/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "GKViewController.h"


@class GKGame, GKRemoteViewController;



@interface GKHostedViewController : GKViewController

{

    _Bool _presentingRemoteViewController;

    _Bool _shouldPresentRemoteViewController;

    _Bool _isRequestingRemoteViewController;

    _Bool _gkIsDisappearing;

    GKGame *_game;

    GKRemoteViewController *_remoteViewController;

    id _remoteViewReadyHandler;

}



- (id)_presentingViewController;

- (_Bool)automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers;

- (void)dealloc;

- (void)didGetRemoteViewController;

- (void)didReceiveMemoryWarning;

- (void)dismissModalViewControllerAnimated:(_Bool)arg1;

- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(id)arg2;

- (void)donePressed:(id)arg1;

@property(retain, nonatomic) GKGame *game; // @synthesize game=_game;

@property(nonatomic) _Bool gkIsDisappearing; // @synthesize gkIsDisappearing=_gkIsDisappearing;

- (id)hostSideViewControllerClassName;

- (id)init;

@property(nonatomic) _Bool isRequestingRemoteViewController; // @synthesize isRequestingRemoteViewController=_isRequestingRemoteViewController;

- (void)presentRemoteViewControllerIfNeeded;

@property(nonatomic) _Bool presentingRemoteViewController; // @synthesize presentingRemoteViewController=_presentingRemoteViewController;

@property(retain, nonatomic) GKRemoteViewController *remoteViewController; // @synthesize remoteViewController=_remoteViewController;

@property(copy, nonatomic) id remoteViewReadyHandler; // @synthesize remoteViewReadyHandler=_remoteViewReadyHandler;

- (void)requestRemoteViewControllerIfNeeded;

- (void)resetRemoteViewController;

- (id)serviceSideViewControllerClassName;

@property(nonatomic) _Bool shouldPresentRemoteViewController; // @synthesize shouldPresentRemoteViewController=_shouldPresentRemoteViewController;

- (_Bool)shouldAutomaticallyForwardAppearanceMethods;

- (_Bool)shouldAutomaticallyForwardRotationMethods;

- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;

- (unsigned long long)supportedInterfaceOrientations;

- (void)viewDidAppear:(_Bool)arg1;

- (void)viewDidDisappear:(_Bool)arg1;

- (void)viewDidLoad;

- (void)viewWillAppear:(_Bool)arg1;

- (void)viewWillDisappear:(_Bool)arg1;



@end


