/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "GKPlayerGameCell.h"


@class GKGameRecord;



@interface GKInCommonGameCell : GKPlayerGameCell

{

    GKGameRecord *_localPlayerGameRecord;

}



- (void)didUpdateModel;

- (id)leaderboardStringWithGameRecord:(id)arg1;

@property(retain, nonatomic) GKGameRecord *localPlayerGameRecord; // @synthesize localPlayerGameRecord=_localPlayerGameRecord;

- (void)prepareForReuse;



@end


