/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "GKLeaderboard.h"



@class GKGame, GKLeaderboardItem, GKPlayer, GKScore, NSArray, NSError, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>;



@interface GKSparseLeaderboard : GKLeaderboard

{

    GKGame *_game;

    GKPlayer *_player;

    struct _NSRange _totalRange;

    struct _NSRange _displayedRange;

    NSArray *_showcasedScores;

    unsigned long long _maxLoaded;

    struct _NSRange _currentRange;

    NSMutableArray *_allLeaderboardItems;

    NSMutableDictionary *_playerIDToLeaderboardItems;

    NSObject<OS_dispatch_queue> *_loadQueue;

    _Bool _loaded;

    GKScore *_comparePlayerScore;

    NSError *_error;

    GKLeaderboardItem *_localPlayerItem;

    GKLeaderboardItem *_comparePlayerItem;

}



- (void)addLeaderboardItems:(id)arg1;

@property(retain, nonatomic) GKLeaderboardItem *comparePlayerItem; // @synthesize comparePlayerItem=_comparePlayerItem;

@property(retain, nonatomic) GKScore *comparePlayerScore; // @synthesize comparePlayerScore=_comparePlayerScore;

- (void)dealloc;

- (id)description;

@property(readonly, nonatomic) _Bool displayComparePlayer;

@property(readonly, nonatomic) _Bool displayLocalPlayer;

@property(nonatomic) struct _NSRange displayedRange; // @synthesize displayedRange=_displayedRange;

@property(retain, nonatomic) NSError *error; // @synthesize error=_error;

@property(retain, nonatomic) GKGame *game; // @synthesize game=_game;

- (unsigned long long)indexOfLeaderboardItemForPlayerID:(id)arg1;

- (id)initWithGame:(id)arg1;

- (id)leaderboardItemAtIndex:(unsigned long long)arg1;

- (id)leaderboardItemForPlayerID:(id)arg1;

- (id)leaderboardItemsForPlayerIDs:(id)arg1;

@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *loadQueue; // @synthesize loadQueue=_loadQueue;

- (void)loadScoresForGame:(id)arg1 withCompletionHandler:(id)arg2;

@property(readonly, nonatomic) _Bool loaded; // @synthesize loaded=_loaded;

@property(readonly, nonatomic) struct _NSRange loadedRange;

@property(retain, nonatomic) GKLeaderboardItem *localPlayerItem; // @synthesize localPlayerItem=_localPlayerItem;

@property(readonly, nonatomic) _Bool moreScoresAvailable;

- (unsigned long long)numberOfLeaderboardItems;

- (id)placeholderLeaderboardItemsForRankRange:(struct _NSRange)arg1;

@property(retain, nonatomic) GKPlayer *player; // @synthesize player=_player;

- (struct _NSRange)rangeToLoadForRank:(unsigned long long)arg1;

- (void)setLocalPlayerScore:(id)arg1;

- (id)showcasedLeaderboardItemAtShowcaseIndex:(unsigned long long)arg1;

@property(readonly, nonatomic) _Bool showcasedScoresAdjacent;

@property(readonly, nonatomic) struct _NSRange totalRange; // @synthesize totalRange=_totalRange;

- (id)visibleLeaderboardItemAtIndex:(unsigned long long)arg1;



@end


