/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "GKServiceViewControllerDelegate.h"



@protocol GKTurnBasedServiceViewControllerDelegate <GKServiceViewControllerDelegate>

- (void)finishWithError:(id)arg1;

- (void)finishWithMatch:(id)arg1;

- (void)playerQuitMatch:(id)arg1;

@end


