/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "IMAVInterface.h"


#import "AVConferenceDelegate.h"



@class AVConference, NSLock, NSMutableArray, NSMutableDictionary;



@interface IMAVConferenceInterface : IMAVInterface <AVConferenceDelegate>

{

    NSMutableArray *_avConferencesToCleanup;

    NSMutableDictionary *_avConferences;

    NSLock *_avConferencesLock;

    _Bool _duringInit;

    _Bool _pendingCleanup;

}



+ (void)_postParticipantMediaChangeNotification:(id)arg1 cameraChanged:(_Bool)arg2 orientationChanged:(_Bool)arg3 aspectChanged:(_Bool)arg4 contentRectChanged:(_Bool)arg5 cameraWillSwitch:(_Bool)arg6 camera:(unsigned int)arg7 orentation:(unsigned int)arg8 aspect:(struct CGSize)arg9 contentRect:(struct CGRect)arg10;

+ (void)_postParticipantScreenAttributesChangeNotification:(id)arg1 cameraChanged:(_Bool)arg2 orientationChanged:(_Bool)arg3 aspectChanged:(_Bool)arg4 cameraWillSwitch:(_Bool)arg5 camera:(unsigned int)arg6 orentation:(unsigned int)arg7 aspect:(struct CGSize)arg8;

+ (_Bool)_useMultipleAVConference;

- (void)_avChatDealloc:(id)arg1;

- (id)_avChatForConference:(id)arg1;

- (id)_avChatForConference:(id)arg1 callID:(long long)arg2 errorString:(id)arg3;

- (void)_cleanupAVInterface;

- (void)_conferenceEnded:(id)arg1;

- (id)_conferenceForAVChat:(id)arg1;

- (void)_configureAVConference:(id)arg1 forChat:(id)arg2;

- (id)_controller;

- (id)_existingConferenceForAVChat:(id)arg1;

- (id)_existingConferenceForAVChatGUID:(id)arg1;

- (_Bool)_hasAVConferenceObjectsForChatsOtherThan:(id)arg1;

- (id)_imAVChatParticipantForConference:(id)arg1 callID:(long long)arg2 errorString:(id)arg3;

- (void)_notifyAboutPotentialCallForChat:(id)arg1;

- (void)_queueAVConferenceForCleanup:(id)arg1;

- (void)_setAudioSessionPropertiesForChat:(id)arg1;

- (_Bool)_submitEndCallMetric:(id)arg1 forCallID:(long long)arg2;

- (_Bool)_submitLoggingInformation:(id)arg1 forChat:(id)arg2;

- (int)avChat:(id)arg1 endConferenceForUserID:(id)arg2;

- (_Bool)avChat:(id)arg1 generateCallInfoForID:(id)arg2 service:(id)arg3 usingRelay:(_Bool)arg4 callInfo:(id)arg5;

- (void)avChat:(id)arg1 prepareConnectionWithCallInfo:(id)arg2;

- (void)avChat:(id)arg1 setLocalLandscapeAspectRatio:(struct CGSize)arg2 localPortraitAspectRatio:(struct CGSize)arg3;

- (void)avChat:(id)arg1 setMute:(_Bool)arg2;

- (void)avChat:(id)arg1 setPaused:(_Bool)arg2;

- (void)avChat:(id)arg1 setSendingAudio:(_Bool)arg2;

- (void)avChat:(id)arg1 setSendingVideo:(_Bool)arg2;

- (unsigned long long)capabilities;

- (unsigned long long)capabilitiesOfCPU;

- (unsigned long long)capabilitiesOfNetwork;

- (void)chatStateUpdated;

- (void)conference:(id)arg1 cancelRelayRequest:(long long)arg2 requestDict:(id)arg3;

- (void)conference:(id)arg1 didChangeLocalVariablesForCallID:(long long)arg2;

- (void)conference:(id)arg1 didStartSession:(_Bool)arg2 withUserInfo:(id)arg3;

- (void)conference:(id)arg1 didStopWithCallID:(long long)arg2 error:(id)arg3;

- (void)conference:(id)arg1 didStopWithCallID:(long long)arg2 error:(id)arg3 callMetadata:(id)arg4;

- (void)conference:(id)arg1 inititiateRelayRequest:(long long)arg2 requestDict:(id)arg3;

- (void)conference:(id)arg1 localIPChange:(id)arg2 withCallID:(long long)arg3;

- (void)conference:(id)arg1 receivedFirstRemoteFrameForCallID:(long long)arg2;

- (void)conference:(id)arg1 receivedNoRemotePacketsForTime:(double)arg2 callID:(long long)arg3;

- (void)conference:(id)arg1 remoteAudioPaused:(_Bool)arg2 callID:(long long)arg3;

- (void)conference:(id)arg1 remoteScreenAttributesChanged:(id)arg2 callID:(long long)arg3;

- (void)conference:(id)arg1 remoteVideoAttributesChanged:(id)arg2 callID:(long long)arg3;

- (void)conference:(id)arg1 remoteVideoPaused:(_Bool)arg2 callID:(long long)arg3;

- (void)conference:(id)arg1 sendRelayUpdate:(long long)arg2 updateDict:(id)arg3;

- (void)conference:(id)arg1 updateInputMeterLevel:(float)arg2;

- (void)conference:(id)arg1 updateOutputMeterLevel:(float)arg2;

- (void)conference:(id)arg1 videoQualityNotificationForCallID:(long long)arg2 isDegraded:(_Bool)arg3 isRemote:(_Bool)arg4;

- (void)conference:(id)arg1 withCallID:(long long)arg2 networkHint:(_Bool)arg3;

- (void)conference:(id)arg1 withCallID:(long long)arg2 remoteMediaStalled:(_Bool)arg3;

@property(readonly, nonatomic) AVConference *controller;

- (void)dealloc;

- (void)endAVConferenceWithChat:(id)arg1 callID:(long long)arg2;

- (int)endConferenceForAVChat:(id)arg1;

- (id)getNatIPFromICEData:(id)arg1;

- (void)handleRelayCancel:(id)arg1 fromParticipant:(id)arg2 callInfo:(id)arg3;

- (void)handleRelayInitate:(id)arg1 fromParticipant:(id)arg2 callInfo:(id)arg3;

- (void)handleRelayUpdate:(id)arg1 fromParticipant:(id)arg2 callInfo:(id)arg3;

- (id)init;

- (void)initAVInterface;

- (_Bool)isAVInterfaceReady;

- (_Bool)isMuteForAVChat:(id)arg1;

- (_Bool)isPausedForAVChat:(id)arg1;

- (_Bool)isSendingAudioForAVChat:(id)arg1;

- (_Bool)isSendingVideoForAVChat:(id)arg1;

- (void *)localVideoBackLayer;

- (void *)localVideoLayer;

- (id)natTypeForAVChat:(id)arg1;

- (void)processRemoteIPChanged:(id)arg1 fromParticipant:(id)arg2;

- (void *)remoteVideoBackLayerForChat:(id)arg1;

- (void *)remoteVideoLayerForChat:(id)arg1;

- (void)serverDiedForConference:(id)arg1;

- (void)setLocalVideoBackLayer:(void *)arg1;

- (void)setLocalVideoLayer:(void *)arg1;

- (void)setRemoteVideoBackLayer:(void *)arg1 forChat:(id)arg2;

- (void)setRemoteVideoLayer:(void *)arg1 forChat:(id)arg2;

- (void)setRemoteVideoLayersFromChat:(id)arg1 toChat:(id)arg2;

- (_Bool)startPreviewWithError:(id *)arg1;

- (_Bool)stopPreview;

- (_Bool)supportsLayers;

- (_Bool)supportsRelay;

- (void)updateAVChat:(id)arg1 withCallMetadata:(id)arg2;



@end


