/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "CNFRegAuthorizedAccountWebViewController.h"


@class IMAccount;



@interface CNFRegSecureAccountWebViewController : CNFRegAuthorizedAccountWebViewController

{

    IMAccount *_account;

    _Bool _triedGettingNewCredentials;

    _Bool _gotNewCredential;

    unsigned long long _signinFailureCount;

}



- (void)_handleTimeout;

- (void)_incrementSigninFailureCount;

- (void)_launchForgotPasswordUrl;

- (void)_resetSigninFailureCount;

- (void)_setupAccountHandlers;

- (void)_showBadPasswordAlert;

- (void)_showForgotPasswordAlert;

- (void)_showRegistrationFailureWithError:(id)arg1;

- (void)_showRequestPasswordAlert;

@property(retain, nonatomic) IMAccount *account; // @synthesize account=_account;

- (id)authIdHeaderValue;

- (id)authTokenHeaderValue;

- (void)dealloc;

- (void)doHandoffWithStatus:(int)arg1 appleID:(id)arg2 authID:(id)arg3 authToken:(id)arg4;

- (id)initWithRegController:(id)arg1 account:(id)arg2;

- (void)viewDidAppear:(_Bool)arg1;

- (void)viewWillDisappear:(_Bool)arg1;



@end


