/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





__attribute__((visibility("hidden")))

@interface EKCollectableReplyHandler : NSObject

{

    id _block;

}



- (void)callWithData:(id)arg1;

- (void)dealloc;

- (id)initWithBlock:(id)arg1;



@end


