/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "EKPersistentObject.h"


@class EKPersistentCalendar, NSDate, NSString;



__attribute__((visibility("hidden")))

@interface EKPersistentInviteReplyNotification : EKPersistentObject

{

}



+ (id)defaultPropertiesToLoad;

+ (id)relations;

@property(readonly, nonatomic) _Bool alerted;

@property(readonly, nonatomic) EKPersistentCalendar *calendar;

@property(readonly, nonatomic) NSString *calendarName;

@property(readonly, nonatomic) NSDate *creationDate;

@property(readonly, nonatomic) NSString *shareeAddress;

@property(readonly, nonatomic) NSString *shareeDisplayName;

@property(readonly, nonatomic) NSString *shareeFirstName;

@property(readonly, nonatomic) NSString *shareeLastName;

@property(readonly, nonatomic) int status;



@end


