/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "NSCopying.h"



@class NSDate;



@interface EKRecurrenceEnd : NSObject <NSCopying>

{

    NSDate *_endDate;

    unsigned long long _occurrenceCount;

}



+ (id)recurrenceEndWithEndDate:(id)arg1;

+ (id)recurrenceEndWithOccurrenceCount:(unsigned long long)arg1;

- (id)copyWithZone:(struct _NSZone *)arg1;

- (void)dealloc;

- (id)description;

- (void)encodeWithCoder:(id)arg1;

@property(readonly, nonatomic) NSDate *endDate; // @synthesize endDate=_endDate;

- (unsigned long long)hash;

- (id)initWithCoder:(id)arg1;

- (id)initWithEndDate:(id)arg1;

- (id)initWithOccurrenceCount:(unsigned long long)arg1;

- (_Bool)isEqual:(id)arg1;

@property(readonly, nonatomic) unsigned long long occurrenceCount; // @synthesize occurrenceCount=_occurrenceCount;

@property(readonly, nonatomic) _Bool usesEndDate;



@end


