/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "EKPredicate.h"


@class NSDate;



@interface EKScheduledReminderPredicate : EKPredicate

{

    NSDate *_day;

}



+ (id)predicateForScheduledRemindersInCalendars:(id)arg1 onDay:(id)arg2;

- (id)copyWithZone:(struct _NSZone *)arg1;

@property(retain, nonatomic) NSDate *day; // @synthesize day=_day;

- (void)dealloc;

- (void)encodeWithCoder:(id)arg1;

- (id)initWithCoder:(id)arg1;



@end


