/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "MKDirections.h"


@interface _MKDirections : MKDirections

{

}



- (void)calculateETAWithCompletionHandler:(id)arg1;

@property(readonly, nonatomic, getter=isBusy) _Bool busy;



@end


