/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "NSMutableArray.h"



@interface NSMutableArray (MKSortedAnnotationsInsertion)

- (unsigned long long)_mapkit_insertSortedAnnotationView:(id)arg1;

- (unsigned long long)_mapkit_insertSortedAnnotationView:(id)arg1 reverse:(_Bool)arg2;

@end


