/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "CBPeripheralDelegate.h"

#import "CBPeripheralPairingDelegate.h"



@class AXHearingAidMode, AXTimer, CBPeripheral, NSArray, NSDate, NSMutableDictionary, NSString;



@interface AXHearingAidDevice : NSObject <CBPeripheralDelegate, CBPeripheralPairingDelegate>

{

    double _leftVolume;

    double _rightVolume;

    double _leftMicrophoneVolume;

    double _rightMicrophoneVolume;

    double _leftStreamVolume;

    double _rightStreamVolume;

    _Bool _keepInSync;

    _Bool _finishedLoading;

    long long initialLoadToken;

    AXTimer *_propertyWriteTimer;

    _Bool _isListeningForStreamingChanges;

    _Bool isPaired;

    _Bool isConnecting;

    _Bool isPersistent;

    NSString *leftUUID;

    NSString *rightUUID;

    NSString *name;

    NSString *manufacturer;

    NSString *model;

    NSString *leftFirmwareVersion;

    NSString *rightFirmwareVersion;

    NSString *leftHardwareVersion;

    NSString *rightHardwareVersion;

    double rightBatteryLevel;

    double leftBatteryLevel;

    NSArray *rightPrograms;

    NSArray *leftPrograms;

    AXHearingAidMode *currentRightProgram;

    AXHearingAidMode *currentLeftProgram;

    CBPeripheral *leftPeripheral;

    CBPeripheral *rightPeripheral;

    long long leftLoadedProperties;

    long long rightLoadedProperties;

    NSMutableDictionary *leftPropertiesLoadCount;

    NSMutableDictionary *rightPropertiesLoadCount;

    NSString *leftPeripheralUUID;

    NSString *rightPeripheralUUID;

    long long leftWriteRequestProperties;

    long long rightWriteRequestProperties;

    long long leftProgramVersion;

    long long rightProgramVersion;

    long long _leftWriteResponseProperties;

    long long _rightWriteResponseProperties;

    NSDate *_leftBatteryLowDate;

    NSDate *_rightBatteryLowDate;

}



+ (id)characteristicsUUIDs;

- (void)_init;

- (void)_sendDelayedWrites;

- (_Bool)addPeripheral:(id)arg1;

- (void)connect;

- (void)connectionDidChange;

- (_Bool)containsPeripheralWithUUID:(id)arg1;

@property(retain, nonatomic) AXHearingAidMode *currentLeftProgram; // @synthesize currentLeftProgram;

@property(retain, nonatomic) AXHearingAidMode *currentRightProgram; // @synthesize currentRightProgram;

- (void)dealloc;

- (void)delayWriteProperty:(long long)arg1 forPeripheral:(id)arg2;

- (id)description;

- (id)deviceDescription;

- (id)deviceUUID;

- (_Bool)didLoadBasicProperties;

- (_Bool)didLoadRequiredProperties;

- (void)disconnect;

- (id)initWithPeripheral:(id)arg1;

- (id)initWithPersistentRepresentation:(id)arg1;

- (_Bool)isConnected;

@property(nonatomic) _Bool isConnecting; // @synthesize isConnecting;

@property(nonatomic) _Bool isPaired; // @synthesize isPaired;

@property(nonatomic) _Bool isPersistent; // @synthesize isPersistent;

@property(nonatomic) _Bool keepInSync; // @synthesize keepInSync=_keepInSync;

- (_Bool)leftAvailable;

@property(nonatomic) double leftBatteryLevel; // @synthesize leftBatteryLevel;

@property(retain, nonatomic) NSDate *leftBatteryLowDate; // @synthesize leftBatteryLowDate=_leftBatteryLowDate;

@property(retain, nonatomic) NSString *leftFirmwareVersion; // @synthesize leftFirmwareVersion;

@property(retain, nonatomic) NSString *leftHardwareVersion; // @synthesize leftHardwareVersion;

@property(nonatomic) long long leftLoadedProperties; // @synthesize leftLoadedProperties;

@property(nonatomic) double leftMicrophoneVolume; // @synthesize leftMicrophoneVolume=_leftMicrophoneVolume;

@property(retain, nonatomic) CBPeripheral *leftPeripheral; // @synthesize leftPeripheral;

@property(retain, nonatomic) NSString *leftPeripheralUUID; // @synthesize leftPeripheralUUID;

@property(nonatomic) long long leftProgramVersion; // @synthesize leftProgramVersion;

@property(copy, nonatomic) NSArray *leftPrograms; // @synthesize leftPrograms;

@property(retain, nonatomic) NSMutableDictionary *leftPropertiesLoadCount; // @synthesize leftPropertiesLoadCount;

- (id)leftSelectedProgram;

@property(nonatomic) double leftStreamVolume; // @synthesize leftStreamVolume=_leftStreamVolume;

@property(retain, nonatomic) NSString *leftUUID; // @synthesize leftUUID;

@property(nonatomic) long long leftWriteRequestProperties; // @synthesize leftWriteRequestProperties;

@property(nonatomic) long long leftWriteResponseProperties; // @synthesize leftWriteResponseProperties=_leftWriteResponseProperties;

- (void)loadBasicProperties;

- (void)loadFailedProperties;

- (void)loadProperties:(long long)arg1 forPeripheral:(id)arg2 withRetryPeriod:(double)arg3;

- (void)loadRequiredProperties;

@property(retain, nonatomic) NSString *manufacturer; // @synthesize manufacturer;

- (void)mateWithDevice:(id)arg1;

@property(retain, nonatomic) NSString *model; // @synthesize model;

@property(retain, nonatomic) NSString *name; // @synthesize name;

- (id)peripheral:(id)arg1 characteristicForProperty:(long long)arg2;

- (id)peripheral:(id)arg1 characteristicForUUID:(id)arg2;

- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;

- (void)peripheral:(id)arg1 didDiscoverServices:(id)arg2;

- (void)peripheral:(id)arg1 didFinishPairingWithResult:(id)arg2;

- (void)peripheral:(id)arg1 didInvalidateServices:(id)arg2;

- (_Bool)peripheral:(id)arg1 didLoadProperty:(long long)arg2;

- (void)peripheral:(id)arg1 didUpdateCharacteristic:(id)arg2;

- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;

- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;

- (long long)peripheral:(id)arg1 propertyForCharacteristic:(id)arg2;

- (void)peripheralDidUnpair:(id)arg1;

- (void)peripheralDidUpdateName:(id)arg1;

- (id)persistentRepresentation;

- (id)programs;

- (void)readProperty:(long long)arg1 fromPeripheral:(id)arg2;

- (void)readValueForCharacteristic:(id)arg1 fromPeripheral:(id)arg2;

- (_Bool)rightAvailable;

@property(nonatomic) double rightBatteryLevel; // @synthesize rightBatteryLevel;

@property(retain, nonatomic) NSDate *rightBatteryLowDate; // @synthesize rightBatteryLowDate=_rightBatteryLowDate;

@property(retain, nonatomic) NSString *rightFirmwareVersion; // @synthesize rightFirmwareVersion;

@property(retain, nonatomic) NSString *rightHardwareVersion; // @synthesize rightHardwareVersion;

@property(nonatomic) long long rightLoadedProperties; // @synthesize rightLoadedProperties;

@property(nonatomic) double rightMicrophoneVolume; // @synthesize rightMicrophoneVolume=_rightMicrophoneVolume;

@property(retain, nonatomic) CBPeripheral *rightPeripheral; // @synthesize rightPeripheral;

@property(retain, nonatomic) NSString *rightPeripheralUUID; // @synthesize rightPeripheralUUID;

@property(nonatomic) long long rightProgramVersion; // @synthesize rightProgramVersion;

@property(copy, nonatomic) NSArray *rightPrograms; // @synthesize rightPrograms;

@property(retain, nonatomic) NSMutableDictionary *rightPropertiesLoadCount; // @synthesize rightPropertiesLoadCount;

- (id)rightSelectedProgram;

@property(nonatomic) double rightStreamVolume; // @synthesize rightStreamVolume=_rightStreamVolume;

@property(retain, nonatomic) NSString *rightUUID; // @synthesize rightUUID;

@property(nonatomic) long long rightWriteRequestProperties; // @synthesize rightWriteRequestProperties;

@property(nonatomic) long long rightWriteResponseProperties; // @synthesize rightWriteResponseProperties=_rightWriteResponseProperties;

- (id)rssi;

- (void)selectProgram:(id)arg1;

- (id)selectedProgramIndexes;

- (id)selectedPrograms;

- (void)setLeftSelectedProgram:(id)arg1;

- (void)setNotify:(_Bool)arg1 forPeripheral:(id)arg2;

- (void)setRightSelectedProgram:(id)arg1;

- (void)setValue:(id)arg1 forProperty:(long long)arg2;

- (void)updateName;

- (id)valueForProperty:(long long)arg1;

- (unsigned char)volumeValueForProperty:(long long)arg1 andPeripheral:(id)arg2;

- (void)writeInt:(unsigned char)arg1 toPeripheral:(id)arg2 forProperty:(long long)arg3;



@end


