/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "ICSProperty.h"


@class NSString;



@interface ICSDate : ICSProperty

{

}



- (id)components;

- (id)description;

- (_Bool)hasFloatingTimeZone;

- (_Bool)hasTimeComponent;

- (id)initWithValue:(id)arg1;

- (id)initWithYear:(long long)arg1 month:(long long)arg2 day:(long long)arg3;

- (id)initWithYear:(long long)arg1 month:(long long)arg2 day:(long long)arg3 hour:(long long)arg4 minute:(long long)arg5 second:(long long)arg6;

- (id)initWithYear:(long long)arg1 month:(long long)arg2 day:(long long)arg3 hour:(long long)arg4 minute:(long long)arg5 second:(long long)arg6 timeZone:(id)arg7;

- (id)parametersToIncludeForChecksumVersion:(int)arg1;

@property(retain) NSString *tzid;



@end


