/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "NSManagedObject.h"



@class NSSet, NSString;



__attribute__((visibility("hidden")))

@interface ACDManagedAccessOptionsKey : NSManagedObject

{

}





// Remaining properties

@property(retain, nonatomic) NSString *name; // @dynamic name;

@property(retain, nonatomic) NSSet *owningAccountTypes; // @dynamic owningAccountTypes;

@end


