/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class AVAsset, AVAssetImageGeneratorInternal, AVVideoComposition, NSString;



@interface AVAssetImageGenerator : NSObject

{

    AVAssetImageGeneratorInternal *_priv;

}



+ (id)assetImageGeneratorWithAsset:(id)arg1;

- (id)_NSErrorForError:(int)arg1;

- (struct CGImage *)_copyCGImageAtTime:(CDStruct_1b6d18a9)arg1 usingAssetReader:(id)arg2 error:(id *)arg3;

- (struct __CFDictionary *)_createPixelBufferAttributesWithSize:(struct CGSize)arg1;

- (void)_didGenerateCGImage:(id)arg1;

- (void)_ensureFigAssetImageGenerator;

- (void)_failedToGenerateCGImage:(id)arg1;

- (id)_makeAutoreleasedAssetReader;

- (id)_optionsDictionary;

- (id)_requestWithRequestID:(id)arg1;

- (struct CGSize)_scaledSizeForRenderSize:(struct CGSize)arg1;

- (void)_serverDied;

@property(copy, nonatomic) NSString *apertureMode;

@property(nonatomic) _Bool appliesPreferredTrackTransform;

@property(readonly, nonatomic) AVAsset *asset;

- (void)cancelAllCGImageGeneration;

- (struct CGImage *)copyCGImageAtTime:(CDStruct_1b6d18a9)arg1 actualTime:(CDStruct_1b6d18a9 *)arg2 error:(id *)arg3;

@property(readonly, nonatomic) id <AVVideoCompositing> customVideoCompositor;

- (void)dealloc;

- (void)finalize;

- (void)generateCGImagesAsynchronouslyForTimes:(id)arg1 completionHandler:(id)arg2;

- (id)init;

- (id)initWithAsset:(id)arg1;

@property(nonatomic) struct CGSize maximumSize;

@property(nonatomic) CDStruct_1b6d18a9 requestedTimeToleranceAfter;

@property(nonatomic) CDStruct_1b6d18a9 requestedTimeToleranceBefore;

@property(copy, nonatomic) AVVideoComposition *videoComposition;



@end


