/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "AVAssetReaderOutput.h"


@class AVAssetReaderAudioMixOutputInternal, AVAudioMix, NSArray, NSDictionary, NSString;



@interface AVAssetReaderAudioMixOutput : AVAssetReaderOutput

{

    AVAssetReaderAudioMixOutputInternal *_audioMixOutputInternal;

}



+ (id)assetReaderAudioMixOutputWithAudioTracks:(id)arg1 audioSettings:(id)arg2;

- (id)_asset;

- (struct opaqueMTAudioProcessingTap *)_audioTapProcessorForTrack:(id)arg1;

- (id)_audioTimePitchAlgorithmForTrack:(id)arg1;

- (id)_audioVolumeCurveForTrack:(id)arg1;

- (_Bool)_enableTrackExtractionReturningError:(id *)arg1;

- (void)_setAudioTapProcessor:(struct opaqueMTAudioProcessingTap *)arg1 forTrack:(id)arg2;

- (void)_setAudioTimePitchAlgorithm:(id)arg1 forTrack:(id)arg2;

- (void)_setAudioVolumeCurve:(id)arg1 forTrack:(id)arg2;

@property(copy, nonatomic) AVAudioMix *audioMix;

@property(readonly, nonatomic) NSDictionary *audioSettings;

@property(copy, nonatomic) NSString *audioTimePitchAlgorithm;

@property(readonly, nonatomic) NSArray *audioTracks;

- (void)dealloc;

- (id)description;

- (void)finalize;

- (id)init;

- (id)initWithAudioTracks:(id)arg1 audioSettings:(id)arg2;

- (id)mediaType;



@end


