/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "AVAssetInspectorLoader.h"


@class AVAssetCache, AVAssetInspector, NSMutableArray, NSURL;



@interface AVAssetMakeReadyForInspectionLoader : AVAssetInspectorLoader

{

    AVAssetInspector *_assetInspector;

    AVAssetCache *_assetCache;

    _Bool _shouldMatchDataInCacheByURLPathComponentOnly;

    _Bool _shouldMatchDataInCacheByURLWithoutQueryComponent;

    NSURL *_downloadDestinationURL;

    struct OpaqueFigFormatReader *_formatReader;

    struct OpaqueFigSimpleMutex *_loadingMutex;

    NSMutableArray *_keysAwaitingCompletion;

    long long _status;

    int _basicInspectionFailureCode;

    NSURL *_URL;

}



- (id)URL;

- (struct OpaqueFigFormatReader *)_copyFormatReaderFromFigObjectWithFigErrorCode:(int *)arg1;

- (id)_dictionaryOfSpecialGettersForKeyValueStatus;

- (id)_dictionaryOfSpecialLoadingMethodsForKeys;

- (struct OpaqueFigFormatReader *)_formatReader;

- (id)_getAndPruneCompletionsWhileMutexLocked;

- (_Bool)_inspectionRequiresAFormatReader;

- (_Bool)_isStreaming;

- (id)_loadValuesUsingDefaultLoadingMethodWhileMutexLockedForKeys:(id)arg1;

- (id)_loadValuesWhileMutexLockedForKeys:(id)arg1;

- (struct OpaqueFigSimpleMutex *)_loadingMutex;

- (struct OpaqueFigPlaybackItem *)_playbackItem;

- (_Bool)_providesAccurateTiming;

- (void)_setStatus:(long long)arg1 figErrorCode:(int)arg2;

- (long long)_status;

- (id)_statusOfValueForKeyThatIsAlwaysLoaded;

- (long long)_statusOfValueWhileMutexLockedForKey:(id)arg1 error:(id *)arg2;

- (_Bool)_statusOfValuesIsTerminalWhileMutexLockedForKeys:(id)arg1;

- (_Bool)_updateStatusWhileMutexLocked:(long long)arg1 figErrorCode:(int)arg2;

@property(readonly, nonatomic) AVAssetCache *assetCache; // @synthesize assetCache=_assetCache;

- (id)assetInspector;

- (void)cancelLoading;

- (id)chapterGroupInfo;

- (id)copyWithZone:(struct _NSZone *)arg1;

- (void)dealloc;

@property(readonly, nonatomic) NSURL *downloadDestinationURL; // @synthesize downloadDestinationURL=_downloadDestinationURL;

- (CDStruct_1b6d18a9)duration;

- (void)finalize;

- (_Bool)hasProtectedContent;

- (id)initWithURL:(id)arg1;

- (_Bool)isComposable;

- (_Bool)isExportable;

- (_Bool)isPlayable;

- (_Bool)isReadable;

- (void)loadValuesAsynchronouslyForKeys:(id)arg1 completionHandler:(id)arg2;

- (id)lyrics;

@property(readonly, nonatomic) _Bool shouldMatchDataInCacheByURLPathComponentOnly; // @synthesize shouldMatchDataInCacheByURLPathComponentOnly=_shouldMatchDataInCacheByURLPathComponentOnly;

@property(readonly, nonatomic) _Bool shouldMatchDataInCacheByURLWithoutQueryComponent; // @synthesize shouldMatchDataInCacheByURLWithoutQueryComponent=_shouldMatchDataInCacheByURLWithoutQueryComponent;

- (long long)statusOfValueForKey:(id)arg1 error:(id *)arg2;



@end


