/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "AVAssetReaderOutput.h"


@class AVAssetReaderVideoCompositionOutputInternal, AVVideoComposition, NSArray, NSDictionary;



@interface AVAssetReaderVideoCompositionOutput : AVAssetReaderOutput

{

    AVAssetReaderVideoCompositionOutputInternal *_videoCompositionOutputInternal;

}



+ (id)assetReaderVideoCompositionOutputWithVideoTracks:(id)arg1 videoSettings:(id)arg2;

- (id)_asset;

- (_Bool)_enableTrackExtractionReturningError:(id *)arg1;

- (id)_errorForOSStatus:(int)arg1;

- (_Bool)_prepareForReadingReturningError:(id *)arg1;

- (void)_setVideoComposition:(id)arg1;

- (void)_setVideoComposition:(id)arg1 customVideoCompositorSession:(id)arg2;

- (_Bool)alwaysCopiesSampleData;

@property(readonly, nonatomic) id <AVVideoCompositing> customVideoCompositor;

- (void)dealloc;

- (id)description;

- (void)finalize;

- (id)init;

- (id)initWithVideoTracks:(id)arg1 videoSettings:(id)arg2;

- (id)mediaType;

@property(copy, nonatomic) AVVideoComposition *videoComposition;

@property(readonly, nonatomic) NSDictionary *videoSettings;

@property(readonly, nonatomic) NSArray *videoTracks;



@end


