/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "NSCopying.h"

#import "NSMutableCopying.h"



@class AVVideoCompositionCoreAnimationTool, AVVideoCompositionInternal, NSArray;



@interface AVVideoComposition : NSObject <NSCopying, NSMutableCopying>

{

    AVVideoCompositionInternal *_videoComposition;

}



+ (void)initialize;

+ (id)videoCompositionWithPropertiesOfAsset:(id)arg1;

+ (id)videoCompositionWithPropertiesOfAsset:(id)arg1 videoGravity:(id)arg2;

- (int)_auxiliaryTrackID;

- (id)_auxiliaryTrackLayer;

- (_Bool)_copyFigVideoCompositor:(const void **)arg1 andSession:(id *)arg2 recyclingSession:(id)arg3 forFigRemaker:(_Bool)arg4 error:(id *)arg5;

- (_Bool)_hasLayerAsAuxiliaryTrack;

- (_Bool)_hasPostProcessingLayers;

- (_Bool)_isValidReturningExceptionReason:(id *)arg1;

- (id)_postProcessingRootLayer;

- (id)_postProcessingVideoLayers;

- (id)_serializableInstructions;

@property(readonly, nonatomic) AVVideoCompositionCoreAnimationTool *animationTool;

- (id)builtInCompositorName;

- (id)copyWithZone:(struct _NSZone *)arg1;

@property(readonly, nonatomic) Class customVideoCompositorClass;

- (void)dealloc;

- (void)finalize;

@property(readonly, nonatomic) CDStruct_1b6d18a9 frameDuration;

- (id)init;

- (id)instructionForFigInstruction:(void *)arg1;

@property(readonly, nonatomic) NSArray *instructions;

- (_Bool)isValidForAsset:(id)arg1 timeRange:(CDStruct_e83c9415)arg2 validationDelegate:(id)arg3;

- (id)mutableCopyWithZone:(struct _NSZone *)arg1;

@property(readonly, nonatomic) float renderScale;

@property(readonly, nonatomic) struct CGSize renderSize;

- (void)setAnimationTool:(id)arg1;

- (void)setBuiltInCompositorName:(id)arg1;

- (void)setCustomVideoCompositorClass:(Class)arg1;

- (void)setFrameDuration:(CDStruct_1b6d18a9)arg1;

- (void)setInstructions:(id)arg1;

- (void)setRenderScale:(float)arg1;

- (void)setRenderSize:(struct CGSize)arg1;



@end


