/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "NSCopying.h"

#import "NSSecureCoding.h"



@class NSData, NSString;



@interface BBSectionIconVariant : NSObject <NSCopying, NSSecureCoding>

{

    _Bool _precomposed;

    long long _format;

    NSData *_imageData;

    NSString *_imagePath;

    NSString *_imageName;

    NSString *_bundlePath;

}



+ (id)_variantWithFormat:(long long)arg1;

+ (_Bool)supportsSecureCoding;

+ (id)variantWithFormat:(long long)arg1 imageData:(id)arg2;

+ (id)variantWithFormat:(long long)arg1 imageName:(id)arg2 inBundle:(id)arg3;

+ (id)variantWithFormat:(long long)arg1 imagePath:(id)arg2;

@property(copy, nonatomic) NSString *bundlePath; // @synthesize bundlePath=_bundlePath;

- (id)copyWithZone:(struct _NSZone *)arg1;

- (void)dealloc;

- (void)encodeWithCoder:(id)arg1;

@property(nonatomic) long long format; // @synthesize format=_format;

@property(copy, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;

@property(copy, nonatomic) NSString *imageName; // @synthesize imageName=_imageName;

@property(copy, nonatomic) NSString *imagePath; // @synthesize imagePath=_imagePath;

- (id)initWithCoder:(id)arg1;

@property(nonatomic, getter=isPrecomposed) _Bool precomposed; // @synthesize precomposed=_precomposed;



@end


