/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSDictionary, NSMutableDictionary, NSNumber, NSString, NSURL;



@interface BookmarkDAVSyncData : NSObject

{

    void *_db;

    NSMutableDictionary *_backingDict;

    _Bool _hasChanges;

}



@property(retain, nonatomic) NSString *accountPrsId;

@property(retain, nonatomic) NSString *bookmarksBarId;

@property(nonatomic) unsigned long long bookmarksBarOrder;

@property(retain, nonatomic) NSString *bookmarksMenuId;

@property(nonatomic) unsigned long long bookmarksMenuOrder;

@property(retain, nonatomic) NSDictionary *bulkRequests;

@property(nonatomic) unsigned long long clientVersion;

@property(retain, nonatomic) NSString *ctag;

- (void)dealloc;

@property(retain, nonatomic) NSString *etag;

@property(readonly) _Bool hasChanges; // @synthesize hasChanges=_hasChanges;

@property(nonatomic) _Bool hasHitQuotaLimit;

@property(retain, nonatomic) NSDictionary *heldAsideOrderings;

@property(retain, nonatomic) NSURL *homeURL;

- (id)initWithBookmarkDatabase:(void *)arg1;

@property(nonatomic) _Bool initialSyncDone;

@property(retain, nonatomic) NSNumber *knownQuotaRemaining;

@property(retain, nonatomic) NSURL *principalURL;

@property(retain, nonatomic) NSString *ptag;

@property(retain, nonatomic) NSString *pushKey;

@property(retain, nonatomic) NSDictionary *pushTransports;

@property(nonatomic) _Bool supportsSyncCollection;

@property(retain, nonatomic) NSString *syncToken;

- (void)writeToBookmarkDB;



@end


