/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class CADisplayMode, NSArray, NSString;



@interface CADisplay : NSObject

{

    void *_impl;

}



+ (id)TVOutDisplay;

+ (_Bool)automaticallyNotifiesObserversForKey:(id)arg1;

+ (id)displays;

+ (id)mainDisplay;

- (id)_initWithDisplay:(struct Display *)arg1;

- (void)_invalidate;

@property _Bool allowsVirtualModes;

@property(readonly, nonatomic) NSArray *availableModes;

@property(readonly, nonatomic) struct CGRect bounds;

@property(copy, nonatomic) NSString *colorMode;

@property(retain, nonatomic) CADisplayMode *currentMode;

- (id)description;

@property(readonly, nonatomic) NSString *deviceName;

@property(readonly) unsigned int displayId;

@property(readonly, getter=isCloned) _Bool cloned;

@property(readonly, getter=isCloningSupported) _Bool cloningSupported;

@property(readonly, getter=isExternal) _Bool external;

@property(readonly, getter=isOverscanned) _Bool overscanned;

@property(readonly, getter=isSupported) _Bool supported;

@property(readonly, nonatomic) NSString *name;

@property(copy, nonatomic) NSString *overscanAdjustment;

@property(readonly) double overscanAmount;

@property(readonly, nonatomic) CADisplayMode *preferredMode;

@property(readonly) double refreshRate;

@property(readonly, nonatomic) struct CGRect safeBounds;

@property(readonly) long long tag;

@property(readonly) NSString *uniqueId;

- (void)update;



@end


