/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class TSUPointerKeyDictionary;



__attribute__((visibility("hidden")))

@interface ECTwoKeyCache : NSObject

{

    TSUPointerKeyDictionary *mCache;

}



- (void)dealloc;

- (id)init;

- (id)objectForKey1:(id)arg1 key2:(id)arg2;

- (void)setObject:(id)arg1 forKey1:(id)arg2 key2:(id)arg3;



@end


