/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "EDCollection.h"


__attribute__((visibility("hidden")))

@interface EDReferenceCollection : EDCollection

{

    _Bool mCoalesce;

}



+ (id)coalesceCollection;

+ (id)noCoalesceCollection;

- (unsigned long long)addObject:(id)arg1;

- (void)coalesce;

- (_Bool)coalesceReferenceAtIndex1:(unsigned long long)arg1 index2:(unsigned long long)arg2;

- (unsigned long long)countOfCellsBeingReferenced;

- (id)init;

- (id)initWihNoCoalesce;

- (void)insertObject:(id)arg1 atIndex:(unsigned long long)arg2;

- (id)referenceToCellWithIndex:(unsigned long long)arg1 byRow:(_Bool)arg2;

- (void)replaceObjectAtIndex:(unsigned long long)arg1 withObject:(id)arg2;

- (id)reverseReferencesByRow:(_Bool)arg1;



@end


