/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





__attribute__((visibility("hidden")))

@interface EXPageSetup : NSObject

{

}



+ (id)edPageMarginsFrom:(struct _xmlNode *)arg1 state:(id)arg2;

+ (int)edPageOrderFromPageOrderString:(id)arg1;

+ (int)edPageOrientationFromPageOrientationString:(id)arg1;

+ (id)edPageSetupFrom:(struct _xmlNode *)arg1 state:(id)arg2;



@end


