/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class MFPGraphicsState;



__attribute__((visibility("hidden")))

@interface MFPGraphicsContainer : NSObject

{

    MFPGraphicsState *mParentGraphicsState;

    struct CGAffineTransform mContainerTransform;

}



- (id).cxx_construct;

- (struct CGAffineTransform)containerTransform;

- (void)dealloc;

- (id)initWithParentGraphicsState:(id)arg1 containerTransform:(struct CGAffineTransform)arg2;

- (id)parentGraphicsState;



@end


