/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "OADShapeGeometry.h"


@class NSMutableArray;



__attribute__((visibility("hidden")))

@interface OADCustomShapeGeometry : OADShapeGeometry

{

    CsRect_0aefebc6 *mGeometryCoordSpace;

    CsPoint_c846a6ec *mLimo;

    NSMutableArray *mFormulas;

    NSMutableArray *mTextBodyRects;

    NSMutableArray *mPaths;

}



- (void)addFormula:(id)arg1;

- (void)addPath:(id)arg1;

- (void)addTextBodyRect:(id)arg1;

- (void)dealloc;

- (id)formulaAtIndex:(unsigned long long)arg1;

- (unsigned long long)formulaCount;

- (CsRect_0aefebc6)geometryCoordSpace;

- (id)init;

- (CsPoint_c846a6ec)limo;

- (id)pathAtIndex:(unsigned long long)arg1;

- (unsigned long long)pathCount;

- (void)setGeometryCoordSpace:(CsRect_0aefebc6)arg1;

- (void)setLimo:(CsPoint_c846a6ec)arg1;

- (id)textBodyRectAtIndex:(unsigned long long)arg1;

- (unsigned long long)textBodyRectCount;



@end


