/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "OADFill.h"


@class OADBlipRef, OADImageFillTechnique, OADRelativeRect;



__attribute__((visibility("hidden")))

@interface OADImageFill : OADFill

{

    OADBlipRef *mBlipRef;

    _Bool mIsBlipRefOverridden;

    OADRelativeRect *mSourceRect;

    _Bool mIsSourceRectOverridden;

    int mDpi;

    _Bool mIsDpiOverridden;

    _Bool mRotateWithShape;

    _Bool mIsRotateWithShapeOverridden;

    OADImageFillTechnique *mTechnique;

    _Bool mIsTechniqueOverridden;

}



+ (id)defaultProperties;

- (id)blipRef;

- (id)color;

- (id)copyWithZone:(struct _NSZone *)arg1;

- (void)dealloc;

- (int)dpi;

- (unsigned long long)hash;

- (id)initWithDefaults;

- (_Bool)isBlipRefOverridden;

- (_Bool)isDpiOverridden;

- (_Bool)isEqual:(id)arg1;

- (_Bool)isRotateWithShapeOverridden;

- (_Bool)isSourceRectOverridden;

- (_Bool)isTechniqueOverridden;

- (_Bool)rotateWithShape;

- (void)setBlipRef:(id)arg1;

- (void)setDpi:(int)arg1;

- (void)setParent:(id)arg1;

- (void)setRotateWithShape:(_Bool)arg1;

- (void)setSourceRect:(id)arg1;

- (void)setStyleColor:(id)arg1;

- (void)setTechnique:(id)arg1;

- (id)sourceRect;

- (id)technique;



@end


