/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class PDRootTimeNode, TSUNoCopyDictionary;



__attribute__((visibility("hidden")))

@interface PDAnimation : NSObject

{

    PDRootTimeNode *mRootTimeNode;

    TSUNoCopyDictionary *mBuildMap;

}



+ (void)initialize;

- (id)addRootTimeNode;

- (id)buildMap;

- (void)dealloc;

- (id)init;

- (id)rootTimeNode;

- (void)setBuildMap:(id)arg1;



@end


