/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "PLChangeNotification.h"


@class NSArray, NSIndexSet, NSString, PLManagedObject, PLObjectSnapshot;



@interface PLContainerChangeNotification : PLChangeNotification

{

    id _object;

    PLObjectSnapshot *_snapshot;

    NSArray *_changedObjects;

    _Bool _didCalculateDiffs;

    _Bool _shouldReload;

    NSIndexSet *_deletedIndexes;

    NSIndexSet *_insertedIndexes;

    NSIndexSet *_movedIndexes;

    struct __CFArray *_movedFromIndexes;

    NSIndexSet *_changedIndexes;

    _Bool _countDidChange;

}



- (void)_calculateDiffs;

- (void)_calculateDiffsIfNecessary;

@property(readonly, nonatomic) NSArray *_changedObjects;

@property(readonly, nonatomic) NSString *_contentRelationshipName;

@property(nonatomic, setter=_setDidCalculateDiffs:) _Bool _didCalculateDiffs;

@property(readonly, nonatomic) NSString *_diffDescription;

- (_Bool)_getOldSet:(id *)arg1 newSet:(id *)arg2;

- (id)_init;

- (id)_initWithObject:(id)arg1 snapshot:(id)arg2 changedObjects:(id)arg3;

@property(readonly, nonatomic) PLManagedObject *_managedObject;

@property(readonly, nonatomic) NSIndexSet *changedIndexes;

@property(readonly, nonatomic) NSIndexSet *changedIndexesRelativeToSnapshot;

@property(readonly, nonatomic) NSArray *changedObjects;

@property(readonly, nonatomic) _Bool countDidChange;

- (void)dealloc;

@property(readonly, nonatomic) NSIndexSet *deletedIndexes;

@property(readonly, nonatomic) NSArray *deletedObjects;

- (void)enumerateMovesWithBlock:(id)arg1;

@property(readonly, nonatomic) _Bool hasMoves;

- (id)init;

@property(readonly, nonatomic) NSIndexSet *insertedIndexes;

@property(readonly, nonatomic) NSArray *insertedObjects;

- (id)name;

- (id)object;

@property(readonly, nonatomic) _Bool shouldReload;

@property(readonly, nonatomic) PLObjectSnapshot *snapshot;

- (unsigned long long)snapshotIndexForContainedObject:(id)arg1;



@end


