/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSMutableDictionary, NSString;



@interface PLEmailAddressManager : NSObject

{

    NSMutableDictionary *_keysForEmails;

    NSMutableDictionary *_emailsForKey;

    int _maxKey;

    NSString *_plistPath;

}



+ (id)sharedManager;

- (void)_loadDictionariesIfNeeded;

- (void)dealloc;

- (id)emailAddressForKey:(id)arg1;

- (id)keyForEmailAddress:(id)arg1;



@end


