/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "PLPhotoDCFObject.h"


@class NSDate, NSMutableSet, NSString, PLPhotoDCFDirectory;



@interface PLPhotoDCFFileGroup : PLPhotoDCFObject

{

    id _delegate;

    PLPhotoDCFDirectory *_directory;

    NSString *_directoryPath;

    NSString *_prebakedThumbnailPath;

    NSString *_videoFileExtension;

    NSMutableSet *_extensions;

    NSDate *_date;

    NSString *_preferredExtension;

    unsigned long long _hash;

    unsigned int _hashComputed:1;

    unsigned int _addedExtensions:1;

    unsigned int _writeIsPending:1;

}



+ (id)allMetadataFileExtensions;

- (void)addExtension:(id)arg1;

- (void)addExtensionsFromMetadataDirectory;

- (long long)compare:(id)arg1;

- (void)createMetadataDirectoryIfNecessary;

- (id)date;

- (void)dealloc;

- (id)delegate;

- (void)deleteFiles;

- (void)deleteObsoleteFiles;

- (id)description;

- (id)directory;

- (id)extensions;

- (void)forceAddExtensionsFromMetadataDirectory;

- (_Bool)hasObsoleteFiles;

- (_Bool)hasPrebakedLandscapeScrubberThumbnails;

- (_Bool)hasPrebakedPortraitScrubberThumbnails;

- (_Bool)hasPrebakedThumbnail;

- (_Bool)hasPrebakedWildcatThumbnails;

- (_Bool)hasThumbnail;

- (_Bool)hasVideoFile;

- (unsigned long long)hash;

- (id)imageSourceTypeHint;

- (id)initWithName:(id)arg1 number:(int)arg2 directory:(id)arg3;

- (_Bool)isEqual:(id)arg1;

- (_Bool)isValid;

- (_Bool)isValidImage;

- (_Bool)isWritePending;

- (id)lowResolutionFilename;

- (id)pathForContainingDirectory;

- (id)pathForFullSizeImage;

- (id)pathForGroupWithoutExtension;

- (id)pathForLowResolutionFile;

- (id)pathForMetadata;

- (id)pathForMetadataWithGroupName;

- (id)pathForPrebakedLandscapeScrubberThumbnails;

- (id)pathForPrebakedPortraitScrubberThumbnails;

- (id)pathForPrebakedThumbnail;

- (id)pathForPrebakedWildcatThumbnailsFile;

- (id)pathForThumbnailFile;

- (id)pathForTrimmedVideoFile;

- (id)pathForVideoFile;

- (id)pathForVideoPreviewFile;

- (id)prebakedLandscapeScrubberThumbnailsFilename;

- (id)prebakedPortraitScrubberThumbnailsFilename;

- (id)prebakedThumbnailFilename;

- (id)prebakedWildcatThumbnailsFilename;

- (void)setDate:(id)arg1;

- (void)setDelegate:(id)arg1;

- (void)setWriteIsPending:(_Bool)arg1;

- (id)thumbnailFilename;

- (id)videoPreviewFilename;



@end


