/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "XCTestRun.h"


@class NSMutableArray;



@interface XCTestSuiteRun : XCTestRun

{

    NSMutableArray *runs;

}



- (void)addTestRun:(id)arg1;

- (void)dealloc;

- (unsigned long long)failureCount;

- (id)initWithTest:(id)arg1;

- (void)start;

- (void)stop;

- (double)testDuration;

- (id)testRuns;

- (unsigned long long)unexpectedExceptionCount;



@end


