/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "XCTestRun.h"


@interface XCTestCaseRun : XCTestRun

{

    unsigned long long failureCount;

    unsigned long long unexpectedExceptionCount;

}



- (unsigned long long)failureCount;

- (void)recordFailureInTest:(id)arg1 withDescription:(id)arg2 inFile:(id)arg3 atLine:(unsigned long long)arg4 expected:(_Bool)arg5;

- (void)start;

- (void)stop;

- (unsigned long long)unexpectedExceptionCount;



@end


