/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "MCRestrictionManager.h"



@class NSDictionary;



@interface MCRestrictionManagerWriter : MCRestrictionManager

{

    int _senderPID;

    NSDictionary *_clientTypeLoaders;

}



+ (id)enforcedAppWhitelistRestrictions;

+ (id)sharedManager;

- (void).cxx_destruct;

- (id)_init;

- (id)_liveClientUUIDsForClientType:(id)arg1;

@property(readonly, nonatomic) NSDictionary *clientTypeLoaders; // @synthesize clientTypeLoaders=_clientTypeLoaders;

- (void)memberQueueCommitClientRestrictionsToDisk;

- (void)memberQueueCommitEffectiveUserSettingsToDiskOldEffectiveUserSettings:(id)arg1;

- (void)memberQueueCommitRestrictionsToDisk;

- (void)memberQueueCommitUserSettingsToDisk;

- (_Bool)memberQueueRecomputeEffectiveUserSettingsPasscode:(id)arg1;

- (_Bool)memberQueueSetAllClientRestrictions:(id)arg1 outRestrictionsChanged:(_Bool *)arg2 outEffectiveSettingsChanged:(_Bool *)arg3 outError:(id *)arg4;

- (_Bool)memberQueueSetParametersForSettingsByType:(id)arg1 passcode:(id)arg2;

- (void)notifyClientsToRecomputeCompliance;

- (void)notifyHaveSeenComplianceMessageWithLastLockDate:(id)arg1;

- (void)recomputeEffectiveUserSettingsPasscode:(id)arg1;

- (_Bool)recomputeNagMetadata;

- (void)removeBoolSetting:(id)arg1;

- (_Bool)removeOrphanedClientRestrictions;

- (void)removeValueSetting:(id)arg1;

- (void)resetAllSettingsToDefaults;

@property(nonatomic) int senderPID; // @synthesize senderPID=_senderPID;

- (_Bool)setAllClientRestrictions:(id)arg1 outRestrictionsChanged:(_Bool *)arg2 outEffectiveSettingsChanged:(_Bool *)arg3 outRecomputedNag:(_Bool *)arg4 outError:(id *)arg5;

- (void)setBoolValue:(_Bool)arg1 forSetting:(id)arg2;

- (_Bool)setClientRestrictions:(id)arg1 clientType:(id)arg2 clientUUID:(id)arg3 localizedClientDescription:(id)arg4 localizedWarning:(id)arg5 outRestrictionsChanged:(_Bool *)arg6 outEffectiveSettingsChanged:(_Bool *)arg7 outRecomputedNag:(_Bool *)arg8 outError:(id *)arg9;

- (void)setIntersectionValues:(id)arg1 forSetting:(id)arg2;

- (_Bool)setParametersForSettingsByType:(id)arg1;

- (_Bool)setParametersForSettingsByType:(id)arg1 passcode:(id)arg2;

- (_Bool)setProfileRestrictions:(id)arg1 outRestrictionsChanged:(_Bool *)arg2 outEffectiveSettingsChanged:(_Bool *)arg3 outAppWhitelistSettingsChanged:(_Bool *)arg4 outRecomputedNag:(_Bool *)arg5 outError:(id *)arg6;

- (void)setShowNagMessage;

- (void)setUnionValues:(id)arg1 forSetting:(id)arg2;

- (void)setUserInfo:(id)arg1 forClientUUID:(id)arg2;

- (void)setValue:(id)arg1 forSetting:(id)arg2;



@end


