/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "NSScanner.h"



@interface NSScanner (NSScannerUtils)

- (id)mf_nextTokenWithPunctuation:(struct __CFCharacterSet *)arg1;

- (_Bool)mf_scanUpAndOverString:(id)arg1;

@end


