/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





__attribute__((visibility("hidden")))

@interface ML3ContainerMediaTypeCounts : NSObject

{

    struct __CFDictionary *_map;

    unsigned long long _count;

}



- (void)addMediaType:(unsigned int)arg1 count:(unsigned long long)arg2;

@property(nonatomic) unsigned long long count; // @synthesize count=_count;

- (void)dealloc;

- (id)description;

- (void)enumerateMediaTypesWithBlock:(id)arg1;

- (id)init;



@end


