/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UITableViewCell.h"



@class NSDate, UIButton, UIDatePicker;



@interface EKCalendarItemRecurrenceEndCell : UITableViewCell

{

    UIButton *_neverButton;

    UIDatePicker *_datePicker;

}



- (void).cxx_destruct;

@property(retain, nonatomic) NSDate *date;

@property(readonly, nonatomic) UIDatePicker *datePicker; // @synthesize datePicker=_datePicker;

- (id)init;

- (void)layoutSubviews;

@property(readonly, nonatomic) UIButton *neverButton; // @synthesize neverButton=_neverButton;



@end


