/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIView.h"



@class EKEvent, NSMutableArray, UILabel, UIScrollView;



__attribute__((visibility("hidden")))

@interface EKDayAllDayView : UIView

{

    long long _orientation;

    NSMutableArray *_occurrenceViews;

    UILabel *_allDay;

    _Bool _allDayLabelHighlighted;

    UIScrollView *_scroller;

    double _occurrenceInset;

    _Bool _allowSelection;

    _Bool _showSelection;

    EKEvent *_selectedEvent;

    _Bool _usesSmallText;

    UIView *_dividerLineViewTop;

    UIView *_dividerLineViewBottom;

    _Bool _showsBorderLines;

    _Bool _showsLabel;

    int _maxVisibleRows;

    id <EKDayAllDayViewDelegate> _delegate;

    double _fixedHeight;

    EKEvent *_dimmedOccurrence;

}



- (void).cxx_destruct;

- (double)_allDayAreaHeightForEventCount:(long long)arg1;

- (double)_borderLineWidth;

- (double)_height;

- (void)addViewToScroller:(id)arg1;

@property(nonatomic) _Bool allowsOccurrenceSelection;

- (_Bool)containsEvent:(id)arg1;

- (void)dayOccurrenceViewClicked:(id)arg1 atPoint:(struct CGPoint)arg2;

@property(nonatomic) __weak id <EKDayAllDayViewDelegate> delegate; // @synthesize delegate=_delegate;

- (void)didMoveToWindow;

@property(retain, nonatomic) EKEvent *dimmedOccurrence; // @synthesize dimmedOccurrence=_dimmedOccurrence;

- (double)firstEventYOffset;

@property(nonatomic) double fixedHeight; // @synthesize fixedHeight=_fixedHeight;

- (id)initWithFrame:(struct CGRect)arg1;

- (_Bool)isAllDayLabelHighlighted;

- (void)layoutSubviews;

@property(nonatomic) int maxVisibleRows; // @synthesize maxVisibleRows=_maxVisibleRows;

@property(readonly, nonatomic) double naturalHeight;

- (double)nextAvailableOccurrenceViewYOrigin;

- (id)occurrenceViewForEvent:(id)arg1;

- (id)occurrenceViews;

- (void)removeAllOccurrenceViews;

- (void)selectEvent:(id)arg1;

- (id)selectedEvent;

- (void)setAllDayLabelColor:(id)arg1;

- (void)setAllDayLabelHighlighted:(_Bool)arg1;

- (void)setBorderColor:(id)arg1;

- (void)setOccurrenceInset:(double)arg1 labelInset:(double)arg2;

- (void)setOccurrences:(id)arg1;

- (void)setOrientation:(long long)arg1;

@property(nonatomic) _Bool showsBorderLines; // @synthesize showsBorderLines=_showsBorderLines;

@property(nonatomic) _Bool showsLabel; // @synthesize showsLabel=_showsLabel;

@property(nonatomic) _Bool showsSelection;

- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;



@end


