/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "EKEventDetailItem.h"


@class CalendarEventAlarmTable, NSArray;



__attribute__((visibility("hidden")))

@interface EKEventAlarmDetailItem : EKEventDetailItem

{

    CalendarEventAlarmTable *_alarmTable;

    unsigned long long _disclosedSubitem;

    NSArray *_alarms;

}



- (void).cxx_destruct;

- (_Bool)_alarmsAreCreatable;

- (_Bool)_alarmsAreEditable;

- (id)cellForSubitemAtIndex:(unsigned long long)arg1;

- (_Bool)configureWithCalendar:(id)arg1 preview:(_Bool)arg2;

- (double)defaultCellHeightForSubitemAtIndex:(unsigned long long)arg1 forWidth:(double)arg2;

- (id)detailViewControllerWithFrame:(struct CGRect)arg1 forSubitemAtIndex:(unsigned long long)arg2;

- (_Bool)editItemViewControllerCommit:(id)arg1;

- (id)init;

- (unsigned long long)numberOfSubitems;

- (void)reset;

- (void)setEvent:(id)arg1 store:(id)arg2;



@end


