/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIView.h"



@class UIDatePicker, UITableView;



__attribute__((visibility("hidden")))

@interface EKPickerTableView : UIView

{

    UIDatePicker *_datePicker;

    UITableView *_tableView;

    _Bool _showsDatePicker;

    _Bool _usesKeyboard;

    id <EKPickerTableViewDelegate> _delegate;

}



- (void).cxx_destruct;

- (void)_datePickerDoubleTapped:(id)arg1;

- (struct CGRect)_frameForDatePicker;

- (double)_heightForDatePicker;

- (void)_updateTableContentInset;

- (void)_updateTableContentInsetForKeyboard:(id)arg1;

- (_Bool)canBecomeFirstResponder;

@property(readonly, nonatomic) UIDatePicker *datePicker; // @synthesize datePicker=_datePicker;

- (void)dealloc;

@property(nonatomic) __weak id <EKPickerTableViewDelegate> delegate; // @synthesize delegate=_delegate;

- (double)heightWithDatePickerAndTableHeight:(double)arg1;

- (id)initWithFrame:(struct CGRect)arg1;

- (id)initWithFrame:(struct CGRect)arg1 tableViewController:(id)arg2;

- (id)inputView;

- (void)layoutSubviews;

@property(nonatomic) _Bool showsDatePicker; // @synthesize showsDatePicker=_showsDatePicker;

- (void)setShowsDatePicker:(_Bool)arg1 animated:(_Bool)arg2;

@property(nonatomic) _Bool usesBlackDatePicker;

@property(nonatomic) _Bool usesKeyboard; // @synthesize usesKeyboard=_usesKeyboard;

- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@property(readonly, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;



@end


