/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class ALAssetPrivate;



@interface ALAsset : NSObject

{

    id _internal;

}



+ (struct CGSize)largePreviewImageSizeForSize:(struct CGSize)arg1;

- (id)_typeAsString;

- (id)_uuid;

- (struct CGImage *)aspectRatioThumbnail;

- (void)dealloc;

- (id)defaultRepresentation;

- (id)description;

- (id)initWithManagedAsset:(id)arg1 library:(id)arg2;

@property(retain, nonatomic) ALAssetPrivate *internal; // @synthesize internal=_internal;

- (_Bool)isDeletable;

@property(readonly, nonatomic, getter=isEditable) _Bool editable;

- (_Bool)isValid;

@property(readonly, nonatomic) ALAsset *originalAsset;

- (id)representationForUTI:(id)arg1;

- (void)requestDefaultRepresentation;

- (void)setExternalUsageIntent:(unsigned long long)arg1;

- (void)setImageData:(id)arg1 metadata:(id)arg2 completionBlock:(id)arg3;

- (void)setLargePreviewImageWithImageData:(id)arg1 completionBlock:(id)arg2;

- (void)setVideoAtPath:(id)arg1 completionBlock:(id)arg2;

- (struct CGImage *)thumbnail;

- (id)valueForProperty:(id)arg1;

- (void)writeModifiedImageDataToSavedPhotosAlbum:(id)arg1 metadata:(id)arg2 completionBlock:(id)arg3;

- (void)writeModifiedVideoAtPathToSavedPhotosAlbum:(id)arg1 completionBlock:(id)arg2;



@end


