/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "_NSUndoObject.h"


__attribute__((visibility("hidden")))

@interface _NSUndoLightInvocation : _NSUndoObject

{

    SEL _selector;

    id _arg;

}



- (id)_argument;

- (void)dealloc;

- (id)description;

- (id)initWithTarget:(id)arg1 selector:(SEL)arg2 object:(id)arg3;

- (void)invoke;



@end


