/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "NSValue.h"


@interface NSConcreteValue : NSValue

{

    unsigned long long _specialFlags;

    void *typeInfo;

}



+ (void)initialize;

+ (_Bool)supportsSecureCoding;

- (const void *)_value;

- (id)copyWithZone:(struct _NSZone *)arg1;

- (id)description;

- (void)encodeWithCoder:(id)arg1;

- (void)getValue:(void *)arg1;

- (unsigned long long)hash;

- (_Bool)isEqualToValue:(id)arg1;

- (const char *)objCType;



@end


