/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "NSTextCheckingResult.h"


@class NSDate, NSTimeZone;



@interface NSDateCheckingResult : NSTextCheckingResult

{

    struct _NSRange _range;

    NSDate *_date;

    NSTimeZone *_timeZone;

    double _duration;

    NSDate *_referenceDate;

    id _underlyingResult;

    _Bool _timeIsSignificant;

    _Bool _timeIsApproximate;

    _Bool _timeIsPast;

}



- (_Bool)_adjustRangesWithOffset:(long long)arg1;

- (id)date;

- (void)dealloc;

- (id)description;

@property(readonly) double duration;

- (void)encodeWithCoder:(id)arg1;

- (id)initWithCoder:(id)arg1;

- (id)initWithRange:(struct _NSRange)arg1 date:(id)arg2;

- (id)initWithRange:(struct _NSRange)arg1 date:(id)arg2 timeZone:(id)arg3 duration:(double)arg4;

- (id)initWithRange:(struct _NSRange)arg1 date:(id)arg2 timeZone:(id)arg3 duration:(double)arg4 referenceDate:(id)arg5;

- (id)initWithRange:(struct _NSRange)arg1 date:(id)arg2 timeZone:(id)arg3 duration:(double)arg4 referenceDate:(id)arg5 underlyingResult:(void *)arg6;

- (id)initWithRange:(struct _NSRange)arg1 date:(id)arg2 timeZone:(id)arg3 duration:(double)arg4 referenceDate:(id)arg5 underlyingResult:(void *)arg6 timeIsSignificant:(_Bool)arg7 timeIsApproximate:(_Bool)arg8;

- (id)initWithRange:(struct _NSRange)arg1 date:(id)arg2 timeZone:(id)arg3 duration:(double)arg4 referenceDate:(id)arg5 underlyingResult:(void *)arg6 timeIsSignificant:(_Bool)arg7 timeIsApproximate:(_Bool)arg8 timeIsPast:(_Bool)arg9;

- (struct _NSRange)range;

@property(readonly) NSDate *referenceDate;

- (id)resultByAdjustingRangesWithOffset:(long long)arg1;

- (unsigned long long)resultType;

@property(readonly) _Bool timeIsApproximate;

@property(readonly) _Bool timeIsPast;

@property(readonly) _Bool timeIsSignificant;

@property(readonly) NSTimeZone *timeZone;

@property(readonly) void *underlyingResult;



@end


