/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



@protocol NSDeserializerStream

- (id)initFromMemoryNoCopy:(const void *)arg1 length:(unsigned long long)arg2 freeWhenDone:(_Bool)arg3;

- (unsigned long long)readAlignedDataSize;

- (void)readData:(void *)arg1 length:(unsigned long long)arg2;

- (int)readInt;

@end


