/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "NSFileAccessClaim.h"


@class NSFileAccessNode, NSURL;



__attribute__((visibility("hidden")))

@interface NSFileReadingWritingClaim : NSFileAccessClaim

{

    NSURL *_readingURL;

    _Bool _readingURLDidChange;

    unsigned long long _readingOptions;

    NSURL *_writingURL;

    _Bool _writingURLDidChange;

    unsigned long long _writingOptions;

    NSFileAccessNode *_readingLocation;

    NSFileAccessNode *_writingLocation;

    NSFileAccessNode *_rootNode;

    long long _readingLinkResolutionCount;

}



- (_Bool)blocksClaim:(id)arg1;

- (void)dealloc;

- (void)devalueSelf;

- (_Bool)evaluateSelfWithRootNode:(id)arg1 checkSubarbitrability:(_Bool)arg2;

- (void)forwardUsingMessageSender:(id)arg1 crashHandler:(void)arg2;

- (void)granted;

- (id)initWithClient:(id)arg1 messageParameters:(id)arg2 replySender:(id)arg3;

- (id)initWithPurposeID:(id)arg1 readingURL:(id)arg2 options:(unsigned long long)arg3 writingURL:(id)arg4 options:(unsigned long long)arg5 claimer:(id)arg6;

- (void)invokeClaimer;

- (_Bool)isBlockedByReadingItemAtLocation:(id)arg1 options:(unsigned long long)arg2;

- (_Bool)isBlockedByWritingItemAtLocation:(id)arg1 options:(unsigned long long)arg2;

- (void)itemAtLocation:(id)arg1 wasReplacedByItemAtLocation:(id)arg2;



@end


