/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@interface NSObject (NSKeyValueCodingPrivate)

+ (id)_createMutableOrderedSetValueGetterWithContainerClassID:(id)arg1 key:(id)arg2;

+ (id)_createMutableSetValueGetterWithContainerClassID:(id)arg1 key:(id)arg2;

+ (id)_createOtherValueGetterWithContainerClassID:(id)arg1 key:(id)arg2;

+ (id)_createOtherValueSetterWithContainerClassID:(id)arg1 key:(id)arg2;

+ (id)_createValueGetterWithContainerClassID:(id)arg1 key:(id)arg2;

+ (id)_createValuePrimitiveGetterWithContainerClassID:(id)arg1 key:(id)arg2;

+ (id)_createValuePrimitiveSetterWithContainerClassID:(id)arg1 key:(id)arg2;

+ (id)_createValueSetterWithContainerClassID:(id)arg1 key:(id)arg2;

@end


