/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "NSCoder.h"


@interface NSPortCoder : NSCoder

{

}



+ (id)allocWithZone:(struct _NSZone *)arg1;

+ (id)portCoderWithReceivePort:(id)arg1 sendPort:(id)arg2 components:(id)arg3;

- (id)_connection;

- (id)connection;

- (id)decodePortObject;

- (void)dispatch;

- (void)encodePortObject:(id)arg1;

- (id)initWithReceivePort:(id)arg1 sendPort:(id)arg2 components:(id)arg3;

- (_Bool)isBycopy;

- (_Bool)isByref;



@end


