/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "NSProxy.h"


@interface NSProtocolChecker : NSProxy

{

}



+ (id)allocWithZone:(struct _NSZone *)arg1;

+ (id)protocolCheckerWithTarget:(id)arg1 protocol:(id)arg2;

- (const char *)_localClassNameForClass;

- (_Bool)conformsToProtocol:(id)arg1;

- (void)doesNotRecognizeSelector:(SEL)arg1;

- (void)forwardInvocation:(id)arg1;

- (id)forwardingTargetForSelector:(SEL)arg1;

- (id)initWithTarget:(id)arg1 protocol:(id)arg2;

- (struct objc_method_description *)methodDescriptionForSelector:(SEL)arg1;

- (id)methodSignatureForSelector:(SEL)arg1;

- (id)protocol;

- (_Bool)respondsToSelector:(SEL)arg1;

- (id)target;



@end


