/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@interface NSXMLParser : NSObject

{

    id _reserved0;

    id _delegate;

    id _reserved1;

    id _reserved2;

    id _reserved3;

}



- (_Bool)_handleParseResult:(long long)arg1;

- (id)_info;

- (void)_initializeSAX2Callbacks;

- (struct _xmlParserCtxt *)_parserContext;

- (void)_popNamespaces;

- (void)_pushNamespaces:(id)arg1;

- (void)_setExpandedParserError:(id)arg1;

- (void)_setParserError:(long long)arg1;

- (void)abortParsing;

- (long long)columnNumber;

- (void)dealloc;

- (id)delegate;

- (void)finalize;

- (_Bool)finishIncrementalParse;

- (id)initForIncrementalParsing;

- (id)initWithContentsOfURL:(id)arg1;

- (id)initWithData:(id)arg1;

- (id)initWithStream:(id)arg1;

- (long long)lineNumber;

- (_Bool)parse;

- (_Bool)parseData:(id)arg1;

- (_Bool)parseFromStream;

- (id)parserError;

- (id)publicID;

- (void)setDelegate:(id)arg1;

- (void)setShouldContinueAfterFatalError:(_Bool)arg1;

- (void)setShouldProcessNamespaces:(_Bool)arg1;

- (void)setShouldReportNamespacePrefixes:(_Bool)arg1;

- (void)setShouldResolveExternalEntities:(_Bool)arg1;

- (_Bool)shouldContinueAfterFatalError;

- (_Bool)shouldProcessNamespaces;

- (_Bool)shouldReportNamespacePrefixes;

- (_Bool)shouldResolveExternalEntities;

- (id)systemID;



@end


