/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@interface WebMIMETypeRegistry : NSObject

{

}



+ (_Bool)isSupportedImageMIMEType:(id)arg1;

+ (_Bool)isSupportedMediaMIMEType:(id)arg1;

+ (id)mimeTypeForExtension:(id)arg1;

+ (id)preferredExtensionForMIMEType:(id)arg1;



@end


