/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "WebBasePluginPackage.h"


@class NSBundle;



__attribute__((visibility("hidden")))

@interface WebPluginPackage : WebBasePluginPackage

{

    NSBundle *nsBundle;

}



- (id)bundle;

- (void)dealloc;

- (id)initWithPath:(id)arg1;

- (_Bool)load;

- (Class)viewFactory;



@end


