/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSArray, NSString;



@interface WebRenderLayer : NSObject

{

    NSArray *children;

    NSString *name;

    NSString *compositingInfo;

    struct CGRect bounds;

    _Bool composited;

    _Bool separator;

}



+ (id)compositingInfoForLayer:(struct RenderLayer *)arg1;

+ (id)nameForLayer:(struct RenderLayer *)arg1;

- (id).cxx_construct;

- (void)buildDescendantLayers:(struct RenderLayer *)arg1;

- (id)children;

- (id)compositingInfo;

- (void)dealloc;

- (id)heightString;

- (id)initWithName:(id)arg1;

- (id)initWithRenderLayer:(struct RenderLayer *)arg1;

- (id)initWithWebFrame:(id)arg1;

- (_Bool)isComposited;

- (_Bool)isSeparator;

- (id)name;

- (id)positionString;

- (id)widthString;



@end


