/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "GQDGraphic.h"


@class GQDChartLegend, GQDChartModel, GQDSStyle;



__attribute__((visibility("hidden")))

@interface GQDChart : GQDGraphic

{

    GQDChartLegend *mLegend;

    _Bool mIsLegendRetained;

    GQDChartModel *mModel;

    GQDSStyle *mStyle;

    long long mType;

}



+ (const struct StateSpec *)stateForReading;

- (void)dealloc;

- (id)graphicStyle;

- (id)legend;

- (id)model;

- (void)setLegend:(id)arg1;

- (id)style;

- (long long)type;



@end


