/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "GQWrapPointGenerator.h"



@class GQDAffineGeometry, GQDBezierPath;



__attribute__((visibility("hidden")))

@interface GQDDrawable : NSObject <GQWrapPointGenerator>

{

    GQDAffineGeometry *mGeometry;

    struct __CFURL *mUrl;

    char *mUid;

    GQDBezierPath *mWrapPath;

    GQDAffineGeometry *mWrapGeometry;

    set_80ec8016 *mInnerWrapPoints;

    _Bool mHasPagesOrder;

    long long mPagesOrder;

}



- (void)addWrapPoint:(id)arg1;

- (void)clearWrapPoints;

- (void)collectWrapPoints:(id)arg1 forPath:(struct CGPath *)arg2 context:(struct FindLinesContext *)arg3;

- (int)collectWrapPointsForState:(id)arg1 graphicStyle:(id)arg2;

- (struct CGPath *)createBezierPath;

- (vector_dadce35e *)createListOfWrapPointsAlongY:(float)arg1 minX:(float)arg2 maxX:(float)arg3 zIndex:(int)arg4;

- (void)dealloc;

- (id)geometry;

- (_Bool)hasPagesOrder;

- (int)pagesOrder;

- (const char *)uid;

- (struct __CFURL *)url;

- (struct __CFString *)urlString;

- (const set_80ec8016 *)wrapPoints;



@end


