/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "GQDRoot.h"


@class GQDSStylesheet;



__attribute__((visibility("hidden")))

@interface GQDLSDocument : GQDRoot

{

    GQDSStylesheet *mStylesheet;

}



+ (struct _xmlNs *)appNamespace;

- (struct __CFString *)createUpgradedAppBundleResourcePath:(struct __CFString *)arg1;

- (struct __CFURL *)createUrlToAppBundleResource:(struct __CFString *)arg1 processorBundle:(struct __CFBundle *)arg2;

- (void)dealloc;

- (void)initializeAppBundleResourcesUrl;

- (void)setStylesheet:(id)arg1;

- (id)stylesheet;



@end


