/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "GQDWPInlineList.h"


@class GQDSStyle;



__attribute__((visibility("hidden")))

@interface GQDWPLink : GQDWPInlineList

{

    GQDSStyle *mCharStyle;

    struct __CFString *mHref;

}



- (id)characterStyle;

- (void)dealloc;

- (struct __CFString *)href;

- (int)readStyleFromReader:(struct _xmlTextReader *)arg1 processor:(id)arg2;



@end


