/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class KNAnimatedBuild, NSArray, NSDictionary;



@protocol KNAnimationPluginContext <NSObject>

@property(readonly, nonatomic) KNAnimatedBuild *animatedBuild;

@property(readonly, nonatomic) unsigned long long direction;

@property(readonly, nonatomic) double duration;

@property(readonly, nonatomic) _Bool isBuild;

@property(readonly, nonatomic) _Bool isFrameRenderer;

@property(readonly, nonatomic) _Bool isMagicMove;

@property(readonly, nonatomic) _Bool isTransition;

@property(readonly, nonatomic) _Bool isWarmingUp;

@property(readonly, nonatomic) NSArray *magicMoveMatches;

@property(readonly, nonatomic) double percent;

@property(readonly, nonatomic) NSArray *textures;

@property(readonly, nonatomic) NSDictionary *transitionAttributes;

@end


