/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "NSCopying.h"



__attribute__((visibility("hidden")))

@interface TNFormulaIDWrapper : NSObject <NSCopying>

{

    CDStruct_a91f2c80 mID;

}



- (id).cxx_construct;

- (CDStruct_a91f2c80)chartFormulaID;

- (id)copyWithZone:(struct _NSZone *)arg1;

- (id)description;

@property(readonly) CDStruct_a91f2c80 formulaID; // @synthesize formulaID=mID;

- (unsigned long long)hash;

- (id)initWithTNChartFormulaID:(CDStruct_a91f2c80)arg1;

- (_Bool)isEqual:(id)arg1;

- (_Bool)isEqualToTNFormulaIDWrapper:(id)arg1;



@end


