/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@protocol TPHeaderFooterProvider <NSObject>

- (id)headerFooter:(int)arg1 fragmentAtIndex:(int)arg2;

- (id)headerFooterFragmentEnumerator;

- (int)headerFooterTypeForModel:(id)arg1;

- (int)headerFragmentIndexForModel:(id)arg1;

- (_Bool)isHeaderFooterEmpty:(int)arg1;

- (_Bool)isHeaderFooterEmpty:(int)arg1 fragmentAtIndex:(int)arg2;

- (_Bool)usesSingleHeaderFooter;

@end


