/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "TSDLayout.h"


@class TPBodyLayout;



__attribute__((visibility("hidden")))

@interface TPPageLayout : TSDLayout

{

}



@property(readonly, nonatomic) _Bool allowsBody;

@property(readonly, nonatomic) _Bool allowsFootnotes;

@property(readonly, nonatomic) _Bool allowsHeaderFooter;

@property(readonly, nonatomic) TPBodyLayout *bodyLayout;

@property(readonly, nonatomic) struct CGRect bodyRect;

@property(readonly, nonatomic) id <NSFastEnumeration> childTextLayoutsForExteriorWrap;

- (id)computeLayoutGeometry;

- (void)dealloc;

- (id)dependentLayouts;

@property(readonly, nonatomic) double footerHeight;

@property(readonly, nonatomic) double headerHeight;

- (void)invalidateLayoutsForPageCountChange;

- (void)invalidateSize;

- (_Bool)isReadyForBodyLayout;

- (_Bool)isRootLayoutForInspectorGeometry;

- (id)layoutsForProvidingGuidesForChildLayouts;

- (void)p_addLayoutsForInfos:(id)arg1 toArray:(id)arg2;

- (unsigned long long)pageIndex;

- (id)pageLayout;

- (void)parentDidChange;

- (void)parentWillChangeTo:(id)arg1;

- (id)primaryLayoutForInfo:(id)arg1;

- (_Bool)providesGuidesForChildLayouts;

- (_Bool)shouldProvideGuidesDuringExclusiveAlignmentOperation;



@end


