/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "NSCopying.h"



__attribute__((visibility("hidden")))

@interface TPPageIndexPath : NSObject <NSCopying>

{

    unsigned long long _sectionIndex;

    unsigned long long _pageIndex;

}



- (id)copyWithZone:(struct _NSZone *)arg1;

- (id)description;

- (id)init;

- (id)initWithSectionIndex:(unsigned long long)arg1 pageIndex:(unsigned long long)arg2;

@property(nonatomic) unsigned long long pageIndex; // @synthesize pageIndex=_pageIndex;

@property(nonatomic) unsigned long long sectionIndex; // @synthesize sectionIndex=_sectionIndex;



@end


