/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "TSATheme.h"


__attribute__((visibility("hidden")))

@interface TPTheme : TSATheme

{

}



+ (void)initialize;

+ (id)themeWithContext:(id)arg1 alternate:(int)arg2;

- (id)_paragraphStylePresetWithName:(id)arg1 orContentTag:(id)arg2;

- (id)bodyStyle;

- (id)footnoteStyle;

- (id)headerAndFooterStyle;

- (id)initFromUnarchiver:(id)arg1;

- (void)p_saveToArchive:(struct ThemeArchive *)arg1 archiver:(id)arg2;

- (void)saveToArchiver:(id)arg1;



@end


