/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSArray, TSCEFunctionSpec;



__attribute__((visibility("hidden")))

@interface TSCEFunctionArgumentSpec : NSObject

{

    int mArgumentType;

    _Bool mForceArrayMode;

    double mMinValue;

    double mMaxValue;

    _Bool mDisallowDuration;

    _Bool mDisallowCurrency;

    short mIndex;

    int mAccessorMode;

    int mArgumentContext;

    int mRangeContext;

    NSArray *mDisallowedTypes;

    vector_10088e46 *mModeValues;

    short mDefaultModeIndex;

    TSCEFunctionSpec *mFunctionSpec;

    _Bool mMinInclusive;

    _Bool mMaxInclusive;

    _Bool mIsInteger;

    _Bool mReferenceForGeometryOnly;

}



+ (id)argumentSpecWithIndex:(short)arg1 type:(int)arg2 accessorMode:(int)arg3 disallowedTypes:(id)arg4 argumentContext:(int)arg5 rangeContext:(int)arg6 minValue:(double)arg7 minInclusive:(_Bool)arg8 maxValue:(double)arg9 maxInclusive:(_Bool)arg10 isInteger:(_Bool)arg11 disallowDuration:(_Bool)arg12 disallowCurrency:(_Bool)arg13 modeValues:(vector_10088e46 *)arg14 defaultModeIndex:(short)arg15 referenceForGeometryOnly:(_Bool)arg16 forceArrayMode:(_Bool)arg17;

- (int)accessorMode;

- (int)argumentContext;

- (void)dealloc;

@property(readonly, nonatomic) short defaultModeIndex; // @synthesize defaultModeIndex=mDefaultModeIndex;

- (_Bool)disallowCurrency;

- (_Bool)disallowDuration;

- (id)disallowedTypes;

- (_Bool)forceArrayMode;

@property(nonatomic) TSCEFunctionSpec *functionSpec; // @synthesize functionSpec=mFunctionSpec;

- (short)index;

- (long long)indexForModeBool:(_Bool)arg1;

- (long long)indexForModeNumber:(double)arg1;

- (long long)indexForModeString:(id)arg1;

- (long long)indexForModeValue:(struct TSCEValue *)arg1;

- (id)initArgumentSpecWithIndex:(short)arg1 type:(int)arg2 accessorMode:(int)arg3 disallowedTypes:(id)arg4 argumentContext:(int)arg5 rangeContext:(int)arg6 minValue:(double)arg7 minInclusive:(_Bool)arg8 maxValue:(double)arg9 maxInclusive:(_Bool)arg10 isInteger:(_Bool)arg11 disallowDuration:(_Bool)arg12 disallowCurrency:(_Bool)arg13 modeValues:(vector_10088e46 *)arg14 defaultModeIndex:(short)arg15 referenceForGeometryOnly:(_Bool)arg16 forceArrayMode:(_Bool)arg17;

- (_Bool)isInteger;

- (_Bool)isMode;

- (_Bool)isOptional;

- (id)localizedArgumentName;

- (id)localizedFunctionName;

- (id)localizedModeMenuItemStringForModeIndex:(short)arg1;

- (id)localizedModeNameForModeIndex:(short)arg1;

- (id)localizedModeToolTipStringForModeIndex:(short)arg1;

- (id)localizedToolTipString;

- (_Bool)maxInclusive;

- (double)maxValue;

- (_Bool)minInclusive;

- (double)minValue;

@property(readonly, nonatomic) vector_10088e46 *modeValues; // @synthesize modeValues=mModeValues;

- (id)nativeSyntaxString;

- (id)nativeSyntaxStringForModeIndex:(short)arg1;

- (short)numModes;

- (int)preferredType;

- (int)rangeContext;

- (_Bool)referenceForGeometryOnly;

- (_Bool)typeIsDisallowed:(int)arg1 value:(struct TSCEValue *)arg2;

- (struct TSCEValue)valueForModeIndex:(short)arg1;



@end


