/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "TSCH3DAnimationInterpolatable.h"



__attribute__((visibility("hidden")))

@interface TSCH3DAnimationTimeSlice : NSObject <TSCH3DAnimationInterpolatable>

{

}



+ (id)linear;

- (float)interpolate:(float)arg1 index:(const tvec2_3b141483 *)arg2;



@end


