/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSString;



__attribute__((visibility("hidden")))

@interface TSCH3DChartAnimationClip : NSObject

{

    NSString *mTimerName;

}



+ (id)clip;

+ (id)clipWithTimerName:(id)arg1;

- (void)dealloc;

- (void)didAddToAnimationClipsWithScene:(id)arg1 animation:(id)arg2;

- (void)didAddToAnimationClipsWithSceneObject:(id)arg1 scene:(id)arg2 animation:(id)arg3;

- (void)didGenerateShaderEffects:(id)arg1 sceneObject:(id)arg2 pipeline:(id)arg3 context:(id)arg4;

- (void)didGenerateShaderEffectsForSeriesAtIndex:(const tvec2_3b141483 *)arg1 effects:(id)arg2 sceneObject:(id)arg3 pipeline:(id)arg4 context:(id)arg5;

- (void)didProcessElements:(id)arg1 sceneObject:(id)arg2 pipeline:(id)arg3 context:(id)arg4;

- (void)didTransformElement:(const struct RenderElementInfo *)arg1 sceneObject:(id)arg2 context:(id)arg3;

- (void)didUpdateAnimationTimeForContext:(id)arg1 layers:(id)arg2;

- (id)init;

- (id)initWithTimerName:(id)arg1;

- (void)labelsResourcesSessionWillBeginForSceneObject:(id)arg1 pipeline:(id)arg2 context:(id)arg3;

- (void)labelsResourcesSessionWillEndForSceneObject:(id)arg1 pipeline:(id)arg2 context:(id)arg3;

- (_Bool)renderPassDelayDisallowedForSceneObject:(id)arg1 pipeline:(id)arg2 context:(id)arg3;

- (struct ElementRenderPass)renderPassForElement:(const struct RenderElementInfo *)arg1 sceneObject:(id)arg2 context:(id)arg3;

- (struct ElementRenderPass)renderPassForSceneObject:(id)arg1;

- (_Bool)shouldUpdateSeriesElementTimingWithAnyElement;

- (float)timeFromContext:(id)arg1;

@property(readonly, nonatomic) NSString *timerName; // @synthesize timerName=mTimerName;

- (void)updateExternalLabelAttribute:(struct ExternalLabelAttribute *)arg1 sceneObject:(id)arg2 labelRenderInfo:(const struct ChartLabelsContainingLabelRenderInfo *)arg3 timeSlice:(id)arg4 context:(id)arg5;

- (_Bool)willProcessElements:(id)arg1 sceneObject:(id)arg2 pipeline:(id)arg3 context:(id)arg4;

- (_Bool)willProcessSeries:(id)arg1 sceneObject:(id)arg2 pipeline:(id)arg3 context:(id)arg4;

- (_Bool)willRenderElement:(const struct RenderElementInfo *)arg1 sceneObject:(id)arg2 context:(id)arg3;

- (void)willRunWithScene:(id)arg1 context:(id)arg2 layers:(id)arg3;

- (_Bool)willSubmitElement:(const struct RenderElementInfo *)arg1 sceneObject:(id)arg2 context:(id)arg3;

- (_Bool)willSubmitLabelForSceneObject:(id)arg1 labelRenderInfo:(const struct ChartLabelsContainingLabelRenderInfo *)arg2 context:(id)arg3;

- (_Bool)willSubmitSceneObject:(id)arg1 pipeline:(id)arg2 context:(id)arg3;

- (_Bool)willUpdateElementEffectsStatesForElement:(const struct RenderElementInfo *)arg1 sceneObject:(id)arg2 context:(id)arg3;



@end


