/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "TSCH3DResource.h"


#import "TSCHUnretainedParent.h"



@class TSCH3DTextureAtlasTexture;



__attribute__((visibility("hidden")))

@interface TSCH3DTextureAtlasTextureResource : TSCH3DResource <TSCHUnretainedParent>

{

    TSCH3DTextureAtlasTexture *mParent;

}



- (void)clearParent;

- (void)dealloc;

- (id)get;

- (id)initWithParent:(id)arg1;



@end


