/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class TSCH3DChartBoundsLayoutSceneDelegate, TSCH3DChartGetProjectedBoundsPipeline, TSCH3DScene;



__attribute__((visibility("hidden")))

@interface TSCH3DChartBoundsLayout : NSObject

{

    TSCH3DScene *mScene;

    TSCH3DScene *mBounds;

    Class mGetBoundsClass;

    TSCH3DChartGetProjectedBoundsPipeline *mGetBounds;

    TSCH3DChartBoundsLayoutSceneDelegate *mSceneDelegate;

    box_80622335 mLayoutInPage;

    box_80622335 mBodyLayoutInPage;

    tvec2_3b141483 mOriginalContainingViewport;

    int mMode;

    CDStruct_9aa9521f mLayoutSettings;

}



- (id).cxx_construct;

@property(nonatomic) box_80622335 bodyLayoutInPage; // @synthesize bodyLayoutInPage=mBodyLayoutInPage;

- (void)cacheLabels;

- (id)cacheableGetBoundsPipeline;

@property(nonatomic) tvec2_3b141483 containingViewport;

- (void)dealloc;

- (id)debugBounds;

@property(retain, nonatomic) Class getBoundsClass; // @synthesize getBoundsClass=mGetBoundsClass;

- (id)init;

- (id)initWithScene:(id)arg1 containingViewport:(const tvec2_3b141483 *)arg2 originalContainingViewport:(const tvec2_3b141483 *)arg3 layoutSettings:(const CDStruct_9aa9521f *)arg4;

- (void)invalidateBounds;

- (void)invalidateLabelsBoundsForSceneObjectClass:(Class)arg1 boundsIndex:(long long)arg2;

- (_Bool)isForward;

- (_Bool)isSage;

@property(nonatomic) box_80622335 layoutInPage; // @synthesize layoutInPage=mLayoutInPage;

@property(readonly, nonatomic) CDStruct_9aa9521f layoutSettings; // @synthesize layoutSettings=mLayoutSettings;

@property(nonatomic) int mode; // @synthesize mode=mMode;

@property(nonatomic) tvec2_3b141483 originalContainingViewport; // @synthesize originalContainingViewport=mOriginalContainingViewport;

- (const struct ChartProjectedBoundsSpaces *)p_projectedBoundsWithLabelsMode:(int)arg1;

- (void)p_updateLabelWrapBoundsPass;

- (const struct ChartProjectedBoundsSpaces *)projectedBounds;

- (void)resetContainingViewport;

- (void)resetSceneDelegate;

- (struct ResizingSize)resizingSize;

@property(readonly, nonatomic) TSCH3DScene *scene; // @synthesize scene=mScene;



@end


