/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "TSCHMultiDataChartType.h"


__attribute__((visibility("hidden")))

@interface TSCHChartTypeMultiDataBar : TSCHMultiDataChartType

{

}



- (id)defaultSeriesType:(unsigned long long)arg1;

- (id)genericToSpecificPropertyMap;

- (id)init;

- (Class)presetImagerClass;

- (Class)repClass;

- (id)userInterfaceName;



@end


