/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



@protocol TSCH3DGLLayer

- (id)cacheLogic;

- (double)contentsScale;

- (id)framebufferFromContext:(id)arg1 attributes:(const struct FramebufferAttributes *)arg2;

- (id)initWithLayerCacheLogicClass:(Class)arg1;

- (Class)layerDelegateClass;

- (void)presentLayerWithPresenterInfo:(const struct PresenterInfo *)arg1;

- (void)setContentsScale:(double)arg1;

- (void)willDestroyFramebuffer:(id)arg1 session:(id)arg2;



@optional

- (void)setCGColorSpace:(struct CGColorSpace *)arg1;

@end


