/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "TSCH3DSceneObject.h"


__attribute__((visibility("hidden")))

@interface TSCH3DSageInvisibleBoundsSceneObject : TSCH3DSceneObject

{

}



- (id)effects;

- (void)get3PieceStageBounds:(id)arg1;

- (void)getBounds:(id)arg1;

- (void)getGridlineSelectionCatcherBounds:(id)arg1;

- (void)render:(id)arg1;

- (void)renderBounds:(id)arg1;



@end


