/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSArray, NSMutableArray, NSMutableString, NSString;



__attribute__((visibility("hidden")))

@interface TSCH3DClipPlaneShaderCombiner : NSObject

{

    NSMutableString *mCondition;

    NSMutableArray *mVariables;

}



+ (id)combiner;

- (void)appendCondition:(id)arg1 variables:(id)arg2;

@property(readonly, nonatomic) NSString *condition; // @synthesize condition=mCondition;

- (void)dealloc;

- (id)init;

@property(readonly, nonatomic) NSArray *variables; // @synthesize variables=mVariables;



@end


