/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "TSDKnobTracker.h"


__attribute__((visibility("hidden")))

@interface TSDButtonKnobTracker : TSDKnobTracker

{

    id mTarget;

    SEL mAction;

}



@property(nonatomic) SEL action; // @synthesize action=mAction;

- (_Bool)allowHUDToDisplay;

- (void)endMovingKnob;

- (id)initWithRep:(id)arg1 knob:(id)arg2;

- (void)moveKnobToRepPosition:(struct CGPoint)arg1;

- (_Bool)operationShouldBeDynamic;

- (_Bool)p_knobContainsCurrentPosition;

@property(nonatomic) id target; // @synthesize target=mTarget;

- (_Bool)shouldHideOtherKnobs;

- (_Bool)shouldHideSelectionHighlight;



@end


