/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "TSDKnob.h"


@class TSDBezierPath, TSUColor;



__attribute__((visibility("hidden")))

@interface TSDCustomShapeKnob : TSDKnob

{

    TSDBezierPath *mPath;

    TSUColor *mColor;

    double mAngle;

}



+ (id)diamondPath;

+ (id)trianglePath;

@property(nonatomic) double angle; // @synthesize angle=mAngle;

@property(copy, nonatomic) TSUColor *color; // @synthesize color=mColor;

- (void)createKnobLayers;

- (id)darkColor;

- (void)dealloc;

- (id)initWithType:(int)arg1 position:(struct CGPoint)arg2 radius:(double)arg3 tag:(unsigned long long)arg4 onRep:(id)arg5;

- (id)layer;

@property(retain, nonatomic) TSDBezierPath *path; // @synthesize path=mPath;



@end


