/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "TSKCommand.h"


@class TSDDrawableComment, TSDDrawableInfo;



__attribute__((visibility("hidden")))

@interface TSDDrawableInfoCommentCommand : TSKCommand

{

    TSDDrawableInfo *mInfo;

    TSDDrawableComment *mNewComment;

    TSDDrawableComment *mOldComment;

}



- (void)commit;

- (void)dealloc;

- (id)initFromUnarchiver:(id)arg1;

- (id)initWithContext:(id)arg1 info:(id)arg2 comment:(id)arg3;

- (void)p_doWithBeginEditing:(_Bool)arg1;

- (_Bool)process;

- (void)redo;

- (void)saveToArchiver:(id)arg1;

- (void)undo;



@end


