/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "TSKCommand.h"


#import "TSDPropagatableCommand.h"



@class TSDImageInfo, TSDMaskInfo;



__attribute__((visibility("hidden")))

@interface TSDImageMaskCommand : TSKCommand <TSDPropagatableCommand>

{

    TSDImageInfo *mInfo;

    TSDMaskInfo *mNewMaskInfo;

    TSDMaskInfo *mOldMaskInfo;

}



- (void)commit;

- (void)dealloc;

- (id)initFromUnarchiver:(id)arg1;

- (id)initWithImageInfo:(id)arg1 newMaskInfo:(id)arg2;

- (_Bool)modifiesAnyObjectPassingTest:(id)arg1;

- (void)p_do;

- (void)populateChangePropagationMapAfterCommit:(id)arg1;

- (_Bool)process;

- (void)redo;

- (void)saveToArchiver:(id)arg1;

- (void)undo;



@end


