/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class TSDMagicMoveAnimationMatch, TSDTextureSet;



__attribute__((visibility("hidden")))

@interface TSDMagicMoveTextureZOrdererMatch : NSObject

{

    _Bool _isOutgoingZIndexUnmatched;

    _Bool _isIncomingZIndexUnmatched;

    TSDTextureSet *_outgoingTexture;

    TSDTextureSet *_incomingTexture;

    long long _outgoingZIndex;

    long long _incomingZIndex;

    TSDMagicMoveAnimationMatch *_animationMatch;

}



@property(readonly, nonatomic) TSDMagicMoveAnimationMatch *animationMatch; // @synthesize animationMatch=_animationMatch;

- (id)description;

@property(readonly, nonatomic) TSDTextureSet *incomingTexture; // @synthesize incomingTexture=_incomingTexture;

@property(nonatomic) long long incomingZIndex; // @synthesize incomingZIndex=_incomingZIndex;

- (id)initWithAnimationMatch:(id)arg1;

- (double)interpolatedZIndexAtPercent:(double)arg1;

- (double)intersectionPercentWithZOrdererMatch:(id)arg1;

- (_Bool)intersectsZOrdererMatch:(id)arg1;

- (_Bool)intersectsZOrdererMatch:(id)arg1 withAttemptedZIndex:(long long)arg2;

@property(readonly, nonatomic) _Bool isIncomingZIndexUnmatched; // @synthesize isIncomingZIndexUnmatched=_isIncomingZIndexUnmatched;

@property(readonly, nonatomic) _Bool isOutgoingZIndexUnmatched; // @synthesize isOutgoingZIndexUnmatched=_isOutgoingZIndexUnmatched;

@property(readonly, nonatomic) TSDTextureSet *outgoingTexture; // @synthesize outgoingTexture=_outgoingTexture;

@property(nonatomic) long long outgoingZIndex; // @synthesize outgoingZIndex=_outgoingZIndex;



@end


