/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "TSKRenderingExporter.h"



@protocol TSKImageExporter <TSKRenderingExporter>

@property(nonatomic) unsigned long long height;

@property(nonatomic) _Bool scaleToFit;

@property(nonatomic) unsigned long long width;

@end


