/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSArray, NSString;



__attribute__((visibility("hidden")))

@interface TSKWarning : NSObject

{

    NSString *mMessage;

    NSArray *mInfos;

    unsigned int mKind;

    int mSeverity;

}



+ (id)warningWithMessage:(id)arg1;

+ (id)warningWithMessage:(id)arg1 kind:(unsigned int)arg2 infos:(id)arg3;

+ (id)warningWithMessage:(id)arg1 kind:(unsigned int)arg2 severity:(int)arg3 infos:(id)arg4;

+ (id)warningWithMessage:(id)arg1 severity:(int)arg2;

- (void)dealloc;

- (unsigned long long)hash;

@property(copy, nonatomic) NSArray *infos; // @synthesize infos=mInfos;

- (id)initWithMessage:(id)arg1 kind:(unsigned int)arg2 severity:(int)arg3 infos:(id)arg4;

- (_Bool)isEqual:(id)arg1;

@property(readonly, nonatomic) unsigned int kind; // @synthesize kind=mKind;

@property(copy, nonatomic) NSString *message; // @synthesize message=mMessage;

@property(readonly, nonatomic) int severity; // @synthesize severity=mSeverity;



@end


