/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSString, NSURL;



__attribute__((visibility("hidden")))

@interface TSPDatabaseObject : NSObject

{

    int _classType;

    long long _identifier;

}



+ (id)databaseObjectWithIdentifier:(long long)arg1 classType:(int)arg2 dataState:(long long)arg3;

+ (id)databaseObjectWithIdentifier:(long long)arg1 classType:(int)arg2 fileState:(id)arg3 packageURL:(id)arg4;

@property(readonly, nonatomic) int classType; // @synthesize classType=_classType;

@property(readonly, nonatomic) long long dataState;

@property(readonly, nonatomic) NSString *fileState;

@property(readonly, nonatomic) NSURL *fileURL;

@property(readonly, nonatomic) _Bool hasDataState;

@property(readonly, nonatomic) _Bool hasFileState;

@property(readonly, nonatomic) long long identifier; // @synthesize identifier=_identifier;

- (id)init;

- (id)initWithIdentifier:(long long)arg1 classType:(int)arg2;



@end


