/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





__attribute__((visibility("hidden")))

@interface TSPIdentifierDictionary : NSObject

{

    struct hash_map<long long, id, TSPIdentifierHasher, std::__1::equal_to<long long>, std::__1::allocator<std::__1::pair<const long long, id>>> *_map;

    int _lock;

}



- (void)dealloc;

- (id)init;

- (void)makeObjectsPerformSelector:(SEL)arg1;

- (void)makeObjectsPerformSelector:(SEL)arg1 withObject:(id)arg2;

- (void)removeAllObjects;

- (void)removeObjectForIdentifier:(long long)arg1;

- (id)retainedObjectForIdentifier:(long long)arg1;

- (void)setObject:(id)arg1 forIdentifier:(long long)arg2;



@end


