/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "TSPComponentWriteChannel.h"



@class NSObject<OS_dispatch_queue>, TSUDispatchData;



__attribute__((visibility("hidden")))

@interface TSPMemoryComponentWriteChannel : NSObject <TSPComponentWriteChannel>

{

    NSObject<OS_dispatch_queue> *_streamQueue;

    TSUDispatchData *_streamData;

    _Bool _isClosed;

}



- (void).cxx_destruct;

- (void)close;

- (id)init;

- (id)serializedData;

- (void)writeData:(id)arg1;



@end


