/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "TSPObject.h"


__attribute__((visibility("hidden")))

@interface TSPPackageMetadata : TSPObject

{

    struct PackageMetadata _message;

}



- (id).cxx_construct;

- (void).cxx_destruct;

- (id)initFromUnarchiver:(id)arg1;

- (struct PackageMetadata *)message;

- (id)packageLocator;

- (void)saveToArchiver:(id)arg1;

- (long long)tsp_identifier;



@end


