/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "TSPArchiverManagerDelegate.h"

#import "TSPComponentWriterDelegate.h"

#import "TSPDataArchiver.h"

#import "TSPObjectModifyDelegate.h"

#import "TSPProxyObjectManager.h"



@class NSHashTable, NSMutableArray, NSObject<OS_dispatch_queue>, NSURL, TSPArchiverManager, TSPObjectContext;



__attribute__((visibility("hidden")))

@interface TSPPasteboardWriteCoordinator : NSObject <TSPArchiverManagerDelegate, TSPComponentWriterDelegate, TSPDataArchiver, TSPProxyObjectManager, TSPObjectModifyDelegate>

{

    TSPObjectContext *_context;

    id <TSPProxyObjectManager> _proxyManager;

    TSPArchiverManager *_archiverManager;

    NSObject<OS_dispatch_queue> *_delayedObjectsQueue;

    NSHashTable *_delayedObjects;

    NSMutableArray *_dataFinalizeHandlers;

}



- (void).cxx_destruct;

- (void)addDataFinalizeHandlerForSuccessfulSave:(id)arg1;

- (void)archiverManager:(id)arg1 didCreateArchiver:(id)arg2;

- (_Bool)archiverManager:(id)arg1 shouldDelayArchivingObject:(id)arg2;

- (void)componentWriter:(id)arg1 canSkipArchivingStronglyReferencedObject:(id)arg2 fromComponentRootObject:(id)arg3 completion:(id)arg4;

- (_Bool)componentWriter:(id)arg1 shouldDelayWritingObject:(id)arg2;

- (void)componentWriter:(id)arg1 wantsComponentOfObject:(id)arg2 queue:(id)arg3 completion:(id)arg4;

- (id)componentWriter:(id)arg1 wantsExplicitComponentRootObjectForObject:(id)arg2 claimingComponent:(id)arg3;

- (void)componentWriterWantsDelayedObjects:(id)arg1 queue:(id)arg2 completion:(id)arg3;

- (id)createPackageMetadataWithContext:(id)arg1 writingDatas:(id)arg2 toDictionary:(id)arg3;

- (void)dealloc;

- (void)delayArchivingOfObject:(id)arg1;

- (id)init;

- (id)initWithContext:(id)arg1;

- (id)proxyForReferencedObject:(id)arg1;

@property(nonatomic) __weak id <TSPProxyObjectManager> proxyManager; // @synthesize proxyManager=_proxyManager;

@property(readonly, nonatomic) NSURL *relativeURLForExternalData;

- (_Bool)shouldDelayArchivingObject:(id)arg1;

- (void)willModifyObject:(id)arg1 duringReadOperation:(_Bool)arg2;

- (void)writePasteboardObject:(id)arg1 completion:(id)arg2;



@end


