/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "TSPObject.h"


#import "TSTFormulaToken.h"



@class NSArray, NSString, TSCEFunctionArgumentSpec, TSDMultiPaneController, TSTWPTokenAttachment;



__attribute__((visibility("hidden")))

@interface TSTExpressionNode : TSPObject <TSTFormulaToken>

{

    NSArray *mChildren;

    TSCEFunctionArgumentSpec *mArgumentSpec;

    TSTWPTokenAttachment *mTokenAttachment;

    unsigned long long mFirstIndex;

    unsigned long long mLastIndex;

    NSString *mWhitespaceBefore;

    NSString *mWhitespaceAfter;

}



- (void)addTSTCanvasReferencesToSet:(id)arg1 inRangeContext:(int)arg2 withColorHelper:(id)arg3 preferringNodesFromStorage:(id)arg4 allVisitedNodes:(id)arg5;

@property(retain, nonatomic) TSCEFunctionArgumentSpec *argumentSpec;

- (void)buildASTNodeArray:(struct TSCEASTNodeArray *)arg1 hostCell:(CDStruct_0441cfb5)arg2;

@property(retain, nonatomic) NSArray *children;

- (long long)compareFirstLastIndices:(id)arg1;

- (id)copyByResolvingIdentifiers:(id)arg1 hostTable:(id)arg2 forceReferenceInterpretation:(_Bool)arg3;

- (id)copyIntoContext:(id)arg1 bakeModes:(_Bool)arg2 children:(id)arg3;

- (void)dealloc;

- (id)deepCopyIntoContext:(id)arg1 bakeModes:(_Bool)arg2 withTokenDict:(id)arg3;

- (id)description;

- (id)detokenizedText;

- (void)enumerateExpressionNodesUsingBlock:(id)arg1;

- (id)exportString;

@property(nonatomic) unsigned long long firstIndex; // @synthesize firstIndex=mFirstIndex;

- (_Bool)forceReferenceInterpretationOfChildren;

- (id)formulaPlainText;

- (_Bool)hasMenu;

- (id)initAsCopyOf:(id)arg1 intoContext:(id)arg2 children:(id)arg3;

- (id)initFromArchive:(const struct ExpressionNodeArchive *)arg1 unarchiver:(id)arg2;

- (id)initFromUnarchiver:(id)arg1;

- (id)initWithContext:(id)arg1;

- (id)initWithContext:(id)arg1 children:(id)arg2 firstIndex:(unsigned long long)arg3 lastIndex:(unsigned long long)arg4;

- (id)initWithContext:(id)arg1 firstIndex:(unsigned long long)arg2 lastIndex:(unsigned long long)arg3;

- (void)insertFormulaText:(id)arg1 includeWhitespace:(_Bool)arg2;

@property(nonatomic) unsigned long long lastIndex; // @synthesize lastIndex=mLastIndex;

@property(readonly, nonatomic) TSDMultiPaneController *popover;

- (void)saveToArchive:(struct ExpressionNodeArchive *)arg1 archiver:(id)arg2;

- (void)saveToArchiver:(id)arg1;

@property(nonatomic) TSTWPTokenAttachment *tokenAttachment; // @synthesize tokenAttachment=mTokenAttachment;

@property(retain, nonatomic) NSString *whitespaceAfter; // @synthesize whitespaceAfter=mWhitespaceAfter;

@property(retain, nonatomic) NSString *whitespaceBefore; // @synthesize whitespaceBefore=mWhitespaceBefore;



// Remaining properties

@property(readonly, nonatomic) NSString *string; // @dynamic string;

@property(readonly, nonatomic) int tokenType; // @dynamic tokenType;



@end


