/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "SFUInputStream.h"



@class NSObject<OS_dispatch_data>, NSObject<OS_dispatch_queue>;



__attribute__((visibility("hidden")))

@interface TSUReadChannelInputStreamAdapter : NSObject <SFUInputStream>

{

    id <TSUReadChannel> _readChannel;

    id <TSUStreamReadChannel> _streamReadChannel;

    NSObject<OS_dispatch_data> *_leftoverData;

    NSObject<OS_dispatch_queue> *_readQueue;

    long long _offset;

}



- (void).cxx_destruct;

- (id)_initWithReadChannel:(id)arg1 streamReadChannel:(id)arg2;

- (_Bool)canSeek;

- (void)close;

- (id)closeLocalStream;

- (void)dealloc;

- (void)disableSystemCaching;

- (void)enableSystemCaching;

- (id)initWithReadChannel:(id)arg1;

- (id)initWithStreamReadChannel:(id)arg1;

- (long long)offset;

- (unsigned long long)readToBuffer:(char *)arg1 size:(unsigned long long)arg2;

- (void)seekToOffset:(long long)arg1;



@end


