/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "TSUProgress.h"


@class NSObject<OS_dispatch_queue>, TSUScaledProgressStorage;



__attribute__((visibility("hidden")))

@interface TSUScaledProgress : TSUProgress

{

    TSUScaledProgressStorage *mStorage;

    TSUProgress *mProgress;

    id mProgressObserver;

    NSObject<OS_dispatch_queue> *mProgressQueue;

}



- (id)addProgressObserverWithValueInterval:(double)arg1 queue:(id)arg2 handler:(id)arg3;

- (void)dealloc;

- (id)init;

- (_Bool)isIndeterminate;

@property double maxValue;

- (void)p_addProgressObserverToProgressInQueue;

- (void)p_removeProgressObserverFromProgressInQueue;

@property(retain) TSUProgress *progress;

- (void)removeProgressObserver:(id)arg1;

- (double)value;



@end


