/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "TSWPNumberAttachment.h"


__attribute__((visibility("hidden")))

@interface TSWPPageCountAttachment : TSWPNumberAttachment

{

}



- (_Bool)changesWithPageCount;

- (int)elementKind;

- (void)saveToArchiver:(id)arg1;

- (_Bool)shouldArchiveStringEquivalent;

- (id)stringWithPageNumber:(unsigned long long)arg1 pageCount:(unsigned long long)arg2 charIndex:(unsigned long long)arg3;



@end


