/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "TSWPStyleProvider.h"



__attribute__((visibility("hidden")))

@interface TSWPStorageStyleProvider : NSObject <TSWPStyleProvider>

{

}



+ (id)styleProviderForStorage:(id)arg1;

- (id)paragraphStyleAtParIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;



// Remaining properties

@property(readonly, nonatomic) _Bool supportsBoldItalicUnderlineShortcuts;



@end


