/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "ABPredicate.h"


@interface ABAnyValuePredicate : ABPredicate

{

    int _property;

}



- (void)ab_bindStatement:(struct CPSqliteStatement *)arg1 withBindingOffset:(int *)arg2 predicateIdentifier:(int)arg3;

- (id)init;

- (_Bool)isValid;

@property(nonatomic) int property; // @synthesize property=_property;

- (id)queryGroupByProperties;

- (id)queryJoinsInCompound:(_Bool)arg1;

- (id)queryWhereString;



@end


