/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "ABVCardPersonValueSetter.h"


@interface ABVCardCardDAVValueSetter : ABVCardPersonValueSetter

{

    _Bool _recordIsGroup;

    _Bool _importingToExistingGroup;

}



+ (struct __CFDictionary *)_personToGroupPropertyMap;

+ (int)groupPropertyForPersonProperty:(int)arg1;

- (void)_drainExistingProperties;

- (void *)copyParsedRecordWithSource:(void *)arg1 outRecordType:(unsigned int *)arg2;

- (id)imageData;

- (id)initWithGroup:(void *)arg1 removeExistingProperties:(_Bool)arg2;

- (id)initWithPerson:(void *)arg1 removeExistingProperties:(_Bool)arg2;

- (_Bool)propertyIsValidForPerson:(unsigned int)arg1;

@property _Bool recordIsGroup; // @synthesize recordIsGroup=_recordIsGroup;

- (_Bool)setImageData:(id)arg1 cropRectX:(int)arg2 cropRectY:(int)arg3 cropRectWidth:(int)arg4 cropRectHeight:(int)arg5;

- (_Bool)setValue:(void *)arg1 forProperty:(unsigned int)arg2;

- (void *)valueForProperty:(unsigned int)arg1;



@end


