/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "NSCoding.h"



@class NSDate;



@interface MSBackoffManager : NSObject <NSCoding>

{

    id <MSBackoffManagerDelegate> _delegate;

    double _initialInterval;

    double _backoffFactor;

    double _randomizeFactor;

    double _maxBackoffInterval;

    double _currentInterval;

    NSDate *_nextExpiryDate;

    NSDate *_retryAfterDate;

}



- (void).cxx_destruct;

- (void)_complainAboutMissingKeyInArchive:(id)arg1;

- (void)backoff;

@property(nonatomic) double backoffFactor; // @synthesize backoffFactor=_backoffFactor;

- (id)copyParameters;

@property(nonatomic) double currentInterval; // @synthesize currentInterval=_currentInterval;

@property(nonatomic) id <MSBackoffManagerDelegate> delegate; // @synthesize delegate=_delegate;

- (void)didReceiveRetryAfterDate:(id)arg1;

- (void)encodeWithCoder:(id)arg1;

- (id)initWithCoder:(id)arg1;

- (id)initWithInitialInterval:(double)arg1 backoffFactor:(double)arg2 randomizeFactor:(double)arg3 maxBackoffInterval:(double)arg4 retryAfterDate:(id)arg5;

@property(nonatomic) double initialInterval; // @synthesize initialInterval=_initialInterval;

@property(nonatomic) double maxBackoffInterval; // @synthesize maxBackoffInterval=_maxBackoffInterval;

@property(retain, nonatomic) NSDate *nextExpiryDate; // @synthesize nextExpiryDate=_nextExpiryDate;

@property(nonatomic) double randomizeFactor; // @synthesize randomizeFactor=_randomizeFactor;

- (void)reset;

@property(retain, nonatomic) NSDate *retryAfterDate; // @synthesize retryAfterDate=_retryAfterDate;



@end


