/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "MSStreamsProtocolDelegate.h"



@protocol MSDeleteStreamsProtocolDelegate <MSStreamsProtocolDelegate>

- (void)deleteProtocol:(id)arg1 didFinishSuccessfulCollections:(id)arg2 failedCollections:(id)arg3 error:(id)arg4;

- (void)deleteProtocol:(id)arg1 didReceiveAuthenticationError:(id)arg2;

@end


