/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "CKCardMediaObject.h"


@class ABVCardRecord, UIImage;



@interface CKContactMediaObject : CKCardMediaObject

{

    ABVCardRecord *_vCard;

    UIImage *_vCardImage;

}



+ (id)UTITypes;

+ (id)fallbackFilenamePrefix;

- (Class)balloonViewClass;

- (struct CGSize)bbSize;

- (void)dealloc;

- (id)generateThumbnailFillToSize:(struct CGSize)arg1;

- (id)icon;

- (int)mediaType;

@property(retain, nonatomic) ABVCardRecord *vCard; // @synthesize vCard=_vCard;

@property(retain, nonatomic) UIImage *vCardImage; // @synthesize vCardImage=_vCardImage;

- (id)subtitle;

- (id)title;

- (id)vCardImageOfSize:(struct CGSize)arg1;



@end


