/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIView.h"



@class UIButton;



@interface CKTranscriptToolbarView : UIView

{

    UIButton *_editButton;

    UIButton *_contactButton;

    UIButton *_cancelButton;

    _Bool _hasContact;

    _Bool _isGroupMessage;

    _Bool _cancelButtonVisible;

    id <CKTranscriptHeaderViewDelegate> _delegate;

}



- (void)_buttonClicked:(id)arg1;

- (void)dealloc;

@property(nonatomic) id <CKTranscriptHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;

- (struct CGRect)frameForButton:(short)arg1;

@property(nonatomic) _Bool hasContact; // @synthesize hasContact=_hasContact;

- (id)initAsGroupMessage:(_Bool)arg1 hasMessages:(_Bool)arg2;

@property(nonatomic, getter=isCancelButtonVisible) _Bool cancelButtonVisible; // @synthesize cancelButtonVisible=_cancelButtonVisible;

@property(nonatomic) _Bool isGroupMessage; // @synthesize isGroupMessage=_isGroupMessage;

- (void)layoutSubviews;

- (void)sizeToFit;



@end


