/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "GKSimpleTimerDelegate.h"



@class GKDiscoveryPeerConnection, GKSimpleTimer, NSMutableArray, NSMutableSet, NSNumber, NSObject<OS_dispatch_queue>, NSString;



__attribute__((visibility("hidden")))

@interface GKDiscoveryPeer : NSObject <GKSimpleTimerDelegate>

{

    NSString *_serviceName;

    NSString *_playerID;

    NSString *_deviceID;

    NSMutableSet *_interfaces;

    NSMutableArray *_orderedInterfaces;

    NSMutableArray *_attemptedInterfaces;

    GKDiscoveryPeerConnection *_trialConnection;

    NSNumber *_chosenInterface;

    _Bool _shouldSignalDiscovery;

    NSMutableArray *_sendDataBuffer;

    GKDiscoveryPeerConnection *_connection;

    GKSimpleTimer *_resolveTimer;

    id _resolveTimeoutHandler;

    NSObject<OS_dispatch_queue> *_syncQueue;

    int _state;

    double _discoveryTimeStamp;

}



@property(retain, nonatomic) NSMutableArray *attemptedInterfaces; // @synthesize attemptedInterfaces=_attemptedInterfaces;

@property(retain, nonatomic) NSNumber *chosenInterface; // @synthesize chosenInterface=_chosenInterface;

- (void)cleanUpForBrowse;

@property(retain, nonatomic) GKDiscoveryPeerConnection *connection; // @synthesize connection=_connection;

- (void)dealloc;

- (id)description;

@property(copy, nonatomic) NSString *deviceID; // @synthesize deviceID=_deviceID;

- (void)didLoseInterface:(id)arg1;

@property(nonatomic) double discoveryTimeStamp; // @synthesize discoveryTimeStamp=_discoveryTimeStamp;

- (void)flushDataBuffer;

- (id)initWithServiceName:(id)arg1;

@property(retain, nonatomic) NSMutableSet *interfaces; // @synthesize interfaces=_interfaces;

- (void)invalidate;

- (id)nextInterfaceIndex;

@property(retain, nonatomic) NSMutableArray *orderedInterfaces; // @synthesize orderedInterfaces=_orderedInterfaces;

- (_Bool)parseServiceNameForInit:(id)arg1;

@property(copy, nonatomic) NSString *playerID; // @synthesize playerID=_playerID;

@property(copy, nonatomic) id resolveTimeoutHandler; // @synthesize resolveTimeoutHandler=_resolveTimeoutHandler;

@property(retain, nonatomic) GKSimpleTimer *resolveTimer; // @synthesize resolveTimer=_resolveTimer;

- (void)sendData:(id)arg1 withCompletionHandler:(id)arg2;

@property(retain, nonatomic) NSMutableArray *sendDataBuffer; // @synthesize sendDataBuffer=_sendDataBuffer;

@property(copy, nonatomic) NSString *serviceName; // @synthesize serviceName=_serviceName;

@property(nonatomic) _Bool shouldSignalDiscovery; // @synthesize shouldSignalDiscovery=_shouldSignalDiscovery;

@property(nonatomic) int state; // @synthesize state=_state;

@property(retain, nonatomic) GKDiscoveryPeerConnection *trialConnection; // @synthesize trialConnection=_trialConnection;

- (void)startResolveTimerWithHandler:(id)arg1;

- (void)stopResolveTimer;

- (id)stringForState:(int)arg1;

@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *syncQueue; // @synthesize syncQueue=_syncQueue;

- (void)timeout:(id)arg1;



@end


