/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "NSSecureCoding.h"



@class NSString;



@interface AOSLostModeInfo : NSObject <NSSecureCoding>

{

    _Bool _lostModeEnabled;

    NSString *_message;

    NSString *_phoneNumber;

}



+ (_Bool)supportsSecureCoding;

- (void)dealloc;

- (id)description;

- (void)encodeWithCoder:(id)arg1;

- (id)initWithCoder:(id)arg1;

@property(nonatomic) _Bool lostModeEnabled; // @synthesize lostModeEnabled=_lostModeEnabled;

@property(retain, nonatomic) NSString *message; // @synthesize message=_message;

@property(retain, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;



@end


