/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class CPDistributedNotificationCenter, NSXPCConnection;



@interface AOSNotifySession : NSObject

{

    NSXPCConnection *_xpcConnection;

    CPDistributedNotificationCenter *_center;

    id <AOSNotifySessionDelegate> _delegate;

}



+ (id)copyStoreAccount;

+ (id)sharedInstance;

- (void)_destroyXPCConnection;

- (void)_stopVettingNotifications;

- (void)_vetFinished:(id)arg1;

- (void)_vetResultReceived:(id)arg1;

- (void)activationLockStateWithCompletion:(id)arg1;

- (id)addFMFAccount:(id)arg1;

- (id)cancelEmailVet;

@property(retain, nonatomic) CPDistributedNotificationCenter *center; // @synthesize center=_center;

- (id)currentXPCConnection;

- (void)dealloc;

@property(nonatomic) id <AOSNotifySessionDelegate> delegate; // @synthesize delegate=_delegate;

- (void)deviceActivationDidSucceed;

- (void)didEnterFMFRegion:(id)arg1 atLocation:(id)arg2;

- (void)didExitFMFRegion:(id)arg1 atLocation:(id)arg2;

- (id)disableActivationLockUsingToken:(id)arg1;

- (id)disableFMIPUsingToken:(id)arg1 inContext:(int)arg2;

- (void)disableLostMode;

- (void)dumpDebugInfo:(id)arg1;

- (id)enableActivationLock;

- (id)enableFMIPInContext:(int)arg1;

- (id)enableLostModeWithInfo:(id)arg1;

- (id)fmfDeviceId;

- (id)fmipAccount;

- (id)fmipDeviceId;

- (void)fmipStateWithCompletion:(id)arg1;

- (id)iCloudAccount;

- (id)init;

- (id)initWithDelegate:(id)arg1;

- (void)isActivationLockStateChangeInProgressWithCompletion:(id)arg1;

- (void)isFMIPStateChangeInProgressWithCompletion:(id)arg1;

- (_Bool)lockdownShouldDisableDevicePairing;

- (_Bool)lockdownShouldDisableDeviceRestore;

- (id)lostModeInfo;

- (_Bool)lostModeIsActive;

- (id)lostModeParams;

- (id)newErrorForCode:(int)arg1 message:(id)arg2;

- (id)removeFMFAccountWithUsername:(id)arg1;

- (id)retrieveAllAccounts:(id *)arg1;

- (id)retrieveFMFAccount:(id *)arg1;

@property(retain, nonatomic) NSXPCConnection *xpcConnection; // @synthesize xpcConnection=_xpcConnection;

- (void)startListeningOnTopic:(id)arg1;

- (void)stopListeningOnTopic:(id)arg1;

- (id)storeAccount;

- (id)vetEmailAccount:(id)arg1;



@end


