/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "CalDAVCalendarServerResourceChangeElement.h"


@interface CalDAVCalendarServerCollectionUpdatesElement : CalDAVCalendarServerResourceChangeElement

{

    int _state;

}



- (id)copyParseRules;

- (void)setPublish:(id)arg1;

- (void)setUnpublish:(id)arg1;

@property(readonly) int state; // @synthesize state=_state;



@end


