/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "CoreDAVTaskGroup.h"



#import "CoreDAVPostTaskDelegate.h"



@class NSMutableSet, NSSet, NSString, NSURL;



@interface CalDAVModifySharedCalendarShareeListTaskGroup : CoreDAVTaskGroup <CoreDAVPostTaskDelegate>

{

    NSSet *_shareesToRemove;

    NSSet *_shareesToSet;

    NSURL *_calendarURL;

    NSString *_summary;

    NSMutableSet *_invalidSharees;

}



@property(retain) NSURL *calendarURL; // @synthesize calendarURL=_calendarURL;

- (void)dealloc;

- (id)description;

- (id)generateModificationMessageBody;

- (id)initWithAccountInfoProvider:(id)arg1 taskManager:(id)arg2;

- (id)initWithShareesToSet:(id)arg1 shareesToRemove:(id)arg2 summary:(id)arg3 atCalendarURL:(id)arg4 accountInfoProvider:(id)arg5 taskManager:(id)arg6;

@property(retain) NSMutableSet *invalidSharees; // @synthesize invalidSharees=_invalidSharees;

@property(retain) NSSet *shareesToRemove; // @synthesize shareesToRemove=_shareesToRemove;

@property(retain) NSSet *shareesToSet; // @synthesize shareesToSet=_shareesToSet;

@property(retain) NSString *summary; // @synthesize summary=_summary;

- (void)startTaskGroup;

- (void)task:(id)arg1 didFinishWithError:(id)arg2;



// Remaining properties

@property(nonatomic) id <CoreDAVTaskGroupDelegate> delegate; // @dynamic delegate;



@end


