/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class MPAVController, MPMusicPlayerControllerServerInternal;



@interface MPMusicPlayerControllerServer : NSObject

{

    MPMusicPlayerControllerServerInternal *_internal;

}



+ (_Bool)isMusicPlayerControllerServerRunning;

+ (id)sharedInstance;

+ (void)startMusicPlayerControllerServerWithDelegate:(id)arg1;

- (void).cxx_destruct;

- (void)_runMigServer;

- (void)forwardInvocation:(id)arg1;

- (id)init;

- (id)methodSignatureForSelector:(SEL)arg1;

@property(readonly, nonatomic) MPAVController *player;

- (void)setDelegate:(id)arg1;



@end


