/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "_UIReflectingView.h"



@class UIImage, UIImageView;



@interface MPReflectionImageView : _UIReflectingView

{

    UIImageView *_imageView;

    _Bool _squareImage;

}



+ (double)defaultReflectionHeight;

- (void).cxx_destruct;

- (id)albumArtImage;

@property(retain, nonatomic) UIImage *image;

@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;

- (id)initWithFrame:(struct CGRect)arg1;

- (void)setAlbumVisible:(_Bool)arg1 reflectionVisible:(_Bool)arg2;

- (void)setFrame:(struct CGRect)arg1 withReflectionHeight:(double)arg2;

- (void)setReflectionVisible:(_Bool)arg1 withDuration:(float)arg2;

@property(nonatomic) _Bool squareImage; // @synthesize squareImage=_squareImage;



@end


