/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "MPViewController.h"


#import "MPSwipableViewDelegate.h"

#import "MPVideoControllerProtocol.h"

#import "UIModalViewDelegate.h"



@class MPAVController, MPAVItem, MPClosedCaptionDisplay, MPImageCache, MPImageCacheRequest, MPSwipableView, MPTVOutWindow, MPVideoBackgroundView, MPVideoView, UIActivityIndicatorView, UIAlertView, UIColor, UIImage, UIView, UIView<MPVideoOverlay>, _UIHostedWindow;



@interface MPVideoViewController : MPViewController <MPVideoControllerProtocol, MPSwipableViewDelegate, UIModalViewDelegate>

{

    MPVideoBackgroundView *_backgroundView;

    MPSwipableView *_backstopView;

    _Bool _batteryMonitoringWasEnabled;

    MPClosedCaptionDisplay *_captionView;

    unsigned long long _desiredParts;

    unsigned long long _disabledParts;

    unsigned long long _visibleParts;

    unsigned int _tvOutEnabled:1;

    unsigned int _allowsTVOutInBackground:1;

    unsigned long long _itemTypeOverride;

    unsigned long long _scaleMode;

    unsigned long long _scaleModeOverride;

    UIAlertView *_alertSheet;

    MPImageCache *_artworkImageCache;

    MPImageCacheRequest *_artworkImageRequest;

    UIColor *_backstopColor;

    UIActivityIndicatorView *_loadingIndicator;

    MPTVOutWindow *_tvOutWindow;

    unsigned long long _backgroundTaskId;

    int _artworkImageStyle;

    UIImage *_posterImage;

    unsigned int _canAnimateControlsOverlay:1;

    unsigned int _canShowControlsOverlay:1;

    unsigned int _disableControlsAutohide:1;

    unsigned int _playAfterPop:1;

    unsigned int _scheduledLoadingIndicator:1;

    unsigned int _displayPlaybackErrorAlerts:1;

    unsigned int _allowsDetailScrubbing:1;

    unsigned int _attemptAutoPlayWhenControlsHidden:1;

    unsigned int _alwaysAllowHidingControlsOverlay:1;

    unsigned int _hasShownFirstVideoFrame:1;

    unsigned int _allowsWirelessPlayback:1;

    unsigned int _disableAutoRotation:1;

    unsigned int _inlinePlaybackUsesTVOut:1;

}



+ (long long)_activityIndicatorViewStyle;

+ (struct CGRect)calculateArtworkImageViewFrameInRect:(struct CGRect)arg1;

+ (_Bool)supportsFullscreenDisplay;

- (void).cxx_destruct;

@property(nonatomic) _Bool TVOutEnabled;

- (_Bool)_canEnableAirPlayVideoRoutes;

- (void)_cancelArtworkImageRequest;

- (void)_delayedPopForTimeJump;

- (void)_delayedShowLoading;

- (void)_delayedUpdateBackgroundView;

- (void)_endBackgroundTask;

- (void)_exitPlayerForPlaybackError;

- (void)_fixupViewHierarchyIfNecessary;

- (void)_hideLoadingIndicator;

- (void)_itemDurationDidChange:(id)arg1;

- (unsigned long long)_itemTypeWithActualTypePreference;

- (void)_popForTimeJump:(id)arg1;

- (void)_scheduleLoadingIndicatorIfNeeded;

- (void)_screenDidConnect:(id)arg1;

- (void)_screenDidDisconnect:(id)arg1;

- (_Bool)_showDestinationPlaceholder;

- (void)_showStillFrameIfNotAlreadyPlaying;

- (void)_updateAlwaysPlayWheneverPossible;

- (void)_updateBackgroundView:(_Bool)arg1;

- (void)_updateClosedCaptionDisplay;

- (void)_updateIdleTimerDisabledFromPlaybackState:(unsigned long long)arg1;

- (void)_updateProgressControlForItem:(id)arg1;

- (void)_videoView_applicationSuspendedNotification:(id)arg1;

- (void)_videoView_applicationWillEnterForegroundNotification:(id)arg1;

- (void)_videoView_availableRoutesDidChangeNotification:(id)arg1;

- (void)_videoView_batteryStateDidChangeNotification:(id)arg1;

- (void)_videoView_effectiveScaleModeChangedNotification:(id)arg1;

- (void)_videoView_isExternalPlaybackActiveDidChangeNotification:(id)arg1;

- (void)_videoView_playbackErrorNotification:(id)arg1;

- (void)_videoView_resumeEventsOnlyNotification:(id)arg1;

- (void)_videoView_scaleModeChangedNotification:(id)arg1;

- (void)_videoView_sizeChangedNotification:(id)arg1;

- (void)_videoView_timedImageMetadataAvailableNotification:(id)arg1;

- (void)_videoView_validityChangedNotification:(id)arg1;

- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;

@property(nonatomic) _Bool allowsDetailScrubbing;

@property(nonatomic) _Bool allowsTVOutInBackground;

@property(nonatomic) _Bool allowsWirelessPlayback;

@property(nonatomic) _Bool alwaysAllowHidingControlsOverlay;

@property(nonatomic) int artworkImageStyle; // @synthesize artworkImageStyle=_artworkImageStyle;

@property(readonly, nonatomic) UIView *artworkImageView;

@property(nonatomic) _Bool attemptAutoPlayWhenControlsHidden;

@property(nonatomic) _Bool autoPlayWhenLikelyToKeepUp;

@property(readonly, nonatomic) UIView *backgroundView;

- (void)backgroundViewDidUpdate;

@property(retain, nonatomic) UIColor *backstopColor; // @synthesize backstopColor=_backstopColor;

- (struct CGRect)calculateArtworkImageViewFrame;

- (struct CGRect)calculateFullScreenArtworkImageViewFrame;

@property(nonatomic) _Bool canAnimateControlsOverlay;

@property(readonly, nonatomic) _Bool canChangeScaleMode;

- (_Bool)canHideOverlay:(_Bool)arg1;

@property(nonatomic) _Bool canShowControlsOverlay;

@property(readonly, nonatomic) _Bool canShowQTAudioOnlyUI;

- (void)chapterList:(id)arg1 selectedChapter:(unsigned long long)arg2;

- (void)chapterListDidDisappear:(id)arg1;

@property(nonatomic) _Bool controlsOverlayVisible;

- (id)createChapterFlipTransition;

- (void)crossedTimeMakerWithEvent:(id)arg1;

- (void)dealloc;

@property(nonatomic) unsigned long long desiredParts; // @synthesize desiredParts=_desiredParts;

@property(nonatomic) _Bool disableAutoRotation;

@property(nonatomic) _Bool disableControlsAutohide;

@property(nonatomic) unsigned long long disabledParts; // @synthesize disabledParts=_disabledParts;

- (unsigned long long)disabledPartsForProposedParts:(unsigned long long)arg1;

- (int)displayArtworkImageStyle;

@property(nonatomic) _Bool displayPlaybackErrorAlerts;

- (void)displayVideoView;

- (void)displayVideoViewOnScreen;

- (void)displayVideoViewOnTV;

- (void)enableAirPlayVideoRoutesIfNecessary;

- (void)exitFullscreen;

- (void)handleScaleModeChange;

@property(readonly, nonatomic) _UIHostedWindow *hostedWindow;

@property(readonly, nonatomic) unsigned int hostedWindowContextID;

- (id)init;

@property(nonatomic) _Bool inlinePlaybackUsesTVOut;

@property(nonatomic, getter=isFullscreen) _Bool fullscreen;

- (_Bool)isFullscreenForLayoutPurposes;

@property(readonly, nonatomic, getter=isTransitioningFromFullscreen) _Bool transitioningFromFullscreen;

@property(readonly, nonatomic, getter=isTransitioningToFullscreen) _Bool transitioningToFullscreen;

@property(nonatomic) unsigned long long itemTypeOverride; // @synthesize itemTypeOverride=_itemTypeOverride;

- (void)loadView;

- (id)newAlternateTracksTransition;

- (id)newArtworkImageView;

- (void)noteIgnoredChangeTypes:(unsigned long long)arg1;

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

@property(retain, nonatomic) UIImage *posterImage; // @synthesize posterImage=_posterImage;

- (void)prepareToDisplayVideo;

- (void)registerForPlayerNotifications;

- (void)reloadArtworkImageView;

- (void)removeChildViewController:(id)arg1;

@property(nonatomic) unsigned long long scaleMode; // @synthesize scaleMode=_scaleMode;

- (void)setClosedCaptions:(id)arg1;

- (void)setControlsNeedLayout;

- (void)setControlsOverlayVisible:(_Bool)arg1 animate:(_Bool)arg2;

- (void)setControlsOverlayVisible:(_Bool)arg1 animate:(_Bool)arg2 force:(_Bool)arg3;

- (void)setDesiredParts:(unsigned long long)arg1 animate:(_Bool)arg2;

- (void)setFullscreen:(_Bool)arg1 animated:(_Bool)arg2;

@property(retain, nonatomic) MPAVItem *item;

- (void)setOrientation:(long long)arg1 animate:(_Bool)arg2;

- (void)setOwnsStatusBar:(_Bool)arg1;

@property(retain, nonatomic) MPAVController *player;

- (void)setScaleMode:(unsigned long long)arg1 animated:(_Bool)arg2;

- (void)setScaleModeOverride:(unsigned long long)arg1 animated:(_Bool)arg2;

- (void)setUseHostedWindowWhenFullscreen:(_Bool)arg1;

@property(nonatomic) unsigned long long visibleParts; // @synthesize visibleParts=_visibleParts;

- (void)setVisibleParts:(unsigned long long)arg1 animate:(_Bool)arg2;

- (void)showAlternateTracksController:(id)arg1;

@property(readonly, nonatomic) _Bool showArtworkForTVOut;

@property(readonly, nonatomic) _Bool showArtworkInImageView;

- (void)showChaptersController;

- (void)showChaptersControllerAndFadeViews:(id)arg1;

- (void)tearDownTVOutWindow;

- (void)toggleScaleMode:(_Bool)arg1;

- (void)unregisterForPlayerNotifications;

@property(readonly, nonatomic) UIView<MPVideoOverlay> *videoOverlayView;

@property(readonly, nonatomic) UIView<MPVideoOverlay> *videoOverlayViewIfLoaded;

@property(readonly, nonatomic) MPVideoView *videoView;

- (void)videoView_bufferingStateChangedNotification:(id)arg1;

- (void)videoView_firstVideoFrameDisplayedNotification:(id)arg1;

- (void)videoView_itemTypeAvailableNotification:(id)arg1;

- (void)videoView_playbackStateChangedNotification:(id)arg1;

- (void)videoView_tvOutCapabilityDidChangeNotification:(id)arg1;

@property(readonly, nonatomic) _Bool viewControllerWillRequestExit;

- (void)viewDidAppear:(_Bool)arg1;

- (void)viewWillDisappear:(_Bool)arg1;

- (unsigned long long)visiblePartsForProposedParts:(unsigned long long)arg1;

- (void)willChangeToInterfaceOrientation:(long long)arg1;



// Remaining properties

@property(nonatomic) __weak id delegate;

@property(nonatomic) long long orientation;

@property(readonly, nonatomic) UIView *view;



@end


