/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIView.h"



@class UIImageView, UITableView;



@interface UIMovieChapterListView : UIView

{

    UIImageView *_backgroundImageView;

    unsigned long long _pinnedRow;

    UITableView *_tableView;

    double _topPadding;

}



- (void).cxx_destruct;

- (id)init;

- (void)layoutSubviews;

- (void)pinVisibleRow:(unsigned long long)arg1;

@property(nonatomic) double topPadding; // @synthesize topPadding=_topPadding;

@property(readonly, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;



@end


