/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "NSMutableAttributedString.h"



@interface NSMutableAttributedString (DataDetectorsSupport)

- (void)dd_makeLinksForResultsInAttributesOfType:(unsigned long long)arg1 context:(id)arg2;

- (void)dd_resetResults;

- (void)dd_urlifyResult:(id)arg1 withBlock:(id)arg2 referenceDate:(void)arg3;

@end


