/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "SBUIPasscodeLockViewBase.h"


#import "SBUIPasscodeEntryFieldDelegate.h"

#import "SBUIPasscodeLockNumberPadDelegate.h"



@class NSString, SBUIPasscodeLockNumberPad, UILabel, UIView;



@interface SBUIPasscodeLockViewWithKeypad : SBUIPasscodeLockViewBase <SBUIPasscodeLockNumberPadDelegate, SBUIPasscodeEntryFieldDelegate>

{

    UILabel *_statusTitleView;

    UIView *_statusBackgroundView;

    SBUIPasscodeLockNumberPad *_numberPad;

    UIView *_topToStatusFieldOrEntryFieldFiller;

    UIView *_entryFieldToNumberPadFiller;

    UIView *_leftToNumberPadFiller;

    UIView *_rightToNumberPadFiller;

    UIView *_bottomToNumberPadFiller;

    NSString *_lastCharacterBeforeBackspace;

    _Bool _undoInputOnTouchCancellation;

}



- (double)_entryFieldBottomYDistanceFromNumberPadTopButton;

- (_Bool)_includesStatusView;

- (void)_layoutStatusView;

- (void)_layoutStatusView:(id)arg1;

- (void)_luminanceBoostDidChange;

- (id)_newEntryField;

- (id)_newStatusTitleView;

- (void)_noteBackspaceHit;

- (void)_noteKeyUp:(id)arg1;

- (void)_noteStringEntered:(id)arg1 eligibleForPlayingSounds:(_Bool)arg2;

- (void)_notifyDelegatePasscodeCancelled;

- (void)_notifyDelegatePasscodeEntered;

- (id)_numberPad;

- (double)_numberPadOffsetFromTopOfScreen;

- (id)_numericEntryFieldIfExists;

- (void)_setHasInput:(_Bool)arg1;

@property(nonatomic, getter=_undoInputOnTouchCancellation, setter=_setUndoInputOnTouchCancellation:) _Bool undoInputOnTouchCancellation; // @synthesize undoInputOnTouchCancellation=_undoInputOnTouchCancellation;

- (id)_statusBackgroundView;

- (id)_statusTitleView;

- (double)_statusTitleViewHeight;

- (id)_statusTitleViewTitleFont;

- (double)_statusTitleWidth;

- (void)_toggleForStatusField;

- (void)_updateStatusText:(id)arg1 animated:(_Bool)arg2;

- (double)backgroundAlpha;

- (void)dealloc;

- (id)init;

@property(retain, nonatomic) NSString *lastCharacterBeforeBackspace; // @synthesize lastCharacterBeforeBackspace=_lastCharacterBeforeBackspace;

- (void)layoutSubviews;

- (id)passcode;

- (_Bool)passcodeEntryField:(id)arg1 shouldInsertText:(id)arg2;

- (void)passcodeEntryFieldDidAcceptEntry:(id)arg1;

- (void)passcodeEntryFieldDidCancelEntry:(id)arg1;

- (void)passcodeEntryFieldTextDidChange:(id)arg1;

- (void)passcodeLockNumberPad:(id)arg1 keyCancelled:(id)arg2;

- (void)passcodeLockNumberPad:(id)arg1 keyDown:(id)arg2;

- (void)passcodeLockNumberPad:(id)arg1 keyUp:(id)arg2;

- (void)passcodeLockNumberPadBackspaceButtonHit:(id)arg1;

- (void)passcodeLockNumberPadCancelButtonHit:(id)arg1;

- (void)passcodeLockNumberPadEmergencyCallButtonHit:(id)arg1;

- (void)reset;

- (void)resetForFailedPasscode;

- (void)setBackgroundAlpha:(double)arg1;

- (void)setCustomBackgroundColor:(id)arg1;

- (void)setShowsEmergencyCallButton:(_Bool)arg1;

- (void)setShowsStatusField:(_Bool)arg1;

@property(retain, nonatomic) UILabel *statusTitleView; // @synthesize statusTitleView=_statusTitleView;



@end


