/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "NSSecureCoding.h"



@class TIUserDictionaryEntryValue;



@interface TIUserDictionaryTransaction : NSObject <NSSecureCoding>

{

    TIUserDictionaryEntryValue *_valueToDelete;

    TIUserDictionaryEntryValue *_valueToInsert;

}



+ (_Bool)supportsSecureCoding;

- (void)dealloc;

- (id)description;

- (void)encodeWithCoder:(id)arg1;

- (id)initWithCoder:(id)arg1;

@property(retain, nonatomic) TIUserDictionaryEntryValue *valueToDelete; // @synthesize valueToDelete=_valueToDelete;

@property(retain, nonatomic) TIUserDictionaryEntryValue *valueToInsert; // @synthesize valueToInsert=_valueToInsert;



@end


