/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UINavigationController.h"



#import "PSController.h"

#import "UINavigationControllerDelegate.h"



@class NSMutableSet, PSSpecifier;



@interface PSRootController : UINavigationController <PSController, UINavigationControllerDelegate>

{

    PSSpecifier *_specifier;

    NSMutableSet *_tasks;

    _Bool _deallocating;

    unsigned char _hasTelephony;

}



+ (id)domainForSpecifier:(id)arg1;

+ (_Bool)processedBundle:(id)arg1 parentController:(id)arg2 parentSpecifier:(id)arg3 bundleControllers:(id *)arg4 settings:(id)arg5;

+ (id)readPreferenceValue:(id)arg1;

+ (void)setPreferenceValue:(id)arg1 specifier:(id)arg2;

+ (void)writePreference:(id)arg1;

- (void)_delayedControllerReleaseAfterPop:(id)arg1;

- (void)addTask:(id)arg1;

- (id)aggregateDictionaryPath;

- (_Bool)busy;

- (_Bool)canBeShownFromSuspendedState;

- (id)contentViewForTopController;

- (void)dealloc;

- (_Bool)deallocating;

- (void)didDismissFormSheetView;

- (void)didDismissPopupView;

- (void)didLock;

- (void)didUnlock;

- (void)didWake;

- (void)handleURL:(id)arg1;

- (id)initWithTitle:(id)arg1 identifier:(id)arg2;

- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;

- (id)parentController;

- (id)popToRootViewControllerAnimated:(_Bool)arg1;

- (id)popToViewController:(id)arg1 animated:(_Bool)arg2;

- (id)popViewControllerAnimated:(_Bool)arg1;

- (void)pushController:(id)arg1;

- (id)readPreferenceValue:(id)arg1;

- (id)rootController;

- (void)sendWillBecomeActive;

- (void)sendWillResignActive;

- (void)setParentController:(id)arg1;

- (void)setPreferenceValue:(id)arg1 specifier:(id)arg2;

- (void)setRootController:(id)arg1;

- (void)setSpecifier:(id)arg1;

- (void)setViewControllers:(id)arg1 animated:(_Bool)arg2;

- (void)showLeftButton:(id)arg1 withStyle:(long long)arg2 rightButton:(id)arg3 withStyle:(long long)arg4;

- (id)specifier;

- (id)specifiers;

- (void)statusBarWillAnimateByHeight:(double)arg1;

- (void)statusBarWillChangeHeight:(id)arg1;

- (unsigned long long)supportedInterfaceOrientations;

- (void)suspend;

- (void)taskFinished:(id)arg1;

- (_Bool)taskIsRunning:(id)arg1;

- (id)tasksDescription;

- (void)willBecomeActive;

- (void)willDismissFormSheetView;

- (void)willDismissPopupView;

- (void)willResignActive;

- (void)willUnlock;



@end


