/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "PSEditableListController.h"


@interface PSUsageBundleDetailController : PSEditableListController

{

}



+ (id)mediaGroups;

+ (void)setupSpecifier:(id)arg1 forMediaGroups:(id)arg2;

- (_Bool)canBeShownFromSuspendedState;

- (void)dealloc;

- (void)loadView;

- (_Bool)needsToShowToolbarInPrefsAppRoot;

- (id)size:(id)arg1;

- (id)sizeForSpecifier:(id)arg1;

- (id)specifiers;

- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;

- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;

- (_Bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;

- (void)updateSizesAfterDeletingSize:(float)arg1 shouldPop:(_Bool)arg2;



@end


