/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "NSArray.h"



__attribute__((visibility("hidden")))

@interface _PFArray : NSArray

{

    int _cd_rc;

    unsigned int _count;

    id *_array;

    struct _PFArrayFlags _flags;

}



+ (_Bool)accessInstanceVariablesDirectly;

+ (void)initialize;

- (unsigned int)_flags;

- (_Bool)_isDeallocating;

- (id *)_objectsPointer;

- (void)_setShouldRelease:(_Bool)arg1;

- (void)_setShouldUseExtendedRelease:(_Bool)arg1;

- (_Bool)_tryRetain;

- (id)arrayFromObjectIDs;

- (id)copyWithZone:(struct _NSZone *)arg1;

- (unsigned long long)count;

- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;

- (void)dealloc;

- (void)getObjects:(id *)arg1;

- (void)getObjects:(id *)arg1 range:(struct _NSRange)arg2;

- (unsigned long long)indexOfManagedObjectForObjectID:(id)arg1;

- (unsigned long long)indexOfObject:(id)arg1;

- (unsigned long long)indexOfObject:(id)arg1 inRange:(struct _NSRange)arg2;

- (unsigned long long)indexOfObjectIdenticalTo:(id)arg1;

- (unsigned long long)indexOfObjectIdenticalTo:(id)arg1 inRange:(struct _NSRange)arg2;

- (id)initWithObjects:(const id *)arg1 count:(unsigned long long)arg2;

- (id)initWithObjects:(id *)arg1 count:(unsigned int)arg2 andFlags:(unsigned int)arg3;

- (id)managedObjectIDAtIndex:(unsigned long long)arg1;

- (id)mutableCopyWithZone:(struct _NSZone *)arg1;

- (id)newArrayFromObjectIDs;

- (id)objectAtIndex:(unsigned long long)arg1;

- (oneway void)release;

- (id)retain;

- (unsigned long long)retainCount;

- (id)subarrayWithRange:(struct _NSRange)arg1;



@end


