/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSManagedObjectContext, NSString, PFUbiquityLocation, PFUbiquityMetadataFactoryEntry;



__attribute__((visibility("hidden")))

@interface _PFUbiquityStack : NSObject

{

    NSManagedObjectContext *_metadataMOC;

    PFUbiquityMetadataFactoryEntry *_metadataEntry;

    NSString *_localPeerID;

    PFUbiquityLocation *_ubiquityRootURL;

    NSString *_storeName;

    PFUbiquityLocation *_metadataStoreFileLocation;

}



- (id)allPeers;

- (id)createMetadataStoreKnowledgeVector:(id *)arg1;

- (id)createMinMetadataStoreKnowledgeVector:(id *)arg1;

- (void)dealloc;

- (id)description;

- (id)init;

- (id)initWithMetadataEntry:(id)arg1;

@property(readonly, nonatomic) NSString *localPeerID; // @synthesize localPeerID=_localPeerID;

@property(readonly, nonatomic) PFUbiquityMetadataFactoryEntry *metadataEntry; // @synthesize metadataEntry=_metadataEntry;

@property(readonly, nonatomic) NSManagedObjectContext *metadataMOC; // @synthesize metadataMOC=_metadataMOC;

@property(readonly, nonatomic) PFUbiquityLocation *metadataStoreFileLocation; // @synthesize metadataStoreFileLocation=_metadataStoreFileLocation;

- (id)peerForPeerID:(id)arg1 createIfMissing:(_Bool)arg2;

- (_Bool)purgeAndInitializeMetadataStoreFileWithError:(id *)arg1;

- (_Bool)purgeMetadataForStoreMetadata:(id)arg1 withError:(id *)arg2;

@property(readonly, nonatomic) NSString *storeName; // @synthesize storeName=_storeName;

@property(readonly, nonatomic) PFUbiquityLocation *ubiquityRootURL; // @synthesize ubiquityRootURL=_ubiquityRootURL;



@end


