/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSArray, NSDictionary, NSExpression, NSString;



@interface NSPropertyMapping : NSObject

{

    void *_reserved;

    NSArray *_transformValidations;

    NSArray *_propertyTransforms;

    NSString *_name;

    NSExpression *_valueExpression;

    NSDictionary *_userInfo;

    struct __propertyMappingFlags {

        unsigned int _isInUse:1;

        unsigned int _reservedPropertyMapping:31;

    } _propertyMappingFlags;

}



+ (void)initialize;

- (void)_createCachesAndOptimizeState;

- (id)_initWithDestinationName:(id)arg1 valueExpression:(id)arg2;

- (id)_propertyTransforms;

- (void)_setIsEditable:(_Bool)arg1;

- (void)_setPropertyTransforms:(id)arg1;

- (void)_setTransformValidations:(id)arg1;

- (void)_throwIfNotEditable;

- (id)_transformValidations;

- (id)copyWithZone:(struct _NSZone *)arg1;

- (void)dealloc;

- (id)description;

- (void)encodeWithCoder:(id)arg1;

- (id)init;

- (id)initWithCoder:(id)arg1;

- (id)initWithName:(id)arg1 valueExpression:(id)arg2;

- (_Bool)isEditable;

- (_Bool)isEqual:(id)arg1;

- (id)name;

- (void)setName:(id)arg1;

- (void)setUserInfo:(id)arg1;

- (void)setValueExpression:(id)arg1;

- (id)userInfo;

- (id)valueExpression;



@end


