/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@protocol LabelManagerDelegate <NSObject>

- (void)labelManager:(struct LabelManager *)arg1 pendingArtworkIsReady:(_Bool)arg2;

- (void)labelManager:(struct LabelManager *)arg1 selectedLabelMarkerWillDisappear:(id)arg2;

- (void)labelManager:(struct LabelManager *)arg1 setNeedsDisplay:(_Bool)arg2;

- (void)labelManager:(struct LabelManager *)arg1 setNeedsLayout:(_Bool)arg2;

@end


