/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "VGLMesh.h"


__attribute__((visibility("hidden")))

@interface VGLRouteLineArrowMesh : VGLMesh

{

}



- (id)initWithVertexCapacity:(int)arg1 indexCapacity:(int)arg2;



@end


