/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





__attribute__((visibility("hidden")))

@interface VKFootprint : NSObject

{

    CDStruct_aca18c62 _boundingRect;

    struct VKFootprintConvexHull_struct _convexHull;

    double _maxDistance;

    struct VKPoint _furthestGroundPoint;

    double _minDistance;

    struct VKPoint _nearestGroundPoint;

    double _minDepth;

    double _maxDepth;

    double _centerDepth;

    int _cornerGroundPointsCount;

    struct VKPoint _cornerGroundPoints[12];

}



- (id).cxx_construct;

@property(readonly, nonatomic) CDStruct_d2b197d1 boundingRect; // @synthesize boundingRect=_boundingRect;

@property(readonly, nonatomic) double centerDepth; // @synthesize centerDepth=_centerDepth;

- (void)computeFromCamera:(id)arg1;

- (_Bool)containsGroundPoint:(struct VKPoint *)arg1;

@property(readonly, nonatomic) struct VKFootprintConvexHull_struct convexHull; // @synthesize convexHull=_convexHull;

@property(readonly, nonatomic) struct VKPoint *cornerGroundPoints;

@property(readonly, nonatomic) int cornerGroundPointsCount; // @synthesize cornerGroundPointsCount=_cornerGroundPointsCount;

@property(readonly, nonatomic) struct VKPoint furthestGroundPoint; // @synthesize furthestGroundPoint=_furthestGroundPoint;

@property(readonly, nonatomic) double maxDepth; // @synthesize maxDepth=_maxDepth;

@property(readonly, nonatomic) double minDepth; // @synthesize minDepth=_minDepth;

@property(readonly, nonatomic) struct VKPoint nearestGroundPoint; // @synthesize nearestGroundPoint=_nearestGroundPoint;

- (_Bool)rejectsRect:(const CDStruct_d2b197d1 *)arg1;



@end


