/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





__attribute__((visibility("hidden")))

@interface VKMercatorTerrainHeightCache : NSObject

{

    id <VKMercatorTerrainHeightProvider> _heightProvider;

    struct map<vk::Anchor *, float, std::__1::less<vk::Anchor *>, std::__1::allocator<std::__1::pair<vk::Anchor *const, float>>> _anchorToHeight;

}



- (id).cxx_construct;

- (void).cxx_destruct;

- (double)heightForAnchor:(struct Anchor *)arg1;

@property(nonatomic) id <VKMercatorTerrainHeightProvider> heightProvider; // @synthesize heightProvider=_heightProvider;

- (void)invalidateRect:(const CDStruct_d2b197d1 *)arg1;

- (void)removeCachedValueForAnchor:(struct Anchor *)arg1;



@end


