/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class VKAttributedRouteMatch;



__attribute__((visibility("hidden")))

@interface VKPuckAnimatorLocationProjector : NSObject

{

    VKAttributedRouteMatch *_routeMatch;

    VKAttributedRouteMatch *_projectedRouteMatch;

    struct VKPoint _projectedPosition;

    double _projectedCourse;

}



- (id).cxx_construct;

- (void)_updateCourseAndPositionFromRouteMatch;

- (void)dealloc;

- (id)init;

- (void)projectFromLocation:(id)arg1 routeMatch:(id)arg2 speedMultiplier:(double)arg3;

@property(readonly, nonatomic) double projectedCourse; // @synthesize projectedCourse=_projectedCourse;

@property(readonly, nonatomic) CDStruct_c3b9c2ee projectedLocation;

@property(readonly, nonatomic) _Bool projectedLocationOnRoute;

@property(readonly, nonatomic) struct VKPoint projectedPosition; // @synthesize projectedPosition=_projectedPosition;

@property(retain, nonatomic) VKAttributedRouteMatch *projectedRouteMatch; // @synthesize projectedRouteMatch=_projectedRouteMatch;

- (void)reset;

@property(retain, nonatomic) VKAttributedRouteMatch *routeMatch; // @synthesize routeMatch=_routeMatch;



@end


