/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSData;



@interface VKRasterMapTile : NSObject

{

    NSData *_bitmapData;

    struct VKTileKey _superTileKey;

    struct VKTileKey _finalTileKey;

    double _scale;

    struct CGImage *_image;

}



- (struct CGImage *)_image;

- (void)dealloc;

- (void)foreachTileOfSize:(unsigned int)arg1 perform:(id)arg2 completion:(void)arg3;

- (id)imageDataInFormat:(unsigned long long)arg1;

- (id)initWithBitmapData:(id)arg1 superKey:(const struct VKTileKey *)arg2 finalKey:(const struct VKTileKey *)arg3 scale:(double)arg4;

- (id)initWithBitmapData:(id)arg1 tileKey:(const struct VKTileKey *)arg2 scale:(double)arg3;

- (id)tileForKey:(const struct VKRasterTileKey *)arg1;

@property(readonly, nonatomic) struct VKRasterTileKey tileKey;

- (_Bool)writeImageToFile:(id)arg1 format:(unsigned long long)arg2 error:(id *)arg3;



@end


