/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "VKVectorMapModel.h"


#import "VKMapLayer.h"



@class VGLRenderState, VKSkyModel;



__attribute__((visibility("hidden")))

@interface VKRealisticMapModel : VKVectorMapModel <VKMapLayer>

{

    VGLRenderState *_renderState;

    double _fade;

    float _sceneAlpha;

    id <VKRoutePreloadSession> _routePreloadSession;

    _Bool _disableRealisticRoads;

    _Bool _disableRealisticLand;

    VKSkyModel *_skyModel;

}



- (double)_calculateZoomLevelWithContext:(id)arg1;

- (void)dealloc;

@property(nonatomic) _Bool disableRealisticLand; // @synthesize disableRealisticLand=_disableRealisticLand;

@property(nonatomic) _Bool disableRealisticRoads; // @synthesize disableRealisticRoads=_disableRealisticRoads;

- (void)drawDebugScene:(id)arg1 withContext:(id)arg2;

- (void)drawScene:(id)arg1 withContext:(id)arg2;

- (id)init;

- (void)layoutScene:(id)arg1 withContext:(id)arg2;

- (unsigned long long)mapLayerPosition;

- (_Bool)minimumZoomLevelBoundsCamera;

- (void)preloadNavigationSceneAnimationResourcesForDisplayStyle:(long long)arg1 context:(id)arg2;

- (void)preloadRenderingResourcesWithContext:(id)arg1;

@property(retain, nonatomic) id <VKRoutePreloadSession> routePreloadSession;

@property(nonatomic) float sceneAlpha; // @synthesize sceneAlpha=_sceneAlpha;

@property(retain, nonatomic) VKSkyModel *skyModel; // @synthesize skyModel=_skyModel;

- (void)stylesheetDidChange;

- (void)stylesheetWillChange;

- (unsigned int)supportedRenderPasses;

- (_Bool)wantsCategorizedSourceTiles;

- (void)willStartDrawingTiles:(id)arg1;



@end


