/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "MCVPNPayloadBase.h"


@class NSArray, NSString;



@interface MCAppLayerVPNPayload : MCVPNPayloadBase

{

    NSString *_VPNUUID;

    NSArray *_SafariDomains;

}



+ (id)localizedPluralForm;

+ (id)localizedSingularForm;

+ (id)typeStrings;

- (void).cxx_destruct;

@property(retain, nonatomic) NSArray *SafariDomains; // @synthesize SafariDomains=_SafariDomains;

@property(retain, nonatomic) NSString *VPNUUID; // @synthesize VPNUUID=_VPNUUID;

- (id)description;

- (id)initWithDictionary:(id)arg1 profile:(id)arg2 outError:(id *)arg3;

- (id)stubDictionary;



@end


