/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class CPDistributedMessagingCenter, NSData, NSDictionary, NSMutableArray, NSObject<OS_dispatch_queue>, NSTimer;



@interface MCProfileConnection : NSObject

{

    CPDistributedMessagingCenter *_messageCenter;

    struct __CFBag *_observers;

    CPDistributedMessagingCenter *_interactionServer;

    id <MCInteractionDelegate> _interactionDelegate;

    id _interactionLockDelayedContext;

    NSDictionary *_preflightResponse;

    NSData *_originalProfileData;

    _Bool _needToRestoreOriginalProfileData;

    int _userInputTimeoutType;

    NSTimer *_userInputTimer;

    NSObject<OS_dispatch_queue> *_notificationSyncQueue;

    NSMutableArray *_notificationTokens;

}



+ (id)sharedConnection;

- (void).cxx_destruct;

- (void)__checkForProfiledCrash;

- (void)__doMCICDidFinish:(id)arg1;

- (void)_appWhitelistDidChange:(id)arg1;

- (void)_applyToObservers:(id)arg1;

- (void)_cancelUserInputTimeout;

- (void)_defaultsDidChange;

- (void)_detectProfiledCrashes;

- (void)_doMCICDidBeginInstallingNextProfileData:(id)arg1 params:(id)arg2;

- (void)_doMCICDidFinish:(id)arg1 params:(id)arg2;

- (void)_doMCICDidRequestCurrentPasscode:(id)arg1 params:(id)arg2;

- (void)_doMCICDidUpdateStatus:(id)arg1 params:(id)arg2;

- (void)_doMCICPreflightResponse:(id)arg1 params:(id)arg2;

- (void)_doMCICRequestUserInput:(id)arg1 params:(id)arg2;

- (void)_doMCICShowUserWarnings:(id)arg1 params:(id)arg2;

- (void)_effectiveSettingsDidChange:(id)arg1;

- (int)_getPasscodeComplianceWarningExpiryDate:(id)arg1 lastLockDate:(id)arg2 outLocalizedTitle:(id *)arg3 outLocalizedMessage:(id *)arg4;

- (id)_init;

- (void)_internalDefaultsDidChange;

- (_Bool)_openSensitiveURLString:(id)arg1 unlock:(_Bool)arg2;

- (void)_passcodeDidChange;

- (void)_passcodePolicyDidChange;

- (void)_profileListDidChange;

- (id)_queueDataForAcceptance:(id)arg1 originalFileName:(id)arg2 transitionToUI:(_Bool)arg3 outError:(id *)arg4;

- (void)_registerSelectorsForInteractionServer:(id)arg1;

- (void)_restrictionDidChange;

- (void)_setTimeoutWaitingForUserInputType:(int)arg1;

- (void)_tearDownInteractionServer;

- (void)_userInputTimerFired;

- (id)acceptedFileExtensions;

- (id)acceptedMIMETypes;

- (void)addObserver:(id)arg1;

- (void)addUserBookmark:(id)arg1;

- (void)addWebContentFilterAutoPermittedURLString:(id)arg1;

- (id)allClientUUIDsForClientType:(id)arg1;

- (id)allowedOpenInAppBundleIDsAfterApplyingFilterToAppBundleIDs:(id)arg1 originatingAppBundleID:(id)arg2 originatingAccountIsManaged:(_Bool)arg3;

- (int)appWhitelistState;

- (int)applyRestrictionDictionary:(id)arg1 clientType:(id)arg2 clientUUID:(id)arg3 localizedClientDescription:(id)arg4 localizedWarningMessage:(id)arg5 complianceBlocking:(int)arg6 displayImmediateAlert:(_Bool)arg7 outRestrictionChanged:(_Bool *)arg8 outEffectiveSettingsChanged:(_Bool *)arg9 outError:(id *)arg10;

- (_Bool)applyRestrictionDictionary:(id)arg1 clientType:(id)arg2 clientUUID:(id)arg3 localizedClientDescription:(id)arg4 localizedWarningMessage:(id)arg5 outRestrictionChanged:(_Bool *)arg6 outEffectiveSettingsChanged:(_Bool *)arg7 outError:(id *)arg8;

- (_Bool)applyRestrictionDictionary:(id)arg1 clientType:(id)arg2 clientUUID:(id)arg3 outRestrictionChanged:(_Bool *)arg4 outEffectiveSettingsChanged:(_Bool *)arg5 outError:(id *)arg6;

- (id)autonomousSingleAppModePermittedBundleIDs;

- (int)boolRestrictionForFeature:(id)arg1;

- (void)cancelUserInputResponses;

- (_Bool)changePasscodeFrom:(id)arg1 to:(id)arg2 outError:(id *)arg3;

- (id)chaperoneOrganization;

- (void)checkCarrierProfile;

- (void)checkCarrierProfileForceInstallation:(_Bool)arg1;

- (void)checkIn;

- (void)checkInAsynchronously;

- (_Bool)clearPasscodeWithEscrowKeybagData:(id)arg1 secret:(id)arg2 outError:(id *)arg3;

- (id)cloudConfigurationDetails;

- (void)cloudConfigurationUIDidCompleteWasApplied:(_Bool)arg1;

- (_Bool)currentPasscodeIsCompliantWithGlobalRestrictionsOutError:(id *)arg1;

- (_Bool)currentPasscodeIsCompliantWithProfileRestrictionsOutError:(id *)arg1;

- (void)dealloc;

- (int)defaultBoolValueForSetting:(id)arg1;

- (id)defaultParametersForBoolSetting:(id)arg1;

- (id)defaultParametersForIntersectionSetting:(id)arg1;

- (id)defaultParametersForUnionSetting:(id)arg1;

- (id)defaultParametersForValueSetting:(id)arg1;

- (id)defaultUserBookmarks;

- (id)defaultValueForSetting:(id)arg1;

- (id)defaultValuesForIntersectionSetting:(id)arg1;

- (id)defaultValuesForUnionSetting:(id)arg1;

- (id)doNotBackupAppIDs;

- (id)doNotDocumentSyncAppIDs;

- (int)effectiveBoolValueForSetting:(id)arg1;

- (id)effectiveParametersForBoolSetting:(id)arg1;

- (id)effectiveParametersForIntersectionSetting:(id)arg1;

- (id)effectiveParametersForUnionSetting:(id)arg1;

- (id)effectiveParametersForValueSetting:(id)arg1;

- (int)effectiveRestrictedBoolValueForSetting:(id)arg1;

- (id)effectiveRestrictions;

- (id)effectiveUserSettings;

- (id)effectiveValueForSetting:(id)arg1;

- (id)effectiveValuesForIntersectionSetting:(id)arg1;

- (id)effectiveValuesForUnionSetting:(id)arg1;

- (id)effectiveWhitelistedAppBundleIDs;

- (id)effectiveWhitelistedAppsAndOptions;

- (id)filteredMailSheetAccountsForBundleID:(id)arg1 sourceAccountManagement:(int)arg2;

- (void)getPasscodeComplianceWarningLastLockDate:(id)arg1 completionBlock:(id)arg2;

- (int)getPasscodeComplianceWarningLastLockDate:(id)arg1 outLocalizedTitle:(id *)arg2 outLocalizedMessage:(id *)arg3;

- (unsigned long long)gracePeriod;

- (int)hostMayPairWithOptions:(id)arg1 challenge:(id)arg2;

- (void)installProfileData:(id)arg1 interactionDelegate:(id)arg2;

- (void)installProfileData:(id)arg1 options:(id)arg2 interactionDelegate:(id)arg3;

- (id)installProfileData:(id)arg1 options:(id)arg2 outError:(id *)arg3;

- (id)installProfileData:(id)arg1 outError:(id *)arg2;

- (void)installProfileDataStoredForPurpose:(int)arg1 completionBlock:(id)arg2;

- (_Bool)installProvisioningProfileData:(id)arg1 managingProfileIdentifier:(id)arg2 outError:(id *)arg3;

- (id)installedProfileIdentifiers;

- (id)installedProfileIdentifiersWithFilterFlags:(int)arg1;

- (id)installedProfileWithIdentifier:(id)arg1;

- (id)installedProfilesWithFilterFlags:(int)arg1;

- (_Bool)isActivationLockAllowed;

- (_Bool)isAdTrackingLimited;

- (_Bool)isAirDropAllowed;

- (_Bool)isAppInstallationAllowed;

- (_Bool)isAppManaged:(id)arg1;

- (_Bool)isAppRatingLimitInEffect;

- (_Bool)isAssistantUserGeneratedContentAllowed;

- (_Bool)isAutomaticAppUpdatesAllowed;

- (_Bool)isAutomaticAppUpdatesModificationAllowed;

- (_Bool)isBoolSettingLockedDownByRestrictions:(id)arg1;

- (_Bool)isChaperoned;

- (_Bool)isCloudConfigurationAvailable;

- (_Bool)isCloudKeychainSyncAllowed;

- (_Bool)isContentProtectionInEffect;

- (_Bool)isControlCenterAllowedInApps;

- (_Bool)isFingerprintModificationAllowed;

- (_Bool)isFingerprintUnlockAllowed;

- (_Bool)isInSingleAppMode;

- (_Bool)isIntersectionSettingLockedDownByRestrictions:(id)arg1;

- (_Bool)isLockScreenControlCenterAllowed;

- (_Bool)isLockScreenNotificationsViewAllowed;

- (_Bool)isLockScreenTodayViewAllowed;

- (_Bool)isLockScreenWiFiModificationAllowed;

- (_Bool)isMUAllowed;

- (_Bool)isOTAPKIUpdatesAllowed;

- (_Bool)isOpenInRestrictionInEffect;

- (_Bool)isParentalControlsAllowPasscodeAccessToNonWhitelistedAppsUIForcedByRestrictions;

- (_Bool)isPasscodeRequired;

- (_Bool)isPasscodeRequiredByPolicy;

- (_Bool)isPasscodeRequiredByProfiles;

- (_Bool)isPasscodeRequiredToAccessWhitelistedApps;

- (_Bool)isPasscodeSet;

- (_Bool)isSupervised;

- (_Bool)isTeslaCloudConfigurationAvailable;

- (_Bool)isUnionSettingLockedDownByRestrictions:(id)arg1;

- (_Bool)isValueSettingLockedDownByRestrictions:(id)arg1;

- (_Bool)isVehicleUIAllowed;

- (_Bool)isWebFilterUIActive;

- (_Bool)isWebTextDefineAllowed;

- (id)knownAirPrintIPPURLStrings;

- (id)localizedDescriptionOfCurrentPasscodeConstraints;

- (void)lockDevice;

- (void)lockDeviceImmediately:(_Bool)arg1;

- (void)lockdownDidReceiveActivationRecord:(id)arg1;

- (id)managedAppIDsWithFlags:(int)arg1;

- (id)managedSystemConfigurationServiceIDs;

- (id)managedWiFiNetworkNames;

- (void)markStoredProfileForPurposeAsInstalled:(int)arg1;

- (_Bool)mayEnterPasscodeToAccessNonWhitelistedApps;

- (_Bool)mayOpenFromManagedToUnmanaged;

- (_Bool)mayOpenFromUnmanagedToManaged;

- (id)messageCenter;

- (void)migratePostDataMigrator;

- (int)newPasscodeEntryScreenType;

- (void)notifyClientsToRecomputeCompliance;

- (void)notifyUserHasSeenComplianceMessageWithLastLockDate:(id)arg1;

- (id)objectForFeature:(id)arg1;

- (id)objectRestrictionForFeature:(id)arg1;

- (id)parametersForBoolSetting:(id)arg1;

- (id)parametersForIntersectionSetting:(id)arg1;

- (id)parametersForUnionSetting:(id)arg1;

- (id)parametersForValueSetting:(id)arg1;

- (_Bool)parentalControlsAllowPasscodeAccessToNonWhitelistedApps;

- (id)parentalControlsAvailableAppBundleIDsForWhitelisting;

- (void)parentalControlsSetAllowPasscodeAccessToNonWhitelistedApps:(_Bool)arg1;

- (id)parentalControlsWhitelistedAppBundleIDs;

- (_Bool)passcode:(id)arg1 meetsCurrentConstraintsOutError:(id *)arg2;

- (id)passcodeExpiryDate;

- (id)passcodeExpiryDateOutError:(id *)arg1;

- (void)performBootTimeChecks;

- (id)popProfileDataFromHeadOfInstallationQueue;

- (id)popProvisioningProfileDataFromHeadOfInstallationQueue;

- (void)preflightUserInputResponses:(id)arg1 forPayloadIndex:(unsigned long long)arg2;

- (void)processProfilesPostMigrate;

- (void)processProfilesPostRestore;

- (void)profileDataStoredForPurpose:(int)arg1 completionBlock:(id)arg2;

- (id)profileFromProfileData:(id)arg1 outError:(id *)arg2;

- (id)publicMessageCenter;

- (id)queueFileDataForAcceptance:(id)arg1 originalFileName:(id)arg2 outError:(id *)arg3;

- (id)queueFileDataForProfileInstallation:(id)arg1 originalFileName:(id)arg2 outError:(id *)arg3;

- (id)queueProfileDataForAcceptance:(id)arg1 outError:(id *)arg2;

- (id)queueProfileDataForInstallation:(id)arg1 outError:(id *)arg2;

- (void)recomputeUserComplianceWarning;

- (void)recomputeUserComplianceWarningSynchronously;

- (void)removeBoolSetting:(id)arg1;

- (void)removeExpiredProfiles;

- (void)removeObserver:(id)arg1;

- (void)removeOrphanedClientRestrictions;

- (void)removeProfileAsyncWithIdentifier:(id)arg1;

- (void)removeProfileWithIdentifier:(id)arg1;

- (void)removeProfileWithIdentifier:(id)arg1 completion:(id)arg2;

- (void)removeProfilesFromInstallationQueue;

- (_Bool)removeProvisioningProfileWithUUID:(id)arg1 outError:(id *)arg2;

- (void)removeValueSetting:(id)arg1;

- (void)rereadManagedAppAttributes;

- (void)resetAllSettingsToDefaults;

- (void)respondToCurrentPasscodeRequestContinue:(_Bool)arg1 passcode:(id)arg2;

- (void)respondToWarningsContinueInstallation:(_Bool)arg1;

- (int)restrictedBoolValueForFeature:(id)arg1;

- (void)retrieveAndStoreCloudConfigurationDetailsCompletionBlock:(id)arg1;

- (void)retrieveCloudConfigurationDetailsCompletionBlock:(id)arg1;

- (void)retrieveCloudConfigurationFromURL:(id)arg1 username:(id)arg2 password:(id)arg3 anchorCertificates:(id)arg4 completionBlock:(id)arg5;

- (void)setAutomaticAppUpdatesAllowed:(_Bool)arg1;

- (void)setBoolValue:(_Bool)arg1 forSetting:(id)arg2;

- (void)setBoolValue:(_Bool)arg1 forSetting:(id)arg2 passcode:(id)arg3;

- (void)setDelegate:(id)arg1;

- (void)setFingerprintUnlockAllowed:(_Bool)arg1 passcode:(id)arg2 completionBlock:(id)arg3;

- (void)setGracePeriod:(unsigned long long)arg1 passcode:(id)arg2 completionBlock:(id)arg3;

- (void)setInteractionDelegate:(id)arg1;

- (void)setParameters:(id)arg1 forBoolSetting:(id)arg2;

- (void)setParameters:(id)arg1 forValueSetting:(id)arg2;

- (void)setParametersForSettingsByType:(id)arg1;

- (void)setParametersForSettingsByType:(id)arg1 passcode:(id)arg2;

- (void)setParentalControlsWhitelistedAppBundleIDs:(id)arg1;

- (void)setPasscodeWasSetInBackup:(_Bool)arg1;

- (void)setUserBookmarks:(id)arg1;

- (void)setUserInfo:(id)arg1 forClientUUID:(id)arg2;

- (void)setValue:(id)arg1 forSetting:(id)arg2;

- (void)setValue:(id)arg1 forSetting:(id)arg2 passcode:(id)arg3;

- (void)setValues:(id)arg1 forIntersectionSetting:(id)arg2;

- (void)setValues:(id)arg1 forUnionSetting:(id)arg2;

- (void)setWebContentFilterAutoPermittedURLStrings:(id)arg1;

- (void)setWebContentFilterUserBlacklistedURLStrings:(id)arg1;

- (void)setupAssistantDidFinish;

- (_Bool)shouldInstallStoredProfileForPurpose:(int)arg1;

- (_Bool)shouldShowCloudConfigurationUI;

- (_Bool)shouldSkipSetupPanes;

- (_Bool)showProfileErrorUIWithProfileIdentifier:(id)arg1 outError:(id *)arg2;

- (void)shutDown;

- (void)stashUserBookmarksWithLabel:(id)arg1 newUserBookmarks:(id)arg2;

- (void)storeCertificateData:(id)arg1 forHostIdentifier:(id)arg2;

- (void)storeCloudConfigurationDetails:(id)arg1;

- (void)storeProfileData:(id)arg1 configurationSource:(int)arg2 purpose:(int)arg3;

- (void)submitUserInputResponses:(id)arg1;

- (_Bool)transitionToProfileAcceptanceUI;

- (_Bool)transitionToProfileAcceptanceUIAndReturnToBundleID:(id)arg1;

- (_Bool)transitionToProfileOverviewUI;

- (_Bool)unlockDeviceWithPasscode:(id)arg1 outError:(id *)arg2;

- (int)unlockScreenType;

- (void)unstashUserBookmarksFromLabel:(id)arg1;

- (void)updateProfileWithIdentifier:(id)arg1 interactionDelegate:(id)arg2;

- (id)updateProfileWithIdentifier:(id)arg1 outError:(id *)arg2;

- (id)userBookmarks;

- (id)userInfoForClientUUID:(id)arg1;

- (id)userSettings;

- (_Bool)validatePasscode:(id)arg1;

- (_Bool)validatePasscode:(id)arg1 andUnlockContentProtectedDevice:(_Bool)arg2;

- (id)valueForFeature:(id)arg1;

- (id)valueRestrictionForFeature:(id)arg1;

- (_Bool)wasCloudConfigurationApplied;

- (_Bool)wasTeslaCloudConfigurationApplied;

- (id)webContentFilterEffectiveBlacklistedURLStrings;

- (id)webContentFilterUserBlacklistedURLStrings;



@end


