/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "MCAppWhitelistPayloadBase.h"


@interface MCSingleAppPayload : MCAppWhitelistPayloadBase

{

}



+ (id)localizedPluralForm;

+ (id)localizedSingularForm;

+ (id)typeStrings;

- (id)initWithDictionary:(id)arg1 profile:(id)arg2 outError:(id *)arg3;

- (_Bool)mustInstallNonInteractively;

- (id)restrictions;

- (id)subtitle1Description;

- (id)subtitle1Label;



@end


