/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "AAEmailVettingRequest.h"


@class NSString;



@interface AACompleteEmailVettingRequest : AAEmailVettingRequest

{

    NSString *_token;

}



+ (Class)responseClass;

- (void).cxx_destruct;

- (id)bodyDictionary;

- (id)initWithAccount:(id)arg1 token:(id)arg2;

- (id)initWithURLString:(id)arg1 account:(id)arg2 token:(id)arg3;

- (id)urlString;



@end


