/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "AARequest.h"


@class NSData, NSString;



@interface AADeviceProvisioningRequest : AARequest

{

    NSString *_dsid;

    NSString *_url;

    NSData *_data;

}



- (void).cxx_destruct;

- (id)initWithDSID:(id)arg1 URLString:(id)arg2 requestData:(id)arg3;

- (id)urlRequest;

- (id)urlString;



@end


