/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "AARequest.h"


@class ACAccount, NSString;



@interface AAUpdateProvisioningRequest : AARequest

{

    ACAccount *_account;

    NSString *_authToken;

}



+ (Class)responseClass;

- (void).cxx_destruct;

@property(retain, nonatomic) ACAccount *account; // @synthesize account=_account;

@property(copy, nonatomic) NSString *authToken; // @synthesize authToken=_authToken;

- (id)initWithAccount:(id)arg1;

- (id)initWithAccount:(id)arg1 token:(id)arg2;

- (id)initWithURLString:(id)arg1 account:(id)arg2;

- (id)urlCredential;

- (id)urlRequest;

- (id)urlString;



@end


