/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSMutableDictionary, NSSet;



__attribute__((visibility("hidden")))

@interface FontAssetDownloadManager : NSObject

{

    struct TCFRef<const __CFArray *> fDescriptors;

    struct TCFRef<const __CFSet *> fMandatoryAttributes;

    id fProgressCallbackBlock;

    NSMutableDictionary *fProgressParams;

    NSMutableDictionary *fDownloadOptions;

    NSSet *fPreciousFontLanguages;

}



+ (id)availableFontAttributesArray;

+ (id)displayNameForCurrentUser:(id)arg1;

+ (id)enabledKeyboardLanguages;

+ (Class)getASAssetQueryClass;

+ (_Bool)shouldIgnoreFontAsset:(id)arg1;

+ (_Bool)shouldRetryWithServer;

+ (_Bool)shouldTryServer;

- (id).cxx_construct;

- (void).cxx_destruct;

- (_Bool)activateFontsFromAssetURL:(id)arg1;

- (_Bool)assetStalled:(id)arg1;

- (id)availableMobileAssets:(_Bool)arg1 error:(id *)arg2;

- (unsigned long long)calculateDownloadSize:(id)arg1;

- (_Bool)callProgressCallbak:(unsigned int)arg1;

- (void)dealloc;

- (id)doFinalMatching;

- (void)downloadFontAssets;

- (_Bool)executeDownloadingFontAssets:(id)arg1 forDescriptors:(id)arg2 andFontFilePaths:(id)arg3;

- (id)extractMatchingAssetsForDescriptor:(struct __CTFontDescriptor *)arg1 from:(id)arg2 withFailInfo:(_Bool *)arg3 andFontFilePaths:(id)arg4;

- (id)getUnmatchedDescriptors;

- (id)initWithDescriptors:(struct __CFArray *)arg1 andMandatoryAttributes:(struct __CFSet *)arg2 withBlock:(id)arg3;

- (id)mobileAssetsForUnmatched:(id)arg1 andFontFilePaths:(id)arg2;

- (id)preciousFontLanguages;

- (void)setDownloadOptionsForMobileAsset;

- (void)setGarbageCollectionBehaviorForAsset:(id)arg1;

- (void)setProgressParam:(id)arg1 forKey:(id)arg2;



@end


