/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "SAUISnippet.h"


@class NSArray, NSString, SAMovieV2MovieDetailSnippet;



@interface SAMovieV2TheaterShowtimeListSnippet : SAUISnippet

{

}



+ (id)theaterShowtimeListSnippet;

+ (id)theaterShowtimeListSnippetWithDictionary:(id)arg1 context:(id)arg2;

- (id)encodedClassName;

- (id)groupIdentifier;

@property(retain, nonatomic) SAMovieV2MovieDetailSnippet *movieDetailSnippet;

@property(copy, nonatomic) NSString *subtitle;

@property(copy, nonatomic) NSArray *theaterShowtimeListCells;

@property(copy, nonatomic) NSString *title;



@end


