/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "SASettingGetValueResponse.h"


@class SASettingEntity;



@interface SASettingGetBoolResponse : SASettingGetValueResponse

{

}



+ (id)getBoolResponse;

+ (id)getBoolResponseWithDictionary:(id)arg1 context:(id)arg2;

+ (id)getBoolResponseWithSetting:(id)arg1;

- (id)encodedClassName;

- (id)groupIdentifier;

- (id)initWithSetting:(id)arg1;

@property(retain, nonatomic) SASettingEntity *setting;



@end


