/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "SABaseClientBoundCommand.h"


@class NSString;



@interface SASSpeechFailure : SABaseClientBoundCommand

{

}



+ (id)speechFailure;

+ (id)speechFailureWithDictionary:(id)arg1 context:(id)arg2;

- (id)encodedClassName;

@property(nonatomic) long long errorCode;

- (id)groupIdentifier;

@property(nonatomic) int reason;

@property(copy, nonatomic) NSString *reasonDescription;

- (_Bool)requiresResponse;



@end


