/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "AceObject.h"


#import "SAAceSerializable.h"



@class NSNumber, NSString;



@interface SAWebAcePicture : AceObject <SAAceSerializable>

{

}



+ (id)acePicture;

+ (id)acePictureWithDictionary:(id)arg1 context:(id)arg2;

- (id)encodedClassName;

@property(copy, nonatomic) NSString *format;

- (id)groupIdentifier;

@property(copy, nonatomic) NSNumber *height;

@property(copy, nonatomic) NSNumber *width;



@end


