/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIViewController.h"



#import "SKUINetworkErrorDelegate.h"

#import "SKUIProductPageOverlayDelegate.h"

#import "SKUIWishlistDelegate.h"

#import "UIPopoverControllerDelegate.h"



@class NSOperationQueue, SKUIClientContext, SKUIIPadSearchController, SKUINetworkErrorViewController, SKUIPopoverObserver, SKUIProductPageOverlayController, SKUIWishlistViewController, UIBarButtonItem;



@interface SKUIViewController : UIViewController <SKUINetworkErrorDelegate, SKUIProductPageOverlayDelegate, SKUIWishlistDelegate, UIPopoverControllerDelegate>

{

    SKUIClientContext *_clientContext;

    SKUINetworkErrorViewController *_networkErrorViewController;

    NSOperationQueue *_operationQueue;

    SKUIProductPageOverlayController *_productPageOverlayController;

    SKUIIPadSearchController *_searchController;

    _Bool _wishlistButtonHidden;

    UIBarButtonItem *_wishlistButtonItem;

    SKUIPopoverObserver *_wishlistPopoverObserver;

    SKUIWishlistViewController *_wishlistViewController;

}



- (void).cxx_destruct;

@property(readonly, nonatomic) SKUIIPadSearchController *IPadSearchController;

- (void)_reloadForOrientation:(long long)arg1;

- (void)_setWishlistButtonHidden:(_Bool)arg1;

- (void)_showDialogWithError:(id)arg1;

- (void)_wishlistAction:(id)arg1;

@property(readonly, nonatomic) UIBarButtonItem *_wishlistButtonItem; // @synthesize _wishlistButtonItem;

- (void)_wishlistPopoverDidDismiss;

@property(retain, nonatomic) SKUIClientContext *clientContext; // @synthesize clientContext=_clientContext;

- (void)dealloc;

- (void)networkErrorViewControllerInvalidated:(id)arg1;

@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;

- (void)productPageOverlayDidDismiss:(id)arg1;

- (void)reloadData;

- (void)showDefaultNavigationItems;

- (void)showError:(id)arg1;

- (void)viewWillAppear:(_Bool)arg1;

- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

- (void)wishlist:(id)arg1 didSelectItem:(id)arg2 atIndexPath:(id)arg3;



@end


