/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "SKUIItemGridCollectionViewLayout.h"


@class NSMutableArray, UICollectionView;



@interface SKUISearchCollectionViewFlowLayout : SKUIItemGridCollectionViewLayout

{

    UICollectionView *_collectionView;

    long long _numberOfRows;

    long long _numberOfColumns;

    NSMutableArray *_sectionCounts;

    struct CGSize _headerSize;

}



- (void).cxx_destruct;

- (long long)_globalIndexForIndexPath:(id)arg1;

- (id)_indexPathForGlobalIndex:(long long)arg1;

- (id)init;

- (id)layoutAttributesForDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2;

- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;

- (id)layoutAttributesForItemAtIndexPath:(id)arg1;

- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;

- (void)prepareLayout;



@end


