/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "SKUIRedeemStepViewController.h"


#import "UITextFieldDelegate.h"



@class NSString, SKUIRedeemTextField, UIBarButtonItem, UIImageView;



@interface SKUIRedeemInputViewController : SKUIRedeemStepViewController <UITextFieldDelegate>

{

    long long _category;

    SKUIRedeemTextField *_field;

    UIImageView *_imageView;

    NSString *_initialCode;

    UIBarButtonItem *_redeemButton;

}



- (void).cxx_destruct;

- (void)_cancelAction:(id)arg1;

- (id)_newTextFieldWithClientContext:(id)arg1;

- (void)_redeemAction:(id)arg1;

- (void)_redeemConfigurationImagesDidLoad:(id)arg1;

- (void)_termsButtonAction:(id)arg1;

- (void)_textFieldTextDidChange:(id)arg1;

@property(readonly, nonatomic) long long category; // @synthesize category=_category;

- (void)dealloc;

- (id)initWithRedeemCategory:(long long)arg1;

@property(copy, nonatomic) NSString *initialCode; // @synthesize initialCode=_initialCode;

- (void)loadView;

- (_Bool)textFieldShouldReturn:(id)arg1;



@end


