/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSOperationQueue, SKUIClientContext, UIWindow;



@interface SKUIStarRatingQueue : NSObject

{

    SKUIClientContext *_clientContext;

    NSOperationQueue *_queue;

    UIWindow *_window;

}



- (void).cxx_destruct;

- (void)_setRating:(long long)arg1 forItem:(id)arg2 account:(id)arg3 completionBlock:(id)arg4;

- (id)init;

- (id)initWithClientContext:(id)arg1;

- (void)setRating:(long long)arg1 forItem:(id)arg2 completionBlock:(id)arg3;

@property(nonatomic) __weak UIWindow *window; // @synthesize window=_window;



@end


