/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@interface CMAttitudeInternal : NSObject

{

    CDStruct_bf7dff04 fQuaternion;

}



- (id).cxx_construct;

- (id)initWithQuaternion:(CDStruct_bf7dff04)arg1;

- (void)setQuaternion:(CDStruct_bf7dff04)arg1;



@end


