/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSObject<OS_xpc_object>, NSString;



@interface IMRemoteObject : NSObject

{

    id _internal;

}



+ (void)_registerIMRemoteObject:(id)arg1;

+ (id)_remoteObjects;

+ (void)_unregisterIMRemoteObject:(id)arg1;

+ (void)initialize;

- (void)_cleanupMachBitsCanPost:(_Bool)arg1;

- (id)_initWithConnection:(id)arg1 portName:(id)arg2 protocol:(id)arg3 alreadyConfigured:(_Bool)arg4;

- (void)_portDidBecomeInvalid;

- (id)_queue;

- (void)_systemShutdown:(id)arg1;

@property(readonly, nonatomic) NSObject<OS_xpc_object> *connection;

- (void)dealloc;

- (id)description;

- (void)finalize;

- (void)forwardInvocation:(id)arg1;

- (unsigned long long)forwardXPCObject:(id)arg1 messageContext:(id)arg2;

- (id)initWithConnection:(id)arg1 protocol:(id)arg2;

- (id)initWithConnection:(id)arg1 protocol:(id)arg2 alreadyConfigured:(_Bool)arg3;

- (id)initWithPortName:(id)arg1 protocol:(id)arg2;

- (void)invalidate;

@property(readonly, nonatomic) _Bool isValid;

- (id)methodSignatureForSelector:(SEL)arg1;

@property(nonatomic) int pid;

@property(readonly, nonatomic) NSString *portName;

- (void)setPortName:(id)arg1;



@end


