/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "CPChunk.h"


#import "CPDisposable.h"



@interface CPTableCell : CPChunk <CPDisposable>

{

    struct CGRect cellBounds;

    CDStruct_627e0f85 rowSpan;

    CDStruct_627e0f85 columnSpan;

    struct {

        struct CGRect _field1;

        struct CGColor *_field2;

        unsigned int _field3;

        id *_field4;

    } *borders;

    struct CGColor *backgroundColor;

    unsigned int backgroundGraphicCount;

    id *backgroundGraphics;

}



- (struct CGColor *)backgroundColor;

- (id)backgroundGraphicAtIndex:(unsigned int)arg1;

@property(readonly, nonatomic) unsigned int backgroundGraphicCount; // @synthesize backgroundGraphicCount;

- (struct CGRect)boundsOfBorder:(int)arg1;

@property(readonly, nonatomic) struct CGRect cellBounds; // @synthesize cellBounds;

- (struct CGColor *)colorOfBorder:(int)arg1;

@property(nonatomic) CDStruct_627e0f85 columnSpan; // @synthesize columnSpan;

- (long long)compareCellOrdinal:(id)arg1;

- (void)dealloc;

- (void)dispose;

- (void)finalize;

- (unsigned int)graphicCountOfBorder:(int)arg1;

- (id)graphicObjectOfBorder:(int)arg1 atIndex:(unsigned int)arg2;

- (id)initWithBounds:(struct CGRect)arg1;

@property(nonatomic) CDStruct_627e0f85 rowSpan; // @synthesize rowSpan;

- (void)setBackgroundGraphics:(id)arg1;

- (void)setBorder:(int)arg1 bounds:(struct CGRect)arg2 graphics:(id)arg3;



@end


