/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "PBCodable.h"



#import "NSCopying.h"



@class NSMutableArray;



@interface GEOBusinessOptions : PBCodable <NSCopying>

{

    NSMutableArray *_attributeKeys;

    int _maxBusinessResults;

    NSMutableArray *_photoOptions;

    _Bool _includeBusinessHours;

    _Bool _includeCenter;

    struct {

        unsigned int maxBusinessResults:1;

        unsigned int includeBusinessHours:1;

        unsigned int includeCenter:1;

    } _has;

}



- (void)addAttributeKey:(id)arg1;

- (void)addPhotoOptions:(id)arg1;

- (id)attributeKeyAtIndex:(unsigned long long)arg1;

@property(retain, nonatomic) NSMutableArray *attributeKeys; // @synthesize attributeKeys=_attributeKeys;

- (unsigned long long)attributeKeysCount;

- (void)clearAttributeKeys;

- (void)clearPhotoOptions;

- (void)copyTo:(id)arg1;

- (id)copyWithZone:(struct _NSZone *)arg1;

- (void)dealloc;

- (id)description;

- (id)dictionaryRepresentation;

@property(nonatomic) _Bool hasIncludeBusinessHours;

@property(nonatomic) _Bool hasIncludeCenter;

@property(nonatomic) _Bool hasMaxBusinessResults;

- (unsigned long long)hash;

@property(nonatomic) _Bool includeBusinessHours; // @synthesize includeBusinessHours=_includeBusinessHours;

@property(nonatomic) _Bool includeCenter; // @synthesize includeCenter=_includeCenter;

- (_Bool)isEqual:(id)arg1;

@property(nonatomic) int maxBusinessResults; // @synthesize maxBusinessResults=_maxBusinessResults;

@property(retain, nonatomic) NSMutableArray *photoOptions; // @synthesize photoOptions=_photoOptions;

- (id)photoOptionsAtIndex:(unsigned long long)arg1;

- (unsigned long long)photoOptionsCount;

- (_Bool)readFrom:(id)arg1;

- (void)writeTo:(id)arg1;



@end


