/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "PBCodable.h"



#import "NSCopying.h"



@class NSMutableArray;



@interface GEOHours : PBCodable <NSCopying>

{

    CDStruct_95bda58d _days;

    NSMutableArray *_timeRanges;

}



- (void)addDay:(int)arg1;

- (void)addTimeRange:(id)arg1;

- (void)clearDays;

- (void)clearTimeRanges;

- (void)copyTo:(id)arg1;

- (id)copyWithZone:(struct _NSZone *)arg1;

- (int)dayAtIndex:(unsigned long long)arg1;

@property(readonly, nonatomic) int *days;

@property(readonly, nonatomic) unsigned long long daysCount;

- (void)dealloc;

- (id)description;

- (id)dictionaryRepresentation;

- (unsigned long long)hash;

- (_Bool)isEqual:(id)arg1;

- (_Bool)readFrom:(id)arg1;

- (void)setDays:(int *)arg1 count:(unsigned long long)arg2;

@property(retain, nonatomic) NSMutableArray *timeRanges; // @synthesize timeRanges=_timeRanges;

- (id)timeRangeAtIndex:(unsigned long long)arg1;

- (unsigned long long)timeRangesCount;

- (void)writeTo:(id)arg1;



@end


