/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "PBRequest.h"



#import "NSCopying.h"



@class GEORPUserCredentials, NSData, NSMutableArray, NSString;



@interface GEORPProblemCollectionRequest : PBRequest <NSCopying>

{

    NSString *_countryCode;

    NSData *_devicePushToken;

    NSString *_hwMachine;

    NSString *_inputLanguage;

    NSString *_osRelease;

    NSMutableArray *_requestElements;

    GEORPUserCredentials *_userCredentials;

}



- (void)addRequestElement:(id)arg1;

- (void)clearRequestElements;

- (void)copyTo:(id)arg1;

- (id)copyWithZone:(struct _NSZone *)arg1;

@property(retain, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;

- (void)dealloc;

- (id)description;

@property(retain, nonatomic) NSData *devicePushToken; // @synthesize devicePushToken=_devicePushToken;

- (id)dictionaryRepresentation;

@property(readonly, nonatomic) _Bool hasCountryCode;

@property(readonly, nonatomic) _Bool hasDevicePushToken;

@property(readonly, nonatomic) _Bool hasHwMachine;

@property(readonly, nonatomic) _Bool hasInputLanguage;

@property(readonly, nonatomic) _Bool hasOsRelease;

@property(readonly, nonatomic) _Bool hasUserCredentials;

- (unsigned long long)hash;

@property(retain, nonatomic) NSString *hwMachine; // @synthesize hwMachine=_hwMachine;

@property(retain, nonatomic) NSString *inputLanguage; // @synthesize inputLanguage=_inputLanguage;

- (_Bool)isEqual:(id)arg1;

@property(retain, nonatomic) NSString *osRelease; // @synthesize osRelease=_osRelease;

- (_Bool)readFrom:(id)arg1;

- (id)requestElementAtIndex:(unsigned long long)arg1;

@property(retain, nonatomic) NSMutableArray *requestElements; // @synthesize requestElements=_requestElements;

- (unsigned long long)requestElementsCount;

- (unsigned int)requestTypeCode;

- (Class)responseClass;

@property(retain, nonatomic) GEORPUserCredentials *userCredentials; // @synthesize userCredentials=_userCredentials;

- (void)writeTo:(id)arg1;



@end


