/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "PBCodable.h"



#import "NSCopying.h"



@class GEORPProblemContext, GEORPProblemCorrections;



@interface GEORPProblem : PBCodable <NSCopying>

{

    CDStruct_95bda58d _userPaths;

    GEORPProblemContext *_problemContext;

    GEORPProblemCorrections *_problemCorrections;

    int _problemType;

    unsigned int _protocolVersion;

    struct {

        unsigned int problemType:1;

        unsigned int protocolVersion:1;

    } _has;

}



- (void)addUserPath:(int)arg1;

- (void)clearUserPaths;

- (void)copyTo:(id)arg1;

- (id)copyWithZone:(struct _NSZone *)arg1;

- (void)dealloc;

- (id)description;

- (id)dictionaryRepresentation;

@property(readonly, nonatomic) _Bool hasProblemContext;

@property(readonly, nonatomic) _Bool hasProblemCorrections;

@property(nonatomic) _Bool hasProblemType;

@property(nonatomic) _Bool hasProtocolVersion;

- (unsigned long long)hash;

- (_Bool)isEqual:(id)arg1;

@property(retain, nonatomic) GEORPProblemContext *problemContext; // @synthesize problemContext=_problemContext;

@property(retain, nonatomic) GEORPProblemCorrections *problemCorrections; // @synthesize problemCorrections=_problemCorrections;

@property(nonatomic) int problemType; // @synthesize problemType=_problemType;

@property(nonatomic) unsigned int protocolVersion; // @synthesize protocolVersion=_protocolVersion;

- (_Bool)readFrom:(id)arg1;

- (void)setUserPaths:(int *)arg1 count:(unsigned long long)arg2;

- (int)userPathAtIndex:(unsigned long long)arg1;

@property(readonly, nonatomic) int *userPaths;

@property(readonly, nonatomic) unsigned long long userPathsCount;

- (void)writeTo:(id)arg1;



@end


