/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@interface GEORPProblemProvider : NSObject

{

}



+ (unsigned short)providerID;

- (void)cancelRequest;

- (void)startStatusRequest:(id)arg1 finished:(id)arg2 error:(void)arg3;

- (void)startSubmissionRequest:(id)arg1 finished:(id)arg2 error:(void)arg3;



@end


