/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "NSArray.h"



@class NSData;



@interface RadioTracksArray : NSArray

{

    NSData *_trackDescriptorsData;

}



- (void).cxx_destruct;

- (id)copyWithZone:(struct _NSZone *)arg1;

- (unsigned long long)count;

- (void)encodeWithCoder:(id)arg1;

- (id)initWithCoder:(id)arg1;

- (id)initWithTrackDescriptorsData:(id)arg1;

- (id)objectAtIndex:(unsigned long long)arg1;



@end


