/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "NSManagedObject.h"



@class NSData, NSDate, NSDictionary, NSString, NSURL;



@interface RadioManagedTrack : NSManagedObject

{

}



- (id)_keyForActionTextStyle:(long long)arg1;

- (long long)_offerTypeForOfferTypeString:(id)arg1;

- (id)_offerTypeStringForOfferType:(long long)arg1;

- (id)actionTextForStyle:(long long)arg1;

@property(retain, nonatomic) NSData *adData;

@property(nonatomic) long long afterPromoClipID;

@property(nonatomic) long long albumID;

@property(copy, nonatomic) NSURL *albumURL;

@property(copy, nonatomic) NSURL *artworkURL;

@property(copy, nonatomic) NSData *artworkURLData;

@property(nonatomic) long long beforePromoClipID;

@property(copy, nonatomic) NSString *copyrightText;

@property(copy, nonatomic) NSDate *dateAdded;

@property(nonatomic) long long dateFetched;

@property(copy, nonatomic) NSString *debugMessage;

@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;

@property(nonatomic) double duration;

- (id)feedbackDictionaryRepresentation;

@property(nonatomic) _Bool inWishList;

@property(nonatomic) _Bool isExplicit;

@property(nonatomic) int likeStatus;

@property(copy, nonatomic) NSString *offerBuyParameters;

@property(copy, nonatomic) NSString *offerFormattedPrice;

@property(nonatomic) float offerPrice;

@property(nonatomic) long long offerType;

@property(copy, nonatomic) NSURL *previewURL;

@property(copy, nonatomic) NSDictionary *promoContent;

- (void)setActionText:(id)arg1 forStyle:(long long)arg2;

@property(nonatomic) long long shuffleSeed;

@property(nonatomic) long long storeID;

@property(copy, nonatomic) NSDictionary *trackInfo;

@property(copy, nonatomic) NSDate *wishListDate;



// Remaining properties

@property(copy, nonatomic) NSString *album; // @dynamic album;

@property(copy, nonatomic) NSString *artist; // @dynamic artist;

@property(copy, nonatomic) NSString *title; // @dynamic title;



@end


