/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "RadioRequest.h"


@class NSString, SSURLConnectionRequest;



@interface RadioLikeRequest : RadioRequest

{

    long long _itemID;

    int _likeStatus;

    SSURLConnectionRequest *_request;

    int _seedType;

    NSString *_stationHash;

    long long _stationID;

    _Bool _isSeed;

}



- (void).cxx_destruct;

- (id)init;

- (id)initWithItemID:(long long)arg1 seedType:(int)arg2 station:(id)arg3;

- (id)initWithTrack:(id)arg1 station:(id)arg2;

- (id)initWithTrackID:(id)arg1 station:(id)arg2;

@property(nonatomic) _Bool isSeed; // @synthesize isSeed=_isSeed;

@property(nonatomic) int likeStatus; // @synthesize likeStatus=_likeStatus;

- (void)startWithCompletionHandler:(id)arg1;

- (void)startWithLikeCompletionHandler:(id)arg1;



@end


