/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "WFWebPageProtocol.h"



@class NSObject<WFWebPageProtocol>, NSString, WFImgArrayCache;



__attribute__((visibility("hidden")))

@interface WFWebPageDecorator : NSObject <WFWebPageProtocol>

{

    NSObject<WFWebPageProtocol> *webPageStripper;

    WFImgArrayCache *pageImagesPropertyCache;

    NSString *URLString;

}



+ (id)_plainTextWithSelector:(SEL)arg1 object:(id)arg2;

+ (id)plainTextWithWebPageData:(id)arg1;

+ (id)plainTextWithWebPageString:(id)arg1;

+ (id)webPageWithData:(id)arg1;

+ (id)webPageWithData:(id)arg1 URLString:(id)arg2;

+ (id)webPageWithString:(id)arg1;

+ (id)webPageWithString:(id)arg1 URLString:(id)arg2;

@property(retain) NSString *URLString; // @synthesize URLString;

- (void)_cacheImgProperties;

- (void)dealloc;

- (_Bool)hasFrameset;

- (_Bool)hasShortRefresh;

- (id)imageAltsText;

- (id)images;

- (id)initWithWebPageData:(id)arg1;

- (id)initWithWebPageString:(id)arg1;

- (id)initWithWebPageStripper:(id)arg1;

- (id)linkTitlesText;

- (id)links;

- (id)metaTagDescription;

- (id)metaTagKeywords;

- (id)metaTagsLabeled;

- (id)metaTagsUnlabeled;

- (long long)numberOfImages;

- (long long)numberOfKnownImagePixels;

- (long long)numberOfUnknownSizedImages;

- (id)pageContent;

- (id)pageTitle;

- (id)plainText;

- (id)plainTextAttributeWithSelector:(SEL)arg1 title:(id)arg2;

- (id)plainTextAttributeWithSelector:(SEL)arg1 title:(id)arg2 weight:(int)arg3;

- (id)rawPlainText;

- (id)scriptBlocks;

- (id)tags;

- (long long)wordCount;



@end


