/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "QLPreviewTransitionAnimator.h"


@interface QLPreviewZoomTransitionAnimator : QLPreviewTransitionAnimator

{

}



- (void)animateTransition:(id)arg1;

- (double)transitionDuration:(id)arg1;



@end


