/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "MFDAStreamingContentConsumer.h"



@class NSMutableData;



@interface MFDAMessageContentConsumer : NSObject <MFDAStreamingContentConsumer>

{

    int _requestedFormat;

    id <MFCollectingDataConsumer> _dataConsumer;

    id <MFCollectingDataConsumer> _alternatePartConsumer;

    id <MFMessageDataConsumerFactory> _consumerFactory;

    _Bool _triedCreatingAlternatePartConsumer;

    _Bool _succeeded;

    NSMutableData *_bodyData;

    double _timeOfLastActivity;

}



@property(retain, nonatomic) id <MFCollectingDataConsumer> alternatePartConsumer; // @synthesize alternatePartConsumer=_alternatePartConsumer;

@property(readonly, nonatomic) NSMutableData *bodyData; // @synthesize bodyData=_bodyData;

- (void)consumeData:(char *)arg1 length:(int)arg2 format:(int)arg3 mailMessage:(id)arg4;

@property(retain, nonatomic) id <MFMessageDataConsumerFactory> consumerFactory; // @synthesize consumerFactory=_consumerFactory;

- (id)data;

@property(retain, nonatomic) id <MFCollectingDataConsumer> dataConsumer; // @synthesize dataConsumer=_dataConsumer;

- (id)dataConsumerForPart:(id)arg1;

- (void)dealloc;

- (void)didEndStreamingForMailMessage:(id)arg1;

@property(nonatomic) int requestedFormat; // @synthesize requestedFormat=_requestedFormat;

- (_Bool)shouldBeginStreamingForMailMessage:(id)arg1 format:(int)arg2;

- (_Bool)succeeded;

@property(readonly, nonatomic) double timeOfLastActivity; // @synthesize timeOfLastActivity=_timeOfLastActivity;



@end


