/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@interface WebReadingList : NSObject

{

}



+ (_Bool)_isSupportedReadingListURL:(id)arg1;

- (void)addReadingListItemWithURL:(id)arg1 title:(id)arg2 previewText:(id)arg3;



@end


