/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "MFSASLAuthenticator.h"



@class CastleIMAPAccount;



@interface _MFNewcastleAuthenticator : MFSASLAuthenticator

{

    _Bool _sentResponse;

    CastleIMAPAccount *_castleAccount;

}



@property(retain, nonatomic) CastleIMAPAccount *castleAccount; // @synthesize castleAccount=_castleAccount;

- (void)dealloc;

- (id)initWithAuthScheme:(id)arg1 account:(id)arg2 connection:(id)arg3;

- (_Bool)justSentPlainTextPassword;

- (id)responseForServerData:(id)arg1;

- (id)saslName;

- (_Bool)supportsInitialClientResponse;



@end


