/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "IMAPAccount.h"


@interface AOLAccount : IMAPAccount

{

}



+ (id)_usernameWithHostname:(id)arg1;

+ (id)accountPropertiesValueForKey:(id)arg1 value:(id)arg2;

+ (id)defaultPathNameForAccountWithHostname:(id)arg1 username:(id)arg2;

+ (id)deliveryAccountHostname;

+ (unsigned int)deliveryAccountPortNumber;

+ (_Bool)deliveryAccountUsesSSL;

+ (id)displayedAccountTypeString;

+ (id)emailAddressHostPart;

+ (id)hostname;

+ (_Bool)isPredefinedAccountType;

+ (_Bool)usernameIsEmailAddress;

+ (_Bool)usesSSL;

- (id)_defaultSpecialMailboxNameForType:(int)arg1;

- (id)_deliveryAccountCreateIfNeeded:(_Bool)arg1;

- (_Bool)derivesDeliveryAccountInfoFromMailAccount;

- (id)displayUsername;

- (id)emailAddresses;

- (id)hostname;

- (id)iconString;

- (void)setHostname:(id)arg1;

- (void)setUsername:(id)arg1;

- (void)setUsesSSL:(_Bool)arg1;

- (id)statisticsKind;

- (_Bool)usesSSL;



@end


