/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class MFBaseFilterDataConsumer, MFCountingDataConsumer, NSMutableArray;



@interface MFIMAPDownload : NSObject

{

    unsigned int _uid;

    NSMutableArray *_pendingFetchResults;

    MFCountingDataConsumer *_countingConsumer;

    MFBaseFilterDataConsumer *_mainConsumer;

}



- (void)addCommandsToPipeline:(id)arg1 withCache:(id)arg2;

- (unsigned long long)bytesFetched;

- (unsigned long long)consumerBytesFetched;

- (id)data;

- (void)dealloc;

- (id)error;

- (unsigned long long)expectedLength;

- (void)handleFetchResult:(id)arg1;

- (id)initWithUid:(unsigned int)arg1;

- (_Bool)isComplete;

- (unsigned long long)lengthOfDataBeforeLineConversion;

@property(readonly, nonatomic) MFBaseFilterDataConsumer *mainConsumer; // @synthesize mainConsumer=_mainConsumer;

- (void)processResults;

- (void)setError:(id)arg1;

- (unsigned int)uid;



@end


