/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSArray;



@interface MFIMAPConnectionFlagSearchRequest : NSObject

{

    _Bool _isPositiveMatch;

    unsigned long long _mask;

    NSArray *_searchTerms;

}



+ (id)requestWithMask:(unsigned long long)arg1 searchTerms:(id)arg2 positiveMatch:(_Bool)arg3;

- (void)dealloc;

- (id)initWithMask:(unsigned long long)arg1 searchTerms:(id)arg2 positiveMatch:(_Bool)arg3;

@property(readonly, nonatomic) _Bool isPositiveMatch; // @synthesize isPositiveMatch=_isPositiveMatch;

@property(readonly, nonatomic) unsigned long long mask; // @synthesize mask=_mask;

@property(readonly, nonatomic) NSArray *searchTerms; // @synthesize searchTerms=_searchTerms;



@end


