/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class AXAccessQueue, NSMutableArray, NSString;



@interface AXIPCClient : NSObject

{

    struct __CFMachPort *_serverPort;

    unsigned int _assignedServerMachPort;

    id _portDeathHandler;

    float _timeout;

    NSString *_clientIdentifier;

    struct __CFRunLoopSource *_clientSource;

    unsigned long long _connectionAttempts;

    _Bool _connected;

    _Bool shouldRegisterCallbackSourceOnMainRunloop;

    unsigned int clientCallbackPort;

    NSString *_serviceName;

    NSMutableArray *_postConnectionTasks;

    AXAccessQueue *_connectionQueue;

    struct __CFRunLoopSource *clientCallbackSource;

}



+ (id)allClients;

+ (void)initialize;

- (void)_attemptToEstablishConnection;

- (void)_commonInit;

- (_Bool)_handleErrorWithMessage:(id)arg1 outError:(id *)arg2;

- (void)_registerWithServer;

- (void)_serverDied;

- (_Bool)_verifyConnectionWithError:(id *)arg1;

@property(readonly, nonatomic) unsigned int clientCallbackPort; // @synthesize clientCallbackPort;

@property(readonly, nonatomic) struct __CFRunLoopSource *clientCallbackSource; // @synthesize clientCallbackSource;

@property(copy, nonatomic) NSString *clientIdentifier; // @synthesize clientIdentifier=_clientIdentifier;

- (_Bool)connectWithError:(id *)arg1;

@property(retain, nonatomic) AXAccessQueue *connectionQueue; // @synthesize connectionQueue=_connectionQueue;

- (void)dealloc;

- (id)description;

- (_Bool)disconnectWithError:(id *)arg1;

- (void)establishConnectionWithTimeout:(double)arg1 completion:(id)arg2;

- (id)initWithPort:(unsigned int)arg1;

- (id)initWithServiceName:(id)arg1;

@property(nonatomic, getter=isConnected) _Bool connected; // @synthesize connected=_connected;

@property(copy, nonatomic) id portDeathHandler; // @synthesize portDeathHandler=_portDeathHandler;

@property(retain, nonatomic) NSMutableArray *postConnectionTasks; // @synthesize postConnectionTasks=_postConnectionTasks;

- (id)sendMessage:(id)arg1 withError:(id *)arg2;

- (void)sendSimpleMessage:(id)arg1;

- (_Bool)sendSimpleMessage:(id)arg1 withError:(id *)arg2;

@property(nonatomic) struct __CFMachPort *serverPort; // @synthesize serverPort=_serverPort;

@property(readonly, nonatomic) unsigned int serviceMachPort;

@property(copy, nonatomic) NSString *serviceName; // @synthesize serviceName=_serviceName;

@property(nonatomic) _Bool shouldRegisterCallbackSourceOnMainRunloop; // @synthesize shouldRegisterCallbackSourceOnMainRunloop;

@property(nonatomic) float timeout; // @synthesize timeout=_timeout;

- (_Bool)verifyConnectionExists;



@end


