/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIViewController.h"



#import "RCControlsViewDelegate.h"

#import "RCWaveformGeneratorSegmentOutputObserver.h"

#import "RCWaveformViewDelegate.h"



@class NSString, RCControlsView, RCGLWaveformViewController, UIBarButtonItem, UIColor, UIFont, UILabel;



@interface RCMemoPlaybackViewController : UIViewController <RCWaveformGeneratorSegmentOutputObserver, RCControlsViewDelegate, RCWaveformViewDelegate>

{

    _Bool _initWithNibNameOK;

    _Bool _animateNextLayout;

    _Bool _screenUpdatesDisabled;

    UILabel *_timeDisplayLabel;

    UIFont *_timeDisplayLabelFont;

    UILabel *_recordingNameLabel;

    UIFont *_recordingNameLabelFont;

    UILabel *_recordingDateLabel;

    UIFont *_recordingDateLabelFont;

    double _preferredTimeWidth;

    _Bool _playing;

    long long _controlsConfiguration;

    id <RCWaveformDataSource> _waveformDataSource;

    id <RCMemoPlaybackViewControllerDelegate> _memoControllerDelegate;

    double _currentTime;

    double _duration;

    UIColor *_backgroundColor;

    long long _timeDisplayType;

    RCGLWaveformViewController *_waveformViewController;

    RCControlsView *_controlsView;

    UIBarButtonItem *_rightNavigationButtonItem;

    UIBarButtonItem *_leftNavigationButtonItem;

    unsigned long long _dismissOptions;

}



- (void).cxx_destruct;

- (void)_layoutViews;

- (void)_recordingNameLabelAction:(id)arg1;

- (void)_setWaveformDataSource:(id)arg1 currentTime:(double)arg2;

- (void)_updateTimeViews;

- (void)applicationDidEnterBackgroundNotification:(id)arg1;

- (void)applicationWillEnterForegroundNotification:(id)arg1;

@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;

- (void)cancelEditing;

- (void)commitEditing;

@property(nonatomic) long long controlsConfiguration; // @synthesize controlsConfiguration=_controlsConfiguration;

@property(nonatomic) _Bool controlsHidden;

@property(readonly, nonatomic) RCControlsView *controlsView; // @synthesize controlsView=_controlsView;

- (void)controlsViewDidChooseDone:(id)arg1;

- (void)controlsViewDidChoosePausePlaying:(id)arg1;

- (void)controlsViewDidChoosePauseRecording:(id)arg1;

- (void)controlsViewDidChooseStartPlaying:(id)arg1;

- (void)controlsViewDidChooseStartRecording:(id)arg1;

@property(nonatomic) double currentTime; // @synthesize currentTime=_currentTime;

@property(readonly, nonatomic) long long defaultControlsConfiguration;

- (void)didFinishLoadingWaveform;

- (void)didUpdateWaveform;

- (void)dismiss;

@property(nonatomic) unsigned long long dismissOptions; // @synthesize dismissOptions=_dismissOptions;

@property(nonatomic) double duration; // @synthesize duration=_duration;

- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

- (id)initWithWaveformDataSource:(id)arg1;

@property(retain, nonatomic) UIBarButtonItem *leftNavigationButtonItem; // @synthesize leftNavigationButtonItem=_leftNavigationButtonItem;

@property(nonatomic) __weak id <RCMemoPlaybackViewControllerDelegate> memoControllerDelegate; // @synthesize memoControllerDelegate=_memoControllerDelegate;

- (id)navigationItem;

@property(nonatomic) _Bool playing; // @synthesize playing=_playing;

@property(retain, nonatomic) UILabel *recordingDateLabel; // @synthesize recordingDateLabel=_recordingDateLabel;

@property(retain, nonatomic) NSString *recordingDateText;

@property(retain, nonatomic) UILabel *recordingNameLabel; // @synthesize recordingNameLabel=_recordingNameLabel;

@property(retain, nonatomic) NSString *recordingNameText;

@property(retain, nonatomic) UIBarButtonItem *rightNavigationButtonItem; // @synthesize rightNavigationButtonItem=_rightNavigationButtonItem;

@property(nonatomic) _Bool screenUpdatesDisabled;

- (void)setControlsConfiguration:(long long)arg1 animate:(_Bool)arg2;

@property(retain, nonatomic) UILabel *timeDisplayLabel; // @synthesize timeDisplayLabel=_timeDisplayLabel;

@property(nonatomic) long long timeDisplayType; // @synthesize timeDisplayType=_timeDisplayType;

- (void)updateNavigationItem;

- (void)viewDidDisappear:(_Bool)arg1;

- (void)viewDidLoad;

- (void)viewWillAppear:(_Bool)arg1;

- (void)viewWillLayoutSubviews;

@property(readonly, nonatomic) id <RCWaveformDataSource> waveformDataSource; // @synthesize waveformDataSource=_waveformDataSource;

- (void)waveformGenerator:(id)arg1 didLoadWaveformSegment:(id)arg2;

- (void)waveformGeneratorDidFinishLoading:(id)arg1 error:(id)arg2;

- (void)waveformGeneratorWillBeginLoading:(id)arg1;

@property(readonly, nonatomic) RCGLWaveformViewController *waveformViewController; // @synthesize waveformViewController=_waveformViewController;

- (void)waveformViewController:(id)arg1 didScrubToTime:(double)arg2;

- (void)waveformViewControllerDidChangeSelectedTimeRange:(id)arg1;

- (void)willBeginLoadingWaveform;



@end


