/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIView.h"



@class NSString, UIImageView, UILabel;



@interface RCTrimHUD : UIView

{

    long long _style;

    UIImageView *_hudImageView;

    UIImageView *_hudLeftImageView;

    UIImageView *_hudLeftFillImageView;

    UIImageView *_hudBottomImageView;

    UIImageView *_hudRightFillImageView;

    UIImageView *_hudRightImageView;

    UILabel *_trimHUDLabel;

}



- (void).cxx_destruct;

- (id)_bounceAnimationWithDuration:(double)arg1;

- (double)_bounceValueForFraction:(double)arg1;

- (void)hideAnimated:(_Bool)arg1;

- (id)initWithFrame:(struct CGRect)arg1;

- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;

@property(copy, nonatomic) NSString *text;

- (void)showAnimated:(_Bool)arg1;

@property(readonly, nonatomic) long long style; // @synthesize style=_style;



@end


