/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIActionSheet.h"



@interface UIActionSheet (RCAdditions)

- (void)rc_showInView:(id)arg1 dismissHandlerBlock:(id)arg2;

@end


