/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@protocol _MFSearchResultsConsumer <NSObject>

- (void)_addResults:(id)arg1 ofType:(int)arg2;

- (void)_appendSortedResultsOfType:(int)arg1 excluding:(id)arg2 toResults:(id)arg3;

- (_Bool)_didFinishSearchForType:(int)arg1;

- (void)_enumerateSearchResultTypesInSortOrderUsingBlock:(id)arg1;

- (_Bool)_isResetting;

- (_Bool)_shouldProcessResultsAfterFinishingType:(int)arg1;

@end


