/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@interface MFAddressBookManager : NSObject

{

    void *_addressBook;

    int _lock;

    struct __CFDictionary *_clients;

}



+ (_Bool)isAuthorizedToUseAddressBook;

+ (id)sharedManager;

- (void)_applicationResumed:(id)arg1;

- (id)_clientWeakReferences;

- (void)_handleAddressBookChangeNotification;

- (void)_handleAddressBookPrefsChangeNotification;

- (void)addClient:(id)arg1;

- (void *)addressBook;

- (void)dealloc;

- (id)init;

- (void)removeClient:(id)arg1;



@end


