/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UITextContentView.h"



@interface MFComposeTextContentView : UITextContentView

{

    long long _preventScrollSelectionToVisible;

    _Bool _keepScrollPosition;

    struct CGPoint _scrollPosition;

}



- (_Bool)becomeFirstResponder;

- (void)beginPreventingScrollSelectionToVisible;

- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;

- (void)decreaseQuoteLevel;

- (id)enclosingScrollView;

- (void)endPreventingScrollSelectionToVisible;

- (void)ensureSelection;

- (void)increaseQuoteLevel;

- (_Bool)resignFirstResponder;

- (void)scrollSelectionToVisible:(_Bool)arg1;

- (void)showQuoteLevelOptions;

- (id)supportedPasteboardTypesForCurrentSelection;

- (id)targetForAction:(SEL)arg1 withSender:(id)arg2;



@end


