/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "MFMessageBodyParser.h"


@class NSScanner;



@interface MFMessageBodyHTMLParser : MFMessageBodyParser

{

    NSScanner *_scanner;

}



- (void)_consumeNodesFromNode:(id)arg1 upToNode:(id)arg2;

- (void)_findBody;

- (_Bool)_isMilestoneTagName:(id)arg1;

- (void)dealloc;

- (void)didFindError:(id)arg1;

- (id)initWithHTML:(id)arg1;

- (Class)messageBodyElementClass;

- (int)messageBodyStringAccumulatorDefaultOptions;

- (_Bool)parse;



@end


