/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIView.h"



@class MFModernAtomView;



@interface MFModernAtomBackgroundView : UIView

{

    UIView *_selectedView;

    UIView *_separatorView;

    MFModernAtomView *_hostAtomView;

    int _separatorStyle;

    _Bool _selected;

    double _scalingFactor;

}



- (id)_chevronImage;

- (void)dealloc;

@property(nonatomic) MFModernAtomView *hostAtomView; // @synthesize hostAtomView=_hostAtomView;

- (id)initWithFrame:(struct CGRect)arg1;

- (void)invalidateIntrinsicContentSize;

- (void)layoutSubviews;

@property(nonatomic) double scalingFactor; // @synthesize scalingFactor=_scalingFactor;

@property(nonatomic) _Bool selected; // @synthesize selected=_selected;

@property(nonatomic) int separatorStyle; // @synthesize separatorStyle=_separatorStyle;

@property(readonly, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;

- (double)separatorWidth;

- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;

- (void)tintColorDidChange;



@end


