/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIPopoverController.h"



#import "UIPopoverControllerDelegate.h"



@interface MFPopoverController : UIPopoverController <UIPopoverControllerDelegate>

{

    id _mailDelegate;

    id _mailPopoverManager;

    _Bool _isRotating;

}



- (void)dealloc;

- (void)dismissPopoverAnimated:(_Bool)arg1;

- (id)initWithContentViewController:(id)arg1;

@property(nonatomic) _Bool isRotating; // @synthesize isRotating=_isRotating;

@property(nonatomic) id <MFMailPopoverManagerDelegate> mailDelegate; // @synthesize mailDelegate=_mailDelegate;

@property(nonatomic) id mailPopoverManager; // @synthesize mailPopoverManager=_mailPopoverManager;

- (void)popoverController:(id)arg1 animationCompleted:(long long)arg2;

- (void)popoverControllerDidDismissPopover:(id)arg1;

- (_Bool)popoverControllerShouldDismissPopover:(id)arg1;



@end


