/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSString;



@interface MFReformattedAddress : NSObject

{

    NSString *_address;

    struct _NSRange _middleTruncationRange;

}



- (id)attributedStringWithFontSize:(double)arg1 maximumWidth:(double)arg2 options:(unsigned long long)arg3;

- (void)dealloc;

- (id)description;

@property(readonly, nonatomic) NSString *domainPart;

- (id)initWithAddress:(id)arg1;

@property(readonly, nonatomic) NSString *localPart;

@property(nonatomic) struct _NSRange middleTruncationRange; // @synthesize middleTruncationRange=_middleTruncationRange;

- (double)widthWithFontSize:(double)arg1 maximumWidth:(double)arg2 options:(unsigned long long)arg3;



@end


