/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSArray;



@interface CoreDAVRequestLogger : NSObject

{

    id <CoreDAVAccountInfoProvider> _provider;

    NSArray *_headerSortDescriptors;

    int _snippetsLogged;

}



- (id)_inflateRequestBody:(id)arg1;

- (void)dealloc;

- (void)finishCoreDAVResponse;

@property(retain) NSArray *headerSortDescriptors; // @synthesize headerSortDescriptors=_headerSortDescriptors;

- (id)initWithProvider:(id)arg1;

- (void)logCoreDAVRequest:(id)arg1 withTaskIdentifier:(id)arg2;

- (void)logCoreDAVResponseHeaders:(id)arg1 andStatusCode:(long long)arg2 withTaskIdentifier:(id)arg3;

- (void)logCoreDAVResponseSnippet:(id)arg1;

- (void)logCoreDAVResponseSnippet:(id)arg1 withTaskIdentifier:(id)arg2;



@end


