/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "CoreDAVItem.h"


@class CoreDAVLeafItem;



@interface CoreDAVPrincipalSearchPropertyItem : CoreDAVItem

{

    CoreDAVItem *_prop;

    CoreDAVLeafItem *_descriptionItem;

}



+ (id)copyParseRules;

- (void)dealloc;

- (id)description;

@property(retain) CoreDAVLeafItem *descriptionItem; // @synthesize descriptionItem=_descriptionItem;

- (id)init;

@property(retain) CoreDAVItem *prop; // @synthesize prop=_prop;



@end


