/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIView.h"



@class CAAnimation, NSMutableArray, NSMutableDictionary;



@interface TKVibrationRecorderRippleView : UIView

{

    _Bool _trackingTouch;

    _Bool _needsCurrentSpeedRefresh;

    _Bool _animating;

    double _fingerStillSpeed;

    double _fingerMovingSpeed;

    double _firstRippleInitialRadius;

    double _fadeOutRadius;

    id <TKVibrationRecorderStyleProvider> _styleProvider;

    double _currentTouchStartTime;

    unsigned long long _numberOfRipplesForCurrentTouch;

    NSMutableArray *_recentTouchesContextQueue;

    NSMutableArray *_reusableTouchContexts;

    double _currentSpeedCoefficient;

    NSMutableArray *_ringLayersQueue;

    NSMutableArray *_reusableRingLayers;

    NSMutableDictionary *_ringLayersByIdentifiers;

    unsigned long long _lastRingLayerIdentifier;

    CAAnimation *_ringEnlargementAnimation;

    struct CGPoint _currentTouchLocation;

}



@property(readonly, nonatomic) double _currentSpeed;

@property(nonatomic, setter=_setCurrentSpeedCoefficient:) double _currentSpeedCoefficient; // @synthesize _currentSpeedCoefficient;

@property(nonatomic, setter=_setCurrentTouchLocation:) struct CGPoint _currentTouchLocation; // @synthesize _currentTouchLocation;

@property(nonatomic, setter=_setCurrentTouchStartTime:) double _currentTouchStartTime; // @synthesize _currentTouchStartTime;

- (void)_enqueueReusableRingLayer:(id)arg1;

- (void)_enqueueReusableTouchContextObject:(id)arg1;

- (void)_enqueueRingLayerWithTimeIntervalSinceCreation:(double)arg1 normalizedLocation:(struct CGPoint)arg2 speed:(double)arg3;

@property(nonatomic, getter=_isAnimating, setter=_setAnimating:) _Bool _animating; // @synthesize _animating;

@property(readonly, nonatomic, getter=_isTouchDown) _Bool _touchDown;

@property(nonatomic, getter=_isTrackingTouch, setter=_setTrackingTouch:) _Bool _trackingTouch; // @synthesize _trackingTouch;

@property(nonatomic, setter=_setLastRingLayerIdentifier:) unsigned long long _lastRingLayerIdentifier; // @synthesize _lastRingLayerIdentifier;

@property(nonatomic, setter=_setNeedsCurrentSpeedRefresh:) _Bool _needsCurrentSpeedRefresh; // @synthesize _needsCurrentSpeedRefresh;

@property(nonatomic, setter=_setNumberOfRipplesForCurrentTouch:) unsigned long long _numberOfRipplesForCurrentTouch; // @synthesize _numberOfRipplesForCurrentTouch;

@property(retain, nonatomic, setter=_setRecentTouchesContextQueue:) NSMutableArray *_recentTouchesContextQueue; // @synthesize _recentTouchesContextQueue;

- (void)_refresh:(id)arg1;

- (id)_reusableRingLayer;

@property(retain, nonatomic, setter=_setReusableRingLayers:) NSMutableArray *_reusableRingLayers; // @synthesize _reusableRingLayers;

- (id)_reusableTouchContextObject;

@property(retain, nonatomic, setter=_setReusableTouchContexts:) NSMutableArray *_reusableTouchContexts; // @synthesize _reusableTouchContexts;

@property(retain, nonatomic, setter=_setRingEnlargementAnimation:) CAAnimation *_ringEnlargementAnimation; // @synthesize _ringEnlargementAnimation;

@property(retain, nonatomic, setter=_setRingLayersByIdentifiers:) NSMutableDictionary *_ringLayersByIdentifiers; // @synthesize _ringLayersByIdentifiers;

@property(retain, nonatomic, setter=_setRingLayersQueue:) NSMutableArray *_ringLayersQueue; // @synthesize _ringLayersQueue;

@property(retain, nonatomic, setter=_setStyleProvider:) id <TKVibrationRecorderStyleProvider> _styleProvider; // @synthesize _styleProvider;

- (void)_startAnimation;

- (void)_stopAnimation;

- (void)_touchBeganAtLocation:(struct CGPoint)arg1;

- (void)_touchEndedAtLocation:(struct CGPoint)arg1;

- (void)_touchMovedToLocation:(struct CGPoint)arg1;

- (void)_updateRingEnlargementAnimation;

- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;

- (void)dealloc;

@property(nonatomic) double fadeOutRadius; // @synthesize fadeOutRadius=_fadeOutRadius;

@property(nonatomic) double fingerMovingSpeed; // @synthesize fingerMovingSpeed=_fingerMovingSpeed;

@property(nonatomic) double fingerStillSpeed; // @synthesize fingerStillSpeed=_fingerStillSpeed;

@property(nonatomic) double firstRippleInitialRadius; // @synthesize firstRippleInitialRadius=_firstRippleInitialRadius;

- (id)init;

- (id)initWithStyleProvider:(id)arg1;

- (void)layoutSubviews;

- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;

- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;

- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;



@end


