/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "ABGroupWrapper.h"


@interface ABGlobalGroupWrapper : ABGroupWrapper

{

}



+ (id)newGlobalGroupWrapperWithAddressBook:(void *)arg1;

- (_Bool)isEqual:(id)arg1;

- (_Bool)isGlobalWrapper;

- (id)name;



@end


