/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "UITableViewDataSource.h"

#import "UITableViewDelegate.h"



@class ABBannerView, ABModel, ABUIPerson, NSMutableArray;



@interface ABMembersDataSource : NSObject <UITableViewDelegate, UITableViewDataSource>

{

    id <ABMembersDataSourceDelegate> _delegate;

    id <ABStyleProvider> _styleProvider;

    void *_addressBook;

    ABModel *_model;

    NSMutableArray *_sectionIndexTitles;

    struct __CFDictionary *_sectionHeaderToSortingIndex;

    struct __CFDictionary *_displayableSectionHeaderToSectionHeader;

    struct __CFDictionary *_sectionHeaderToDisplayableSectionHeader;

    struct __CFDictionary *_displayableSectionIndexToSectionIndex;

    struct __CFDictionary *_sectionIndexToDisplayableSectionIndex;

    ABBannerView *_bannerView;

    ABUIPerson *_meCard;

}



- (void)_invalidateMeCard;

@property(nonatomic) void *addressBook; // @synthesize addressBook=_addressBook;

- (id)bannerView;

- (void)createAllDisplayableSectionIndexAndHeaderCaches;

- (void)dealloc;

@property(nonatomic) id <ABMembersDataSourceDelegate> delegate; // @synthesize delegate=_delegate;

- (id)displayableSectionHeaderFromSectionHeader:(id)arg1;

- (id)displayableSectionIndexFromSectionIndex:(id)arg1;

- (unsigned long long)displayedMemberIndexForIndexPath:(id)arg1 inTableView:(id)arg2;

- (long long)globalRowForBanner;

- (long long)globalRowForDisplayedMemberIndex:(unsigned long long)arg1;

- (id)indexPathForDisplayedMemberIndex:(unsigned long long)arg1 inTableView:(id)arg2;

@property(retain, nonatomic) ABModel *model; // @synthesize model=_model;

- (long long)numberOfSectionsInTableView:(id)arg1;

- (void)scrollViewWillBeginDragging:(id)arg1;

- (struct __CFDictionary *)sectionHeaderSortingIndices;

- (id)sectionIndexFromDisplayableSectionIndex:(id)arg1;

- (id)sectionIndexTitlesForTableView:(id)arg1;

- (void)setBannerView:(id)arg1 inTableView:(id)arg2;

@property(retain, nonatomic) id <ABStyleProvider> styleProvider; // @synthesize styleProvider=_styleProvider;

- (_Bool)shouldShowGroups;

- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;

- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;

- (struct CGRect)tableView:(id)arg1 frameForSectionIndexGivenProposedFrame:(struct CGRect)arg2;

- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;

- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;

- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;

- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;

- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;

- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;

- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3;

- (id)titleForHeaderInSection:(long long)arg1;



@end


