/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "NSProxy.h"



#import "ABPeoplePickerServiceViewControllerProtocol.h"



@class ABPeoplePickerHostViewController, NSMutableArray;



@interface ABPeoplePickerHostViewControllerProxy : NSProxy <ABPeoplePickerServiceViewControllerProtocol>

{

    ABPeoplePickerHostViewController *_hostViewController;

    NSMutableArray *_queuedInvocations;

}



- (void)dealloc;

- (void)forwardInvocation:(id)arg1;

@property(retain, nonatomic) ABPeoplePickerHostViewController *hostViewController;

- (id)init;

- (id)methodSignatureForSelector:(SEL)arg1;



@end


