/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UITableViewCellLayoutManager.h"



@interface ABPersonCellLayoutManager : UITableViewCellLayoutManager

{

    id <ABPersonCellLayoutManagerDelegate> _delegate;

    id <ABStyleProvider> _styleProvider;

}



- (double)accessoryViewInsetForBounds:(struct CGRect)arg1;

- (struct CGRect)backgroundEndingRectForCell:(id)arg1 forNewEditingState:(_Bool)arg2;

- (struct CGRect)backgroundStartingRectForCell:(id)arg1 forNewEditingState:(_Bool)arg2;

- (void)cell:(id)arg1 didTransitionToState:(unsigned long long)arg2;

- (void)cell:(id)arg1 willTransitionToState:(unsigned long long)arg2;

- (id)cellAsMultiCell:(id)arg1;

- (struct CGRect)contentEndingRectForCell:(id)arg1 forNewEditingState:(_Bool)arg2;

- (struct CGRect)contentStartingRectForCell:(id)arg1 forNewEditingState:(_Bool)arg2;

- (void)dealloc;

@property(nonatomic) id <ABPersonCellLayoutManagerDelegate> delegate; // @synthesize delegate=_delegate;

- (struct CGRect)deleteConfirmationRectForCell:(id)arg1;

- (double)deleteConfirmationWidth;

@property(retain, nonatomic) id <ABStyleProvider> styleProvider; // @synthesize styleProvider=_styleProvider;

- (double)widthForCellContentViewInTableView:(id)arg1 whenEditing:(_Bool)arg2 isShowingDeleteConfirmation:(_Bool)arg3 accessoryViewBounds:(struct CGRect)arg4;



@end


