/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIButton.h"



@class UIColor, UIImage;



@interface ABTransportButton : UIButton

{

    long long _transportType;

    UIColor *_glyphColor;

    UIImage *_image;

}



+ (id)transportButton;

- (id)_imageNameForType:(long long)arg1;

- (void)_updateImageWithType:(long long)arg1;

- (struct UIEdgeInsets)alignmentRectInsets;

- (struct CGRect)backgroundRectForBounds:(struct CGRect)arg1;

- (void)dealloc;

@property(retain, nonatomic) UIColor *glyphColor; // @synthesize glyphColor=_glyphColor;

@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;

- (struct CGSize)intrinsicContentSize;

@property(nonatomic) long long transportType; // @synthesize transportType=_transportType;

- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

- (void)tintColorDidChange;



@end


