/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIImage.h"



@interface UIImage (Tinting)

+ (id)ab_imageNamed:(id)arg1;

+ (id)ab_tintedImageNamed:(id)arg1 withTint:(id)arg2;

@end


