/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSArray, SUPurchaseManager;



@interface SUPurchaseBatch : NSObject

{

    NSArray *_continuations;

    NSArray *_errors;

    NSArray *_items;

    NSArray *_offers;

    SUPurchaseManager *_purchaseManager;

    _Bool _shouldSuspendWhenFinished;

    NSArray *_validPurchases;

}



- (id)_copyModifiedErrorsFromDictionary:(struct __CFDictionary *)arg1;

- (id)_copyUniqueErrorsFromErrors:(id)arg1;

- (id)_copyValidPurchasesForItems:(id)arg1;

- (void)_validateItems;

@property(retain, nonatomic) NSArray *continuations; // @synthesize continuations=_continuations;

- (id)copyContinuationsForPurchases:(id)arg1;

- (id)copyFilteredItemsFromItems:(id)arg1;

- (void)dealloc;

- (void *)errorEqualCallback;

@property(retain, nonatomic) NSArray *errors; // @synthesize errors=_errors;

- (id)everythingFailedErrorForError:(id)arg1;

- (id)initWithItems:(id)arg1;

- (id)initWithItems:(id)arg1 offers:(id)arg2;

@property(readonly, nonatomic) NSArray *items; // @synthesize items=_items;

- (id)mergedErrorForError:(id)arg1 withCount:(long long)arg2;

@property(readonly, nonatomic) NSArray *offers; // @synthesize offers=_offers;

@property(nonatomic) __weak SUPurchaseManager *purchaseManager; // @synthesize purchaseManager=_purchaseManager;

- (void)setDocumentTargetIdentifier:(id)arg1;

- (void)setPurchasesAndContinuationsFromPurchases:(id)arg1;

@property(retain, nonatomic) NSArray *validPurchases; // @synthesize validPurchases=_validPurchases;



@end


