/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSString;



@interface SUScriptModalDialogResponse : NSObject

{

    long long _buttonIndex;

    NSString *_textFieldValue;

}



@property(nonatomic) long long buttonIndex; // @synthesize buttonIndex=_buttonIndex;

- (void)dealloc;

@property(retain, nonatomic) NSString *textFieldValue; // @synthesize textFieldValue=_textFieldValue;



@end


