/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class ISURLOperationPool, NSArray, SUImageCache, SUVariableCellConfigurationCache;



@interface SUTableDataSource : NSObject

{

    id _cellReuseSource;

    long long _columnCount;

    SUVariableCellConfigurationCache *_configurationCache;

    long long _preferringUserInteractionCount;

}



- (void)beginPreferringUserInteraction;

- (id)cachedConfigurationForClass:(Class)arg1 index:(long long)arg2;

- (_Bool)canDeleteIndexPath:(id)arg1;

- (_Bool)canDoubleTapIndexPath:(id)arg1;

- (_Bool)canSelectIndexPath:(id)arg1;

- (id)cellContextForConfigurationClass:(Class)arg1;

- (id)cellForIndexPath:(id)arg1;

- (double)cellHeightForIndexPath:(id)arg1;

@property(nonatomic) id cellReuseSource; // @synthesize cellReuseSource=_cellReuseSource;

@property(nonatomic) long long columnCount; // @synthesize columnCount=_columnCount;

- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;

- (void)configurePlaceholderCell:(id)arg1 forIndexPath:(id)arg2;

- (void)dealloc;

- (_Bool)deleteIndexPath:(id)arg1;

- (void)didBeginPreferringUserInteraction;

- (void)didEndPreferringUserInteraction;

- (void)endPreferringUserInteraction;

- (id)headerViewForSection:(long long)arg1;

- (double)heightForFooterInSection:(long long)arg1;

- (double)heightForPlaceholderCells;

@property(readonly, nonatomic) SUImageCache *imageCache;

@property(readonly, nonatomic) ISURLOperationPool *imagePool;

- (id)init;

@property(readonly, nonatomic, getter=isPreferringUserInteraction) _Bool preferringUserInteraction;

- (long long)numberOfColumnsInSection:(long long)arg1;

- (long long)numberOfRowsInSection:(long long)arg1;

@property(readonly, nonatomic) long long numberOfSections;

- (id)placeholderCellForIndexPath:(id)arg1;

- (void)reloadCellContexts;

- (void)reloadData;

- (void)resetCaches;

- (void)resetLayoutCaches;

- (long long)sectionIndexForIndexTitle:(id)arg1 atIndex:(long long)arg2;

@property(readonly, nonatomic) NSArray *sectionIndexTitles;

@property(readonly, nonatomic) long long tableViewStyle;

- (id)titleForDeleteConfirmationForIndexPath:(id)arg1;

- (id)titleForHeaderInSection:(long long)arg1;



@end


