/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSOperationQueue, NSURL;



__attribute__((visibility("hidden")))

@interface LBFSEventsWatcher : NSObject

{

    struct __FSEventStream *_streamRef;

    _Bool _started;

    NSURL *_url;

    NSObject<OS_dispatch_queue> *_eventQueue;

    NSOperationQueue *_messageQueue;

    long long _disableCount;

    NSMutableDictionary *_inodeMap;

    id _updateHandler;

}



- (void)dealloc;

- (void)disableUpdates;

- (void)enableUpdates;

- (id)initWithDirectoryURL:(id)arg1;

- (id)messageForURL:(id)arg1 inode:(long long)arg2 exists:(_Bool)arg3 flags:(unsigned int)arg4;

- (void)processEventForPath:(id)arg1 flags:(unsigned int)arg2;

- (void)scanDirectory:(id)arg1 isGathering:(_Bool)arg2;

- (void)sendMessage:(id)arg1;

@property(copy, nonatomic) id updateHandler; // @synthesize updateHandler=_updateHandler;

- (void)start;

- (void)stop;

@property(readonly) NSURL *url; // @synthesize url=_url;



@end


