/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "DAAction.h"



@interface ASEmailChangeFlagsAction : DAAction

{

    _Bool _read;

    _Bool _flagged;

    unsigned long long _changedFlags;

}



- (void)appendApplicationDataForTask:(id)arg1 toWBXMLData:(id)arg2;

- (id)initWithServerID:(id)arg1 read:(_Bool)arg2 flagged:(_Bool)arg3 changedFlags:(unsigned long long)arg4;



@end


