/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "ASItem.h"


#import "NSCoding.h"



@class NSString;



@interface ASFolder : ASItem <NSCoding>

{

    int _folderType;

    NSString *_serverID;

    NSString *_parentID;

    NSString *_displayName;

    int _changeType;

    _Bool _renameOnCollision;

    int _localID;

}



+ (_Bool)acceptsTopLevelLeaves;

+ (id)asParseRules;

+ (_Bool)frontingBasicTypes;

+ (_Bool)notifyOfUnknownTokens;

+ (_Bool)parsingLeafNode;

+ (_Bool)parsingWithSubItems;

- (id)_folderTypeString;

@property int changeType; // @synthesize changeType=_changeType;

@property(readonly) int dataclass;

- (void)dealloc;

- (id)description;

@property(retain) NSString *displayName; // @synthesize displayName=_displayName;

- (void)encodeWithCoder:(id)arg1;

@property(readonly) int folderType; // @synthesize folderType=_folderType;

- (unsigned long long)hash;

- (id)initWithCoder:(id)arg1;

- (id)initWithFolderType:(int)arg1 serverID:(id)arg2 parentID:(id)arg3 displayName:(id)arg4 localID:(int)arg5;

- (_Bool)isEqual:(id)arg1;

@property(readonly) int localID; // @synthesize localID=_localID;

- (_Bool)mayContainDataclasses:(int)arg1;

@property(retain) NSString *parentID; // @synthesize parentID=_parentID;

- (void)parseASParseContext:(id)arg1 root:(id)arg2 parent:(id)arg3 callbackDict:(id)arg4 streamCallbackDict:(id)arg5 account:(id)arg6;

@property _Bool renameOnCollision; // @synthesize renameOnCollision=_renameOnCollision;

@property(retain) NSString *serverID; // @synthesize serverID=_serverID;

- (void)setFolderTypeNumber:(id)arg1;



@end


