/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "ASItem.h"


@class NSArray, NSData, NSDictionary, NSMutableArray, NSString;



@interface ASGALSearchResult : ASItem

{

    NSDictionary *_applicationData;

    NSString *_longID;

    NSMutableArray *_classes;

    NSMutableArray *_collectionIDs;

    NSString *_phone;

    NSString *_office;

    NSString *_title;

    NSString *_company;

    NSString *_alias;

    NSString *_firstName;

    NSString *_lastName;

    NSString *_homePhone;

    NSString *_mobilePhone;

    NSString *_emailAddress;

    NSData *_photoData;

}



+ (_Bool)acceptsTopLevelLeaves;

+ (id)asParseRules;

+ (_Bool)frontingBasicTypes;

+ (_Bool)notifyOfUnknownTokens;

+ (_Bool)parsingLeafNode;

+ (_Bool)parsingWithSubItems;

- (void)addClass:(id)arg1;

- (void)addCollectionID:(id)arg1;

@property(copy) NSString *alias; // @synthesize alias=_alias;

- (id)applicationData;

@property(retain) NSArray *classes; // @synthesize classes=_classes;

@property(retain) NSArray *collectionIDs; // @synthesize collectionIDs=_collectionIDs;

@property(copy) NSString *company; // @synthesize company=_company;

- (id)convertToDAContactSearchResultElement;

- (void)dealloc;

- (id)description;

@property(copy) NSString *emailAddress; // @synthesize emailAddress=_emailAddress;

@property(copy) NSString *firstName; // @synthesize firstName=_firstName;

@property(copy) NSString *homePhone; // @synthesize homePhone=_homePhone;

@property(copy) NSString *lastName; // @synthesize lastName=_lastName;

@property(retain) NSString *longID; // @synthesize longID=_longID;

@property(copy) NSString *mobilePhone; // @synthesize mobilePhone=_mobilePhone;

@property(copy) NSString *office; // @synthesize office=_office;

- (void)parseASParseContext:(id)arg1 root:(id)arg2 parent:(id)arg3 callbackDict:(id)arg4 streamCallbackDict:(id)arg5 account:(id)arg6;

@property(copy) NSString *phone; // @synthesize phone=_phone;

@property(copy) NSData *photoData; // @synthesize photoData=_photoData;

- (void)postProcessApplicationData;

- (void)setApplicationData:(id)arg1;

@property(copy) NSString *title; // @synthesize title=_title;



@end


