/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "ASSearchTask.h"


@interface ASGALSearchTask : ASSearchTask

{

}



- (void)finishWithError:(id)arg1;

- (_Bool)getTopLevelToken:(char *)arg1 outStatusCodePage:(char *)arg2 outStatusToken:(char *)arg3;

- (int)numDownloadedElements;

- (void)performTask;

- (_Bool)processContext:(id)arg1;

- (id)requestBody;



@end


