/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "ASItem.h"


@class NSArray, NSNumber;



@interface ASSearchResponse : ASItem

{

    NSArray *_stores;

    NSNumber *_status;

    int _expectedResultType;

}



+ (_Bool)acceptsTopLevelLeaves;

+ (id)asParseRules;

+ (_Bool)frontingBasicTypes;

+ (_Bool)notifyOfUnknownTokens;

+ (_Bool)parsingLeafNode;

+ (_Bool)parsingWithSubItems;

- (void)dealloc;

- (id)description;

@property int expectedResultType; // @synthesize expectedResultType=_expectedResultType;

@property(copy) NSNumber *status; // @synthesize status=_status;

@property(retain) NSArray *stores; // @synthesize stores=_stores;



@end


