/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "CNPhoneNumber.h"


@class NSString;



@interface CNMutablePhoneNumber : CNPhoneNumber

{

}



@property(copy, nonatomic) NSString *stringValue; // @dynamic stringValue;



@end


