/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "AVQueueFeeder.h"


@class NSMutableArray;



@interface AVArrayQueueFeeder : AVQueueFeeder

{

    NSMutableArray *_items;

}



- (void)dealloc;

- (id)init;

- (id)initWithArray:(id)arg1;

- (void)insertObject:(id)arg1 atIndex:(unsigned int)arg2;

- (unsigned long long)itemCount;

- (id)itemForIndex:(unsigned long long)arg1;

- (unsigned long long)numberOfPaths;

- (id)pathAtIndex:(unsigned long long)arg1;

- (void)removeObjectAtIndex:(unsigned int)arg1;

- (void)shuffleWithCurrentIndex:(unsigned int)arg1;



@end


