/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NoteContext;



@interface DALocalDBWatcher : NSObject

{

    int _lastSavedCalSequenceNumber;

    int _lastSavedABSequenceNumber;

    void *_abWatcher;

    struct CalDatabase *_calWatcher;

    NoteContext *_noteWatcher;

    struct __CFDictionary *_concernedABPartyToBlockMap;

    struct __CFDictionary *_concernedCalPartyToBlockMap;

    struct __CFDictionary *_concernedNotePartyToBlockMap;

    _Bool _watchingBookmarks;

    struct __CFDictionary *_concernedBookmarkPartyToBlockMap;

}



+ (id)sharedDBWatcher;

- (void)_handleABChangeNotificationWithInfo:(id)arg1;

- (void)_handleBookmarkChangeNotification;

- (void)_handleCalChangeNotification;

- (void)_notesChangedExternally:(id)arg1;

- (void)dealloc;

- (id)init;

@property int lastSavedABSequenceNumber; // @synthesize lastSavedABSequenceNumber=_lastSavedABSequenceNumber;

@property int lastSavedCalSequenceNumber; // @synthesize lastSavedCalSequenceNumber=_lastSavedCalSequenceNumber;

- (void)noteABDBDirChanged;

- (void)noteCalDBDirChanged;

- (void)registerConcernedABParty:(id)arg1 withChangedBlock:(id)arg2;

- (void)registerConcernedBookmarkParty:(id)arg1 withChangedBlock:(id)arg2;

- (void)registerConcernedCalParty:(id)arg1 withChangedBlock:(id)arg2;

- (void)registerConcernedNoteParty:(id)arg1 withChangedBlock:(id)arg2;

- (void)removeConcernedABParty:(id)arg1;

- (void)removeConcernedBookmarkParty:(id)arg1;

- (void)removeConcernedCalParty:(id)arg1;

- (void)removeConcernedNoteParty:(id)arg1;



@end


