/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "GKInternalRepresentation.h"


@class GKPlayerInternal, NSDate, NSString;



@interface GKTurnBasedParticipantInternal : GKInternalRepresentation

{

    NSString *_sessionID;

    GKPlayerInternal *_player;

    GKPlayerInternal *_invitedBy;

    NSString *_inviteMessage;

    NSString *_status;

    NSDate *_lastTurnDate;

    NSDate *_timeoutDate;

    unsigned int _matchOutcome;

    unsigned char _slot;

}



+ (id)secureCodedPropertyKeys;

- (void)dealloc;

- (unsigned long long)hash;

@property(retain, nonatomic) NSString *inviteMessage; // @synthesize inviteMessage=_inviteMessage;

@property(retain, nonatomic) GKPlayerInternal *invitedBy; // @synthesize invitedBy=_invitedBy;

- (_Bool)isEqual:(id)arg1;

@property(retain, nonatomic) NSDate *lastTurnDate; // @synthesize lastTurnDate=_lastTurnDate;

@property(nonatomic) unsigned int matchOutcome; // @synthesize matchOutcome=_matchOutcome;

@property(retain, nonatomic) GKPlayerInternal *player; // @synthesize player=_player;

@property(readonly, nonatomic) NSString *playerID;

- (id)serverRepresentation;

@property(retain, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;

@property(nonatomic) unsigned char slot; // @synthesize slot=_slot;

@property(retain, nonatomic) NSString *status; // @synthesize status=_status;

@property(retain, nonatomic) NSDate *timeoutDate; // @synthesize timeoutDate=_timeoutDate;



@end


