/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIViewController.h"



#import "PKGroupsControllerDelegate.h"

#import "PKPassGroupStackViewDatasource.h"

#import "PKPassGroupStackViewDelegate.h"

#import "PKServiceAddPassesViewControllerProtocol.h"

#import "UIScrollViewDelegate.h"



@class NSArray, NSMutableArray, NSMutableData, NSURLConnection, PKGroupsController, PKPassGroupStackView, UINavigationBar, UIProgressView;



@interface PKServiceAddPassesViewController : UIViewController <PKPassGroupStackViewDelegate, PKPassGroupStackViewDatasource, PKGroupsControllerDelegate, UIScrollViewDelegate, PKServiceAddPassesViewControllerProtocol>

{

    NSURLConnection *_downloadPassURLConnection;

    long long _downloadPassExpectedBytes;

    NSMutableData *_downloadPassData;

    _Bool _allowsPassIngestion;

    _Bool _alreadyAdding;

    _Bool _haveStartedCardAnimation;

    _Bool _viewAppeared;

    int _presentationState;

    NSMutableArray *_localPasses;

    NSArray *_localPassDatas;

    UINavigationBar *_navigationBar;

    PKPassGroupStackView *_cardStackView;

    PKGroupsController *_groupsController;

    NSMutableArray *_minimumCardHeightFromHereToTop;

    UIProgressView *_progressView;

}



+ (id)_exportedInterface;

+ (_Bool)_preventsAppearanceProxyCustomization;

+ (id)_remoteViewControllerInterface;

- (void)acceptCard:(id)arg1;

- (void)animateInCardIfNeeded;

- (void)cancelCard:(id)arg1;

@property(retain, nonatomic) PKPassGroupStackView *cardStackView; // @synthesize cardStackView=_cardStackView;

- (void)connection:(id)arg1 didFailWithError:(id)arg2;

- (void)connection:(id)arg1 didReceiveData:(id)arg2;

- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;

- (void)connectionDidFinishLoading:(id)arg1;

- (void)dealloc;

- (id)genericTitleWithCount:(unsigned long long)arg1;

- (id)groupAtIndex:(unsigned long long)arg1;

- (double)groupHeightAtIndex:(unsigned long long)arg1;

- (void)groupStackView:(id)arg1 deleteConfirmedForPass:(id)arg2;

- (void)groupStackView:(id)arg1 didAnimateToState:(int)arg2;

- (void)groupStackViewDidBeginReordering:(id)arg1;

- (void)groupStackViewDidEndReordering:(id)arg1;

@property(retain, nonatomic) PKGroupsController *groupsController; // @synthesize groupsController=_groupsController;

- (void)groupsController:(id)arg1 didInsertGroup:(id)arg2 atIndex:(unsigned long long)arg3;

- (void)groupsController:(id)arg1 didMoveGroup:(id)arg2 fromIndex:(unsigned long long)arg3 toIndex:(unsigned long long)arg4;

- (void)groupsController:(id)arg1 didRemoveGroup:(id)arg2 atIndex:(unsigned long long)arg3;

@property(nonatomic) _Bool haveStartedCardAnimation; // @synthesize haveStartedCardAnimation=_haveStartedCardAnimation;

- (unsigned long long)indexOfGroup:(id)arg1;

- (void)ingestCardAtURL:(id)arg1;

- (void)ingestPasses:(id)arg1;

- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

- (void)loadGroups;

- (void)loadView;

@property(retain, nonatomic) NSArray *localPassDatas; // @synthesize localPassDatas=_localPassDatas;

@property(retain, nonatomic) NSMutableArray *localPasses; // @synthesize localPasses=_localPasses;

@property(retain, nonatomic) NSMutableArray *minimumCardHeightFromHereToTop; // @synthesize minimumCardHeightFromHereToTop=_minimumCardHeightFromHereToTop;

@property(retain) UINavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;

- (unsigned long long)numberOfGroups;

- (_Bool)passesGrowWhenFlipped;

@property(nonatomic) int presentationState; // @synthesize presentationState=_presentationState;

@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;

- (void)setAllowsPassIngestion:(_Bool)arg1;

@property(nonatomic) _Bool viewAppeared; // @synthesize viewAppeared=_viewAppeared;

- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;

- (void)showDownloadingPassUI;

- (id)styleTitleUsingPass:(id)arg1 count:(unsigned long long)arg2;

- (unsigned long long)supportedInterfaceOrientations;

- (long long)suppressedContent;

- (void)tearDown;

- (void)tearDownDownloadConnection;

- (void)updateAddButton;

- (void)updateAddButtonAndSettings;

- (void)updateCancelButton;

- (void)updateNavTitle;

- (void)viewDidAppear:(_Bool)arg1;

- (void)viewDidDisappear:(_Bool)arg1;



@end


