/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class ASAsset, NSAttributedString, NSString;



__attribute__((visibility("hidden")))

@interface _UIDefinitionValue : NSObject

{

    NSString *_localizedDictionaryName;

    NSString *_term;

    NSAttributedString *_definition;

    NSString *_longDefinition;

    ASAsset *_rawAsset;

}



- (void)dealloc;

@property(readonly) NSAttributedString *definition; // @synthesize definition=_definition;

- (id)description;

- (id)initWithLocalizedDictionaryName:(id)arg1 term:(id)arg2 definition:(id)arg3 longDefinition:(id)arg4;

@property(readonly) NSString *localizedDictionaryName; // @synthesize localizedDictionaryName=_localizedDictionaryName;

@property(readonly) NSString *longDefinition; // @synthesize longDefinition=_longDefinition;

@property(retain, nonatomic) ASAsset *rawAsset; // @synthesize rawAsset=_rawAsset;

@property(readonly) NSString *term; // @synthesize term=_term;



@end


