/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSArray, NSAttributedString, NSMutableArray, NSString, UITextInputTraits, UIView, UIViewController, _UIModalItemBackgroundView, _UIModalItemContentView, _UIModalItemRepresentationView;



@interface _UIModalItem : NSObject

{

    NSString *_title;

    NSString *_message;

    NSString *_cancelButtonTitle;

    NSString *_defaultButtonTitle;

    NSAttributedString *_titleAttributedString;

    NSAttributedString *_messageAttributedString;

    NSString *_subtitleString;

    long long _titleMaxLineNumber;

    long long _messageMaxLineNumber;

    long long _numberOfButtonsRows;

    _Bool _useUndoStyle;

    _Bool _useWifiPickerLayout;

    _Bool _textFieldsHidden;

    _Bool _dontUpdateFrameForKBChanges;

    NSMutableArray *_otherButtonsTitles;

    long long _itemType;

    id <UIModalItemDelegate> _delegate;

    id _completionBlock;

    long long _modalItemInputStyle;

    UIView *_popoverTargetView;

    struct CGRect _popoverTargetRect;

    UIViewController *_contentViewController;

    struct CGSize _contentViewControllerSize;

    long long _presentAnimationType;

    long long _dismissAnimationType;

    _Bool _isPresented;

    _Bool _isVisible;

    _Bool _isBeingDismissed;

    _Bool _isHidden;

    UIViewController *_viewController;

    UIViewController *_hostingViewController;

    UIViewController *_anchorViewController;

    long long _defaultButtonIndex;

    long long _cancelButtonIndex;

    _UIModalItemContentView *_contentView;

    _UIModalItemBackgroundView *_backgroundView;

    _UIModalItemRepresentationView *_representedView;

    NSString *_loginString;

    NSString *_passwordString;

    NSString *_loginPlaceholderString;

    NSString *_passwordPlaceholderString;

    UITextInputTraits *_passwordTraits;

    UITextInputTraits *_loginTraits;

    _Bool _enableFirstOtherButton;

    _Bool _forceVerticalLayout;

    long long _dismissIndex;

    long long cancelButtonIndex;

    NSArray *_buttonTitles;

}



+ (id)modalItemWithType:(long long)arg1 title:(id)arg2 message:(id)arg3 buttonTitles:(id)arg4 completion:(id)arg5;

- (id)_anchorViewController;

- (id)_backgroundView;

- (id)_cancelButtonTitle;

- (id)_contentView;

- (id)_defaultButtonTitle;

- (id)_hostingViewController;

- (void)_loginFieldTextDidChange;

- (id)_loginTraits;

- (double)_maxHeight;

- (double)_maxWidth;

- (id)_otherButtonsTitles;

- (void)_passwordFieldTextDidChange;

- (id)_passwordTraits;

- (id)_popoverBackgroundView;

- (id)_representedView;

- (void)_setAnchorViewController:(id)arg1;

- (void)_setHostingViewController:(id)arg1;

- (void)_setRepresentedView:(id)arg1;

@property(retain, nonatomic, getter=_viewController, setter=_setViewController:) UIViewController *_viewController;

- (id)_typeKey;

- (void)_updateContentView;

- (long long)addButtonWithTitle:(id)arg1;

@property(retain, nonatomic) _UIModalItemBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;

- (id)buttonTitleAtIndex;

@property(copy, nonatomic) NSArray *buttonTitles; // @synthesize buttonTitles=_buttonTitles;

@property(nonatomic) long long cancelButtonIndex; // @synthesize cancelButtonIndex;

@property(retain, nonatomic) _UIModalItemContentView *contentView; // @synthesize contentView=_contentView;

@property(retain, nonatomic) UIViewController *contentViewController; // @synthesize contentViewController=_contentViewController;

@property(nonatomic) struct CGSize contentViewControllerSize; // @synthesize contentViewControllerSize=_contentViewControllerSize;

- (void)dealloc;

@property(nonatomic) long long defaultButtonIndex; // @synthesize defaultButtonIndex=_defaultButtonIndex;

@property(nonatomic) id <UIModalItemDelegate> delegate; // @synthesize delegate=_delegate;

@property(nonatomic) long long dismissAnimationType; // @synthesize dismissAnimationType=_dismissAnimationType;

@property(nonatomic) long long dismissIndex; // @synthesize dismissIndex=_dismissIndex;

@property(nonatomic) _Bool dontUpdateFrameForKBChanges; // @synthesize dontUpdateFrameForKBChanges=_dontUpdateFrameForKBChanges;

@property(nonatomic) _Bool enableFirstOtherButton; // @synthesize enableFirstOtherButton=_enableFirstOtherButton;

@property(nonatomic) _Bool forceVerticalLayout; // @synthesize forceVerticalLayout=_forceVerticalLayout;

- (id)initWithTitle:(id)arg1 message:(id)arg2 otherButtonTitles:(id)arg3 completion:(id)arg4 delegate:(void)arg5;

@property(nonatomic) _Bool isBeingDismissed; // @synthesize isBeingDismissed=_isBeingDismissed;

@property(nonatomic) _Bool isHidden; // @synthesize isHidden=_isHidden;

@property(readonly) _Bool isPresented; // @synthesize isPresented=_isPresented;

@property(copy, nonatomic) NSString *loginPlaceholderString; // @synthesize loginPlaceholderString=_loginPlaceholderString;

@property(copy, nonatomic) NSString *loginString; // @synthesize loginString=_loginString;

@property(copy, nonatomic) NSString *message; // @synthesize message=_message;

@property(copy, nonatomic) NSAttributedString *messageAttributedString; // @synthesize messageAttributedString=_messageAttributedString;

@property(nonatomic) long long messageMaxLineNumber; // @synthesize messageMaxLineNumber=_messageMaxLineNumber;

@property(nonatomic) long long modalItemInputStyle; // @synthesize modalItemInputStyle=_modalItemInputStyle;

@property(nonatomic) long long numberOfButtonsRows; // @synthesize numberOfButtonsRows=_numberOfButtonsRows;

@property(copy, nonatomic) NSString *passwordPlaceholderString; // @synthesize passwordPlaceholderString=_passwordPlaceholderString;

@property(copy, nonatomic) NSString *passwordString; // @synthesize passwordString=_passwordString;

@property(nonatomic) long long presentAnimationType; // @synthesize presentAnimationType=_presentAnimationType;

- (void)refreshButtonTitle;

@property(copy, nonatomic) NSString *subtitleString; // @synthesize subtitleString=_subtitleString;

@property(nonatomic) struct CGRect targetRect; // @synthesize targetRect=_popoverTargetRect;

@property(nonatomic) UIView *targetView; // @synthesize targetView=_popoverTargetView;

@property(nonatomic) _Bool textFieldsHidden; // @synthesize textFieldsHidden=_textFieldsHidden;

@property(copy, nonatomic) NSString *title; // @synthesize title=_title;

@property(copy, nonatomic) NSAttributedString *titleAttributedString; // @synthesize titleAttributedString=_titleAttributedString;

@property(nonatomic) long long titleMaxLineNumber; // @synthesize titleMaxLineNumber=_titleMaxLineNumber;

@property(nonatomic) long long type; // @synthesize type=_itemType;

@property(nonatomic) _Bool useUndoStyle; // @synthesize useUndoStyle=_useUndoStyle;

@property(nonatomic) _Bool useWifiPickerLayout; // @synthesize useWifiPickerLayout=_useWifiPickerLayout;

- (id)textFieldAtIndex:(long long)arg1;

@property(readonly, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;



@end


