/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIViewController.h"


@class UIWindow;



@interface _UIModalItemAppViewController : UIViewController

{

    UIWindow *_rotationDelegate;

}



- (void)dealloc;

- (long long)preferredInterfaceOrientationForPresentation;

@property(retain, nonatomic) UIWindow *rotationDelegate; // @synthesize rotationDelegate=_rotationDelegate;

- (_Bool)shouldAutorotate;

- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;

- (unsigned long long)supportedInterfaceOrientations;



@end


