/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





__attribute__((visibility("hidden")))

@interface _UIObjectPerScreen : NSObject

{

}



+ (id)objectOfClass:(Class)arg1 forScreen:(id)arg2 withOptions:(id)arg3 createIfNecessary:(_Bool)arg4;

+ (void)removeObjectsOfClass:(Class)arg1;

+ (void)screenDisconnected:(id)arg1;



@end


