/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@protocol _UIPeripheralHostCustomTransition <NSObject>

- (void)computeTransition:(id)arg1 forHost:(id)arg2;

@end


