/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSMutableArray;



__attribute__((visibility("hidden")))

@interface _UIQueueingServiceWebViewControllerProxy : NSObject

{

    NSMutableArray *_queuedInvocations;

    id _serviceViewControllerProxy;

    id <_UIQueueingServiceWebViewControllerProxyDelegate> _delegate;

}



- (void)dealloc;

@property(nonatomic) id <_UIQueueingServiceWebViewControllerProxyDelegate> delegate; // @synthesize delegate=_delegate;

- (void)forwardInvocation:(id)arg1;

- (id)init;

- (id)methodSignatureForSelector:(SEL)arg1;

@property(retain, nonatomic) id serviceViewControllerProxy; // @synthesize serviceViewControllerProxy=_serviceViewControllerProxy;



@end


