/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIView.h"


@interface _UIReflectingView : UIView

{

    UIView *_containerView;

    UIView *_gradientView;

    double _reflectionAlpha;

}



- (id)_gradientLayer;

- (void)_updateGradientColors;

@property(readonly, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;

- (id)initWithFrame:(struct CGRect)arg1;

- (void)layoutSubviews;

@property(nonatomic) double reflectionAlpha;

@property(nonatomic) double reflectionFraction;

- (void)setBackgroundColor:(id)arg1;

- (void)setFrame:(struct CGRect)arg1;



@end


