/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "_UIRefreshControlContentView.h"


@class UILabel, UIView, _UIRefreshControlModernReplicatorView;



__attribute__((visibility("hidden")))

@interface _UIRefreshControlModernContentView : _UIRefreshControlContentView

{

    _Bool _animationsAreValid;

    UIView *_replicatorContainer;

    _UIRefreshControlModernReplicatorView *_replicatorView;

    UIView *_seed;

    _Bool _hasFinishedRevealing;

    UILabel *_textLabel;

    _Bool _areAnimationsValid;

    double _currentPopStiffness;

}



- (void)_cleanUpAfterRevealing;

- (double)_currentTimeOffset;

- (double)_effectiveScrollViewHeight;

- (id)_effectiveTintColor;

- (id)_effectiveTintColorWithAlpha:(double)arg1;

- (void)_goAway;

- (double)_heightAtWhichNoneOfTheInterfaceElementsAreVisibleEvenIfTheControlIsStillPartiallyOnScreen;

- (double)_percentageShowing;

- (void)_resetToRevealingState;

- (void)_reveal;

- (void)_setSpunAppearance;

- (void)_snappingMagic;

- (void)_spin;

- (void)_tick;

- (void)_tickDueToProgrammaticRefresh;

- (void)_updateTimeOffsetOfRelevantLayers;

@property(nonatomic) _Bool areAnimationsValid; // @synthesize areAnimationsValid=_areAnimationsValid;

- (id)attributedTitle;

@property(nonatomic) double currentPopStiffness; // @synthesize currentPopStiffness=_currentPopStiffness;

- (void)dealloc;

- (void)didTransitionFromState:(int)arg1 toState:(int)arg2;

- (id)initWithFrame:(struct CGRect)arg1;

- (void)layoutSubviews;

- (double)maximumSnappingHeight;

- (void)setAttributedTitle:(id)arg1;

- (void)setTintColor:(id)arg1;

- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

- (long long)style;

@property(readonly, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;

- (void)willTransitionFromState:(int)arg1 toState:(int)arg2;



@end


