/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





__attribute__((visibility("hidden")))

@interface _UIViewAnimationDelegate : NSObject

{

    id _completionBlock;

}



- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;

- (void)dealloc;

- (id)initWithCompletionBlock:(id)arg1;



@end


