/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIAlertButton.h"


@class UILabel;



__attribute__((visibility("hidden")))

@interface UIAlertLabeledButton : UIAlertButton

{

    UILabel *_typeLabel;

    double _titleOffset;

}



- (void)dealloc;

- (void)layoutSubviews;

@property(nonatomic) double titleOffset; // @synthesize titleOffset=_titleOffset;

@property(readonly, nonatomic) UILabel *typeLabel;



@end


