/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UICollectionViewLayoutInvalidationContext.h"


@interface UICollectionViewFlowLayoutInvalidationContext : UICollectionViewLayoutInvalidationContext

{

    struct {

        unsigned int invalidateDelegateMetrics:1;

        unsigned int invalidateAttributes:1;

    } _flowLayoutInvalidationFlags;

}



- (id)init;

@property(nonatomic) _Bool invalidateFlowLayoutAttributes;

@property(nonatomic) _Bool invalidateFlowLayoutDelegateMetrics;



@end


