/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSString, NSTimer;



__attribute__((visibility("hidden")))

@interface UIDelayedAction : NSObject

{

    id m_target;

    SEL m_action;

    id m_userInfo;

    double m_delay;

    NSTimer *m_timer;

    _Bool m_canceled;

    NSString *m_runLoopMode;

}



- (void)cancel;

- (void)dealloc;

- (double)delay;

- (id)initWithTarget:(id)arg1 action:(SEL)arg2 userInfo:(id)arg3 delay:(double)arg4;

- (id)initWithTarget:(id)arg1 action:(SEL)arg2 userInfo:(id)arg3 delay:(double)arg4 mode:(id)arg5;

- (_Bool)scheduled;

- (void)setTarget:(id)arg1;

- (id)target;

- (void)timerFired:(id)arg1;

- (void)touch;

- (void)touchWithDelay:(double)arg1;

- (void)unschedule;

- (id)userInfo;



@end


