/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSString;



@protocol UIKBCacheableView <NSObject>

@property(readonly, nonatomic) _Bool cacheDeferable;

@property(readonly, nonatomic) NSString *cacheKey;

- (id)cacheKeysForRenderFlags:(id)arg1;

@property(readonly, nonatomic) double cachedWidth;

@property(readonly, nonatomic) _Bool keepNonPersistent;



@optional

- (void)drawContentsOfRenderers:(id)arg1;

@end


