/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIKBKeyView.h"


__attribute__((visibility("hidden")))

@interface UIKBCandidateGapView : UIKBKeyView

{

}



- (id)cacheKey;

- (id)cacheKeysForRenderFlags:(id)arg1;

- (void)drawRect:(struct CGRect)arg1;

- (id)initWithFrame:(struct CGRect)arg1 keyplane:(id)arg2;

- (_Bool)shouldCache;



@end


