/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIViewController.h"


#import "UICollectionViewDataSource.h"

#import "UIKeyboardCandidateGridLayoutDelegate.h"

#import "UIKeyboardCandidateList.h"



@class NSArray, TIKeyboardCandidateResultSet, UIButton, UIKBCandidateCollectionView, UIKeyboardCandidateGridCollectionView, UIKeyboardCandidateGridLayout, UIView;



__attribute__((visibility("hidden")))

@interface UIKeyboardCandidateGridCollectionViewController : UIViewController <UICollectionViewDataSource, UIKeyboardCandidateList, UIKeyboardCandidateGridLayoutDelegate>

{

    _Bool _alwaysShowExtensionCandidates;

    _Bool _hasSecondaryCandidates;

    _Bool _showHiddenCandidatesOnly;

    _Bool _showsExtensionCandidates;

    _Bool _supportsNumberKeySelection;

    _Bool _secondaryCandidatesViewIsCurrent;

    int _candidatesVisualStyle;

    id <UIKeyboardCandidateGridCollectionViewControllerDelegate> _delegate;

    id <UIKeyboardCandidateListDelegate> _candidateListDelegate;

    TIKeyboardCandidateResultSet *_candidateSet;

    NSArray *_candidateGroups;

    double _rowHeight;

    CDStruct_961fb75c _visualStyling;

    UIButton *_padInlineFloatingArrowButton;

    UIView *_headerView;

    UIKBCandidateCollectionView *_secondaryCandidatesView;

    double _groupBarWidth;

}



@property(nonatomic) _Bool alwaysShowExtensionCandidates; // @synthesize alwaysShowExtensionCandidates=_alwaysShowExtensionCandidates;

- (void)candidateAcceptedAtIndex:(unsigned long long)arg1;

- (id)candidateAtIndexPath:(id)arg1;

@property(retain, nonatomic) NSArray *candidateGroups; // @synthesize candidateGroups=_candidateGroups;

- (unsigned long long)candidateIndexOffset;

@property(nonatomic) id <UIKeyboardCandidateListDelegate> candidateListDelegate; // @synthesize candidateListDelegate=_candidateListDelegate;

@property(retain, nonatomic) TIKeyboardCandidateResultSet *candidateSet; // @synthesize candidateSet=_candidateSet;

- (void)candidatesDidChange;

@property(nonatomic) int candidatesVisualStyle; // @synthesize candidatesVisualStyle=_candidatesVisualStyle;

@property(readonly, nonatomic) UIKeyboardCandidateGridCollectionView *collectionView;

- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;

- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;

- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;

- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;

- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;

- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;

@property(readonly, nonatomic) UIKeyboardCandidateGridLayout *collectionViewGridLayout;

- (id)currentCandidate;

- (unsigned long long)currentIndex;

- (void)dealloc;

@property(nonatomic) id <UIKeyboardCandidateGridCollectionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;

- (id)firstCandidateIndexPath;

- (id)firstCandidateIndexPathInGroupAtIndex:(unsigned long long)arg1;

- (id)groupAtIndex:(unsigned long long)arg1;

@property(nonatomic) double groupBarWidth; // @synthesize groupBarWidth=_groupBarWidth;

- (unsigned long long)groupsCount;

- (_Bool)handleNumberKey:(unsigned long long)arg1;

- (_Bool)hasCandidates;

@property(readonly, nonatomic) _Bool hasGroupBar;

- (_Bool)hasNextPage;

- (_Bool)hasPreviousPage;

@property(nonatomic) _Bool hasSecondaryCandidates; // @synthesize hasSecondaryCandidates=_hasSecondaryCandidates;

@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;

- (id)indexPathForCandidate:(id)arg1;

- (id)init;

- (_Bool)isExtendedList;

- (_Bool)isHiddenCandidatesList;

- (id)keyboardBehaviors;

- (id)lastCandidateIndexPath;

- (id)lastCandidateIndexPathInGroupAtIndex:(unsigned long long)arg1;

- (void)layout;

- (void)loadSecondaryCandidatesView;

- (void)loadView;

- (long long)numberOfSectionsInCollectionView:(id)arg1;

@property(readonly, nonatomic) UIButton *padInlineFloatingArrowButton; // @synthesize padInlineFloatingArrowButton=_padInlineFloatingArrowButton;

- (void)padInlineFloatingExpand;

- (_Bool)padInlineFloatingIsExpanded;

- (unsigned long long)padInlineHighlightedRowIndex;

- (void)reloadData;

- (void)revealHiddenCandidates;

@property(nonatomic) double rowHeight; // @synthesize rowHeight=_rowHeight;

- (unsigned long long)rowIndexForCellAtIndexPath:(id)arg1;

- (struct CGSize)rowSizeForGridLayout;

- (void)scrollToBottomWithAnimation:(_Bool)arg1;

- (void)scrollToTopWithAnimation:(_Bool)arg1;

- (void)scrollToTopWithAnimation:(_Bool)arg1 revealHeaderView:(_Bool)arg2;

- (void)scrollViewDidScroll:(id)arg1;

- (void)scrollViewIndexChanged:(id)arg1;

- (void)scrollViewWillBeginDragging:(id)arg1;

@property(retain, nonatomic) UIKBCandidateCollectionView *secondaryCandidatesView; // @synthesize secondaryCandidatesView=_secondaryCandidatesView;

@property(nonatomic) _Bool secondaryCandidatesViewIsCurrent; // @synthesize secondaryCandidatesViewIsCurrent=_secondaryCandidatesViewIsCurrent;

- (id)selectedItemIndexPath;

- (unsigned long long)selectedSortIndex;

- (void)setCandidates:(id)arg1 inlineText:(id)arg2 inlineRect:(struct CGRect)arg3 maxX:(double)arg4 layout:(_Bool)arg5;

@property(nonatomic) _Bool showHiddenCandidatesOnly; // @synthesize showHiddenCandidatesOnly=_showHiddenCandidatesOnly;

@property(nonatomic) _Bool showsExtensionCandidates; // @synthesize showsExtensionCandidates=_showsExtensionCandidates;

@property(nonatomic) _Bool supportsNumberKeySelection; // @synthesize supportsNumberKeySelection=_supportsNumberKeySelection;

- (void)setUIKeyboardCandidateListDelegate:(id)arg1;

@property(nonatomic) CDStruct_961fb75c visualStyling; // @synthesize visualStyling=_visualStyling;

- (void)showCandidate:(id)arg1;

- (void)showCandidateAtIndex:(unsigned long long)arg1;

- (void)showNextCandidate;

- (void)showNextPage;

- (void)showNextRow;

- (void)showPreviousCandidate;

- (void)showPreviousPage;

- (void)showPreviousRow;

- (id)statisticsIdentifier;

- (void)stepOneLine:(_Bool)arg1;

- (void)updateHeaderView;

- (void)updateIndexTitles;

- (void)viewDidLoad;



@end


