/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIView.h"


@class NSArray, UIImageView;



__attribute__((visibility("hidden")))

@interface UIMovieScrubberEditingView : UIView

{

    UIImageView *_leftImageView;

    UIImageView *_middleImageView;

    UIImageView *_rightImageView;

    NSArray *_activeImages;

    NSArray *_activeNoEditImages;

    NSArray *_inactiveImages;

    _Bool _enabled;

    _Bool _editing;

    double _edgeInset;

}



- (double)_bounceValueForFraction:(double)arg1;

- (id)_handleImages;

- (struct CGRect)_leftHandleRect;

- (struct CGRect)_rightHandleRect;

- (void)_updateHandleImages;

- (void)bounce;

- (void)dealloc;

@property(nonatomic) double edgeInset; // @synthesize edgeInset=_edgeInset;

- (int)handleForPoint:(struct CGPoint)arg1 hitOffset:(double *)arg2;

- (id)initWithFrame:(struct CGRect)arg1;

@property(nonatomic, getter=isEditing) _Bool editing; // @synthesize editing=_editing;

@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;

- (void)layoutSubviews;

- (_Bool)pointInsideLeftHandle:(struct CGPoint)arg1;

- (_Bool)pointInsideRightHandle:(struct CGPoint)arg1;



@end


