/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIView.h"


@class UILabel, UINavigationBar;



__attribute__((visibility("hidden")))

@interface UINavBarPrompt : UIView

{

    UILabel *_label;

    UINavigationBar *_navBar;

}



- (struct CGRect)_labelFrame;

- (struct CGSize)_updateLabelTextColorAndFontReturningShadowOffset;

- (struct CGSize)_updateLabelTextColorAndFontReturningShadowOffset_legacy;

- (void)clearWeakReference:(id)arg1;

- (void)dealloc;

- (id)initWithPrompt:(id)arg1 navBar:(id)arg2;

- (void)layoutSubviews;

- (id)prompt;

- (struct CGRect)promptBounds;

- (void)setPrompt:(id)arg1;



@end


