/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIStatusBarNewUIForegroundStyleAttributes.h"


__attribute__((visibility("hidden")))

@interface UIStatusBarExternalForegroundStyleAttributes : UIStatusBarNewUIForegroundStyleAttributes

{

}



- (long long)activityIndicatorStyleWithSyncActivity:(_Bool)arg1;

- (double)batteryAccessoryMargin;

- (struct UIEdgeInsets)edgeInsetsForBatteryInsides;

- (struct UIEdgeInsets)edgeInsetsForBluetoothBatteryInsides;

- (double)edgePadding;

- (id)expandedNameForImageName:(id)arg1;

- (id)homeImageName;

- (id)makeTextFontForStyle:(long long)arg1;

- (double)scale;

- (double)standardPadding;

- (double)textOffsetForStyle:(long long)arg1;



@end


