/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class UITableViewCell, UITableViewCellDeleteConfirmationControl_Legacy, UITableViewCellEditControl, UITableViewCellReorderControl, UIView;



__attribute__((visibility("hidden")))

@interface UITableViewCellEditingData : NSObject

{

    UITableViewCell *_cell;

    long long _editingStyle;

    UITableViewCellEditControl *_editControl;

    UITableViewCellReorderControl *_reorderControl;

    UITableViewCellDeleteConfirmationControl_Legacy *_deleteConfirmationControl;

    UIView *_reorderSeparatorView;

}



- (void)dealloc;

- (id)deleteConfirmationControl:(_Bool)arg1;

- (id)editControl:(_Bool)arg1;

- (id)initWithTableViewCell:(id)arg1 editingStyle:(long long)arg2;

@property(readonly, nonatomic, getter=isDataRequired) _Bool dataRequired;

- (id)reorderControl:(_Bool)arg1;

- (id)reorderSeparatorView:(_Bool)arg1;



@end


