/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIGestureRecognizer.h"


@class UIView;



__attribute__((visibility("hidden")))

@interface UITableViewCellDeleteConfirmationGestureRecognizer : UIGestureRecognizer

{

    UIView *_excludedView;

}



- (id)initWithTarget:(id)arg1 action:(SEL)arg2 excludedView:(id)arg3;

- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;



@end


