/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "NSCoding.h"



@class NSArray, NSMutableArray, NSMutableSet;



__attribute__((visibility("hidden")))

@interface UITapRecognizer : NSObject <NSCoding>

{

    unsigned long long _numberOfTouchesRequired;

    unsigned long long _numberOfTapsRequired;

    NSMutableSet *_activeTouches;

    int _currentNumberOfTouches;

    int _currentNumberOfTaps;

    struct CGPoint _location;

    struct CGPoint _startPoint;

    double _allowableMovement;

    double _maximumSingleTapDuration;

    double _maximumIntervalBetweenSuccessiveTaps;

    NSMutableArray *_touches;

    id _delegate;

    unsigned int _timerOn:1;

    unsigned int _noNewTouches:1;

}



- (void)_beginInteraction;

- (double)_effectiveAllowableMovement;

- (void)_interactionEndedTouch:(_Bool)arg1;

- (struct CGPoint)_locationOnScreen;

- (void)_physicalButtonsBegan:(id)arg1 withEvent:(id)arg2;

- (void)_physicalButtonsCancelled:(id)arg1 withEvent:(id)arg2;

- (void)_physicalButtonsEnded:(id)arg1 withEvent:(id)arg2;

- (void)_reset;

@property(nonatomic) double allowableMovement;

- (void)clearTapTimer;

- (void)dealloc;

@property(nonatomic) id <UITapRecognizerDelegate> delegate; // @synthesize delegate=_delegate;

- (void)encodeWithCoder:(id)arg1;

- (id)init;

- (id)initWithCoder:(id)arg1;

- (struct CGPoint)locationInView:(id)arg1;

@property(nonatomic) double maximumIntervalBetweenSuccessiveTaps;

@property(nonatomic) double maximumSingleTapDuration;

@property(nonatomic) unsigned long long numberOfTapsRequired; // @synthesize numberOfTapsRequired=_numberOfTapsRequired;

@property(nonatomic) unsigned long long numberOfTouchesRequired; // @synthesize numberOfTouchesRequired=_numberOfTouchesRequired;

- (void)startTapTimer:(double)arg1;

- (void)tooSlow:(id)arg1;

@property(readonly, nonatomic) NSArray *touches; // @synthesize touches=_touches;

- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;

- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;

- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;



@end


