/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "_UIRotatingActionSheet.h"


@class UIWebDocumentView;



@interface UIWebRotatingSheet : _UIRotatingActionSheet

{

    _Bool _wasDeferringCallbacks;

    UIWebDocumentView *_webBrowserView;

}



- (void)_disableWebView;

- (void)_enableWebView;

- (void)dealloc;

- (void)doneWithSheet;

- (id)initWithUIWebDocumentView:(id)arg1;

- (_Bool)presentSheet;



@end


