/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "PUActivity.h"


#import "PUPhotoStreamComposeServiceDelegate.h"

#import "PUVideoTrimQueueControllerDelegate.h"



@class NSObject<PLUserEditableAlbumProtocol>, PUActivityItemSourceController, PUPhotoStreamComposeServiceViewController, PUVideoTrimQueueController, UIViewController;



@interface PUAlbumStreamActivity : PUActivity <PUPhotoStreamComposeServiceDelegate, PUVideoTrimQueueControllerDelegate>

{

    PUPhotoStreamComposeServiceViewController *_streamComposeVc;

    double _startTime;

    double _endTime;

    UIViewController *_presenterViewController;

    UIViewController *_activityController;

    PUVideoTrimQueueController *_trimController;

    _Bool _isPresentedFromActivityViewController;

    _Bool _destinationAlbumWasCreated;

    PUActivityItemSourceController *_itemSourceController;

    NSObject<PLUserEditableAlbumProtocol> *_destinationStreamingAlbum;

    UIViewController *_referenceViewController;

    id <PUAlbumStreamActivityDelegate> _delegate;

}



+ (long long)activityCategory;

- (void).cxx_destruct;

- (id)_activityImage;

- (void)_createStreamsPickerContainerWithExisting:(_Bool)arg1;

- (void)_handleDismissWithSuccess:(_Bool)arg1;

- (void)_performPresentationOnViewController:(id)arg1 completion:(id)arg2;

- (void)_prepareToPost:(id)arg1 albumName:(id)arg2 recipients:(id)arg3 comments:(id)arg4;

- (_Bool)_presentActivityOnViewController:(id)arg1 animated:(_Bool)arg2 completion:(id)arg3;

- (void)_publishAssets:(id)arg1 andTrimmedVideoPathInfo:(id)arg2 toAlbum:(id)arg3 orCreateWithName:(id)arg4 comment:(id)arg5 invitationRecipients:(id)arg6 wantsPublicWebsite:(_Bool)arg7 completion:(id)arg8;

- (id)_selectedVideo;

- (_Bool)_sharedAlbumAllowsAdding:(struct NSObject *)arg1;

- (void)_showVideoTooLongAlert;

- (id)activityTitle;

- (id)activityType;

- (id)activityViewController;

- (_Bool)canPerformWithActivityItems:(id)arg1;

- (void)controller:(id)arg1 didCancelTrimmingAssets:(id)arg2;

- (void)controller:(id)arg1 didFinishTrimmingAssets:(id)arg2;

@property(nonatomic) __weak id <PUAlbumStreamActivityDelegate> delegate; // @synthesize delegate=_delegate;

@property _Bool destinationAlbumWasCreated; // @synthesize destinationAlbumWasCreated=_destinationAlbumWasCreated;

@property(retain, nonatomic) NSObject<PLUserEditableAlbumProtocol> *destinationStreamingAlbum; // @synthesize destinationStreamingAlbum=_destinationStreamingAlbum;

- (id)init;

@property(nonatomic, setter=setPresentedFromActivityViewController:) _Bool isPresentedFromActivityViewController; // @synthesize isPresentedFromActivityViewController=_isPresentedFromActivityViewController;

- (id)itemSourceController;

- (void)photoStreamComposeService:(id)arg1 didPostComment:(id)arg2;

- (void)photoStreamComposeServiceDidCancel:(id)arg1;

- (void)prepareWithActivityItems:(id)arg1;

- (void)presentActivityOnViewController:(id)arg1 animated:(_Bool)arg2 completion:(id)arg3;

@property(nonatomic) __weak UIViewController *referenceViewController; // @synthesize referenceViewController=_referenceViewController;

- (void)setItemSourceController:(id)arg1;



@end


