/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "PLAssetContainer.h"



@class NSArray, NSDate, NSIndexSet, NSOrderedSet, NSString, PLCloudFeedEntry, PLCloudSharedAlbumInvitationRecord, PLManagedAsset;



@interface PUFeedSectionInfo : NSObject <PLAssetContainer>

{

    _Bool _loaded;

    _Bool _shouldBeVisibleWhenEmpty;

    PLManagedAsset *_keyAsset;

    PLManagedAsset *_secondaryKeyAsset;

    PLManagedAsset *_tertiaryKeyAsset;

    PLCloudFeedEntry *_cloudFeedEntry;

    long long _sectionType;

    NSDate *_date;

    id <PLCloudSharedAlbumProtocol> _sharedAlbum;

    NSString *_albumTitle;

    PLCloudSharedAlbumInvitationRecord *_invitationRecord;

    long long _numberOfItems;

    NSIndexSet *_excludedAssetIndexes;

}



+ (id)sectionInfoWithCloudFeedEntry:(id)arg1;

- (void).cxx_destruct;

@property(copy, nonatomic) NSString *albumTitle; // @synthesize albumTitle=_albumTitle;

@property(readonly, nonatomic) unsigned long long approximateCount;

- (_Bool)areAllAssetsLiked;

- (id)assetForItemAtIndex:(long long)arg1;

@property(readonly, nonatomic) NSOrderedSet *assets;

@property(readonly, nonatomic) unsigned long long assetsCount;

- (id)assetsForItemAtIndex:(long long)arg1 maximumCount:(long long)arg2;

- (id)batchIDForItemAtIndex:(long long)arg1;

- (_Bool)canPerformEditOperation:(int)arg1;

@property(readonly, nonatomic) _Bool canShowAvalancheStacks;

@property(readonly, nonatomic) _Bool canShowComments;

- (id)captionForItemAtIndex:(long long)arg1;

@property(readonly, nonatomic) PLCloudFeedEntry *cloudFeedEntry; // @synthesize cloudFeedEntry=_cloudFeedEntry;

- (id)commentForItemAtIndex:(long long)arg1;

- (_Bool)containsAsset:(id)arg1;

@property(copy, nonatomic) NSDate *date; // @synthesize date=_date;

@property(copy, nonatomic) NSIndexSet *excludedAssetIndexes; // @synthesize excludedAssetIndexes=_excludedAssetIndexes;

- (void)getCommentCount:(out unsigned long long *)arg1 likeCount:(out unsigned long long *)arg2;

- (void)getPhotoCount:(out unsigned long long *)arg1 videoCount:(out unsigned long long *)arg2;

- (_Bool)hasMultipleAssetsForItemAtIndex:(long long)arg1;

- (long long)indexOfItemWithAsset:(id)arg1;

- (long long)indexOfItemWithComment:(id)arg1;

- (id)initWithCloudFeedEntry:(id)arg1;

@property(retain, nonatomic) PLCloudSharedAlbumInvitationRecord *invitationRecord; // @synthesize invitationRecord=_invitationRecord;

@property(readonly, nonatomic) _Bool isEmpty;

@property(nonatomic, getter=isLoaded) _Bool loaded; // @synthesize loaded=_loaded;

@property(retain, nonatomic) PLManagedAsset *keyAsset; // @synthesize keyAsset=_keyAsset;

- (id)likesForItemAtIndex:(long long)arg1;

@property(readonly, nonatomic) NSArray *localizedLocationNames;

@property(readonly, nonatomic) NSString *localizedTitle;

@property(nonatomic) long long numberOfItems; // @synthesize numberOfItems=_numberOfItems;

@property(readonly, nonatomic) unsigned long long photosCount;

- (void)reload;

@property(retain, nonatomic) PLManagedAsset *secondaryKeyAsset; // @synthesize secondaryKeyAsset=_secondaryKeyAsset;

@property(readonly, nonatomic) long long sectionType; // @synthesize sectionType=_sectionType;

@property(retain, nonatomic) id <PLCloudSharedAlbumProtocol> sharedAlbum; // @synthesize sharedAlbum=_sharedAlbum;

@property(nonatomic) _Bool shouldBeVisibleWhenEmpty; // @synthesize shouldBeVisibleWhenEmpty=_shouldBeVisibleWhenEmpty;

@property(retain, nonatomic) PLManagedAsset *tertiaryKeyAsset; // @synthesize tertiaryKeyAsset=_tertiaryKeyAsset;

@property(readonly, nonatomic) NSString *title;

- (long long)typeForItemAtIndex:(long long)arg1;

- (void)updateFromCloudFeedEntry;

@property(readonly, nonatomic) NSString *uuid;

@property(readonly, nonatomic) unsigned long long videosCount;



// Remaining properties

@property(readonly, nonatomic) NSDate *endDate;

@property(readonly, nonatomic) NSDate *startDate;



@end


