/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "PUCollectionViewLayoutDelegating.h"



@class NSIndexPath, NSSet, NSString;



@protocol PUGridLayoutProtocol <NSObject, PUCollectionViewLayoutDelegating>

- (id)assetIndexPathsForElementsInRect:(struct CGRect)arg1;

@property(nonatomic) double globalBottomPadding;

@property(nonatomic) double globalFooterHeight;

@property(readonly, nonatomic) NSIndexPath *globalFooterIndexPath;

@property(nonatomic) double globalTopPadding;

@property(copy, nonatomic) NSSet *hiddenItemIndexPaths;

- (void)invalidateLayoutForVerticalScroll;

@property(copy, nonatomic) NSString *sectionHeaderElementKind;

@property(nonatomic) double sectionHeaderHeight;

@property(nonatomic) double sectionTopPadding;

@end


