/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "PUAbstractTransitionLayoutAttributes.h"


@class UICollectionViewLayoutAttributes;



@interface PUInterpolatingLayoutAttributes : PUAbstractTransitionLayoutAttributes

{

    _Bool _interpolatesCenter;

    _Bool _interpolatesSize;

    _Bool _interpolatesTransform;

    _Bool _interpolatesAlpha;

    UICollectionViewLayoutAttributes *_sourceLayoutAttributes;

    UICollectionViewLayoutAttributes *_destinationLayoutAttributes;

}



+ (id)layoutAttributesForCellWithIndexPath:(id)arg1;

+ (id)layoutAttributesForCellWithIndexPath:(id)arg1 fromLayoutAttributes:(id)arg2 toLayoutAttributes:(id)arg3;

- (void).cxx_destruct;

@property(retain, nonatomic, getter=_destinationLayoutAttributes, setter=_setDestinationLayoutAttributes:) UICollectionViewLayoutAttributes *destinationLayoutAttributes; // @synthesize destinationLayoutAttributes=_destinationLayoutAttributes;

- (double)_progressOutsideNormalizedRange:(double)arg1;

@property(retain, nonatomic, getter=_sourceLayoutAttributes, setter=_setSourceLayoutAttributes:) UICollectionViewLayoutAttributes *sourceLayoutAttributes; // @synthesize sourceLayoutAttributes=_sourceLayoutAttributes;

- (id)dynamicAnimationsAtVelocity:(double)arg1;

- (void)finishInterpolation;

- (void)updateForProgress;



@end


