/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "PUPhotoBrowserControllerSpec.h"


@interface PUPhotoBrowserControllerPadSpec : PUPhotoBrowserControllerSpec

{

}



+ (id)_libraryImageDataProvider;

- (id)avalancheReviewControllerSpec;

- (id)newPhotoBrowserControllerForPhotoAtIndexPath:(id)arg1 inAssetContainerList:(id)arg2;

- (id)photosSharingViewControllerSpec;

- (_Bool)shouldShowPhotoScrubber;

- (_Bool)shouldShowToolbarItemsInNavigationBar;

- (_Bool)shouldUsePopovers;

- (unsigned long long)supportedInterfaceOrientations;



@end


