/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "PUAlbumListTableViewController.h"


@class NSArray, UIBarButtonItem;



@interface PUUIAlbumListViewController : PUAlbumListTableViewController

{

    UIBarButtonItem *_imagePickerCancelButton;

    NSArray *__imagePickerMediaTypes;

}



- (void).cxx_destruct;

- (void)_handleImagePickerCancel:(id)arg1;

@property(copy, nonatomic, setter=_setImagePickerMediaTypes:) NSArray *_imagePickerMediaTypes; // @synthesize _imagePickerMediaTypes=__imagePickerMediaTypes;

- (void)_setAlbumList:(struct NSObject *)arg1 mediaTypes:(id)arg2;

- (id)init;

- (void)loadView;

- (id)newGridViewControllerForAlbum:(struct NSObject *)arg1;

- (_Bool)pu_wantsNavigationBarVisible;

- (void)setAlbumList:(id)arg1;

- (_Bool)shouldAllowEmailInAlbumSubtitle;

- (unsigned long long)supportedInterfaceOrientations;

- (void)updateNavigationBarAnimated:(_Bool)arg1;

- (void)viewWillAppear:(_Bool)arg1;



@end


