/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "SBKResponse.h"


@class SBKSyncResponseData;



__attribute__((visibility("hidden")))

@interface SBKSyncResponse : SBKResponse

{

    SBKSyncResponseData *_syncResponseData;

}



+ (id)responseWithResponse:(id)arg1 transaction:(id)arg2;

- (void).cxx_destruct;

- (void)_deserializeResponseBodyWithTransaction:(id)arg1;

@property(readonly) SBKSyncResponseData *syncResponseData; // @synthesize syncResponseData=_syncResponseData;



@end


