/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "NSEnumerator.h"



@class NSAttributeDictionary;



__attribute__((visibility("hidden")))

@interface NSAttributeDictionaryEnumerator : NSEnumerator

{

    NSAttributeDictionary *dictionary;

    unsigned long long nextElement;

}



- (void)dealloc;

- (id)initWithAttributeDictionary:(id)arg1;

- (id)nextObject;



@end


