/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@class NSArray, NSDictionary;



@interface IMServiceAgent : NSObject

{

    NSDictionary *_currentAVChatInfo;

}



+ (void)forgetStatusImageAppearance;

+ (id)imageNameForStatus:(unsigned long long)arg1;

+ (id)imageURLForStatus:(unsigned long long)arg1;

+ (id)notificationCenter;

+ (long long)serviceAgentCapabilities;

+ (void)setServiceAgentCapabilities:(long long)arg1;

+ (id)sharedAgent;

@property(readonly, nonatomic) NSDictionary *currentAVChatInfo;

- (void)launchIfNecessary;

@property(retain, nonatomic) NSArray *myAvailableMessages;

@property(retain, nonatomic) NSArray *myAwayMessages;

- (id)myPictureData;

- (id)notificationCenter;

@property(readonly, nonatomic) unsigned long long requestAudioReflectorStart;

@property(readonly, nonatomic) unsigned long long requestAudioReflectorStop;

- (unsigned long long)requestVideoStillForPerson:(id)arg1;

- (id)serviceWithName:(id)arg1;

- (id)serviceWithNameNonBlocking:(id)arg1;

- (void)setMyStatus:(unsigned long long)arg1 message:(id)arg2;

@property(readonly, nonatomic) unsigned long long vcCapabilities;



@end


