/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "DTXTransport.h"


@interface DTXSharedMemoryTransport : DTXTransport

{

    struct DTXSharedMemory *_shm;

    struct dispatch_queue_s *_listenQueue;

    _Bool _creator;

}



+ (id)addressForMemory:(unsigned long long)arg1 inProcess:(int)arg2;

+ (id)addressForPosixSharedMemoryWithName:(id)arg1;

+ (id)schemes;

- (_Bool)_setupCreatingSharedMemory:(id)arg1 size:(int)arg2;

- (_Bool)_setupWithShm:(struct DTXSharedMemory *)arg1 asCreator:(_Bool)arg2;

- (void)dealloc;

- (void)disconnect;

- (id)initWithLocalAddress:(id)arg1;

- (id)initWithLocalName:(id)arg1 size:(int)arg2;

- (id)initWithMemoryAddress:(unsigned long long)arg1 inTask:(unsigned int)arg2;

- (id)initWithRemoteAddress:(id)arg1;

- (id)localAddresses;

@property(nonatomic) int remotePid;

@property(readonly, nonatomic) struct DTXSharedMemory *sharedMemory; // @synthesize sharedMemory=_shm;

@property(readonly, nonatomic) unsigned long long totalSharedMemorySize;

- (unsigned long long)transmit:(const void *)arg1 ofLength:(unsigned long long)arg2;



@end


