/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





#import "UIAlertViewDelegate.h"



@class UIAlertView;



@interface TPAlertViewHelper : NSObject <UIAlertViewDelegate>

{

    id _completionHandler;

    UIAlertView *_alertView;

}



+ (id)_allHelpersArray;

+ (struct dispatch_queue_s *)_workQueue;

+ (id)alertHelperWithHandler:(id)arg1 style:(void)arg2 title:(long long)arg3 message:(id)arg4 cancelButtonTitle:(id)arg5 otherButtonTitles:(id)arg6;

- (id)_initWithTitle:(id)arg1 style:(long long)arg2 message:(id)arg3 cancelButtonTitle:(id)arg4 otherButtonTitles:(id)arg5;

- (id)_underlyingAlertView;

- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;

- (void)dealloc;

- (void)dismissWithCancelAnimated:(_Bool)arg1;

- (void)dismissWithClickedButtonIndexAnimated:(long long)arg1;

@property(readonly) long long firstOtherButtonIndex;

- (void)setCompletionHandler:(id)arg1;

- (void)show;



@end


