/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */





@interface ACDPreferences : NSObject

{

}



+ (id)sharedPreferences;

- (id)objectForKey:(id)arg1;

- (void)reset;

- (double)serverTimeoutInterval;

- (void)setObject:(id)arg1 forKey:(id)arg2;

- (void)synchronize;



@end


