/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIView.h"



@class NSString, UIFont, UILabel;



__attribute__((visibility("hidden")))

@interface SLFacebookLoginInfoFooter : UIView

{

    UIFont *_font;

    NSString *_paragraph1;

    NSString *_paragraph2;

    NSString *_paragraph3;

    NSString *_paragraph4;

    UILabel *_label1;

    UILabel *_label2;

    UILabel *_label3;

    UILabel *_label4;

}



- (void).cxx_destruct;

- (id)initWithFrame:(struct CGRect)arg1;

- (void)layoutSubviews;

- (double)preferredHeightForWidth:(double)arg1;



@end


