/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "SLSheetImagePreviewView.h"


@class UIImageView, UILabel, UIView;



__attribute__((visibility("hidden")))

@interface SLSheetVideoPreviewView : SLSheetImagePreviewView

{

    UIView *_infoBar;

    UIImageView *_videoGlyphView;

    UILabel *_durationLabel;

}



- (void).cxx_destruct;

- (void)_applyConstraints;

- (id)initWithFrame:(struct CGRect)arg1;

- (struct CGSize)intrinsicContentSize;

- (void)setVideoDuration:(double)arg1;



@end


