/*

 *     Generated by class-dump 3.4 (64 bit).

 *

 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.

 */



#import "UIButton.h"



@class NSString;



@interface ACUILinkButton : UIButton

{

    NSString *_acui_titleString;

}



- (void).cxx_destruct;

- (id)_highlightedStringAttributes;

- (id)_normalStringAttributes;

@property(retain) NSString *acui_titleString; // @synthesize acui_titleString=_acui_titleString;

- (void)drawRect:(struct CGRect)arg1;

- (id)initWithText:(id)arg1 target:(id)arg2 action:(SEL)arg3;

- (void)setHighlighted:(_Bool)arg1;



@end


